<?php
/**
 * RBEA Styles test file
 *
 * @package category
 */

/**
 * Require frontend styles helper class
 */
require_once plugin_dir_path( dirname( __FILE__ ) ) . 'classes/class-responsive-block-editor-addons-frontend-styles.php';

/**
 * Frontend styles test class
 */
class Responsive_Block_Editor_Addons_Frontend_Styles_Test extends WP_UnitTestCase {
	/**
	 * The Responsive_Block_Editor_Addons_Front_Styles_Helper class instance .
	 *
	 * @access public
	 * @var    string    $rbea_frontend_styles class instance.
	 */
	public static $rbea_frontend_styles;

	/**
	 * Setup class instance
	 *
	 * @param class WP_UnitTest_Factory $factory class instance.
	 */
	public static function wpSetUpBeforeClass( WP_UnitTest_Factory $factory ) {
		self::$rbea_frontend_styles = new Responsive_Block_Editor_Addons_Frontend_Styles();
	}

	/**
	 * Test for Responsive_Block_Editor_Addons_Frontend_Styles_Helper class constructor
	 */
	public function test_responsive_block_editor_addons_frontend_styles_constructor() {
		self::$rbea_frontend_styles = new Responsive_Block_Editor_Addons_Frontend_Styles();
		$this->assertTrue( self::$rbea_frontend_styles instanceof Responsive_Block_Editor_Addons_Frontend_Styles );
	}

	/**
	 * Test get_css_value function
	 */
	public function test_get_css_value() {
		$value = self::$rbea_frontend_styles->get_css_value( '' );
		$this->assertEquals( '', '' );
		$value = self::$rbea_frontend_styles->get_css_value( 0 );
		$this->assertEquals( 0, $value );
		$value = self::$rbea_frontend_styles->get_css_value( 0, 'px' );
		$this->assertEquals( 0, $value );
		$value = self::$rbea_frontend_styles->get_css_value( 10, 'px' );
		$this->assertEquals( '10px', $value );
	}

	/**
	 * Test generate background effect
	 */
	public function test_generate_background_image_effect() {
		$gradient = self::$rbea_frontend_styles->generate_background_image_effect( 'rgb(16, 101, 156, 0.2)', 'rgb(51, 51, 51, 0.2)', 50, 60, 90 );
		$this->assertEquals( 'linear-gradient(50deg, rgb(16, 101, 156, 0.2) 60%,rgb(51, 51, 51, 0.2) 90%)', $gradient );
	}

	/**
	 * Test for hex to rgba
	 */
	public function test_hex_to_rgb() {
		$rgb            = self::$rbea_frontend_styles->hex_to_rgb( '#123456' );
		$expected_value = 'rgba(' . hexdec( '12' ) . ', ' . hexdec( '34' ) . ', ' . hexdec( '56' ) . ', 0.0)';
		$this->assertEquals( $expected_value, $rgb );
		$rgb            = self::$rbea_frontend_styles->hex_to_rgb( '#12abff', false );
		$expected_value = 'rgba(' . hexdec( '12' ) . ', ' . hexdec( 'ab' ) . ', ' . hexdec( 'ff' ) . ', 0.0)';
		$this->assertEquals( $expected_value, $rgb );
		$rgb            = self::$rbea_frontend_styles->hex_to_rgb( '#ab4653', 0.7 );
		$expected_value = 'rgba(' . hexdec( 'ab' ) . ', ' . hexdec( '46' ) . ', ' . hexdec( '53' ) . ', 0.7)';
		$this->assertEquals( $expected_value, $rgb );
	}

	/**
	 * Test for Responsive_Block_Editor_Addons_Frontend_Styles helper functions
	 */
	public function test_responsive_block_editor_addons_frontend_styles_helpers() {
		$this->assertTrue( method_exists( 'Responsive_Block_Editor_Addons_Frontend_Styles', 'hex_to_rgb' ) );
		$this->assertTrue( method_exists( 'Responsive_Block_Editor_Addons_Frontend_Styles', 'get_css_value' ) );
		$this->assertTrue( method_exists( 'Responsive_Block_Editor_Addons_Frontend_Styles', 'generate_background_image_effect' ) );
	}

	/**
	 * Test the values for default attributes for call to action block
	 */
	public function test_responsive_block_advanced_heading_default_attributes() {
		$expected_values = array(
			'block_id'                      => '',
			'headingTitle'                  => '',
			'headingDesc'                   => '',
			'seperatorStyle'                => 'solid',
			'separatorWidthType'            => '%',
			'separatorColor'                => '',
			'headingTitleColor'             => '',
			'subHeadingTitleColor'          => '',
			'headingTitleFontFamily'        => '',
			'subHeadingTitleFontFamily'     => '',
			'headingTitleFontSize'          => '',
			'subHeadingTitleFontSize'       => '',
			'headingTitleFontSizeTablet'    => '',
			'subHeadingTitleFontSizeTablet' => '',
			'headingTitleFontSizeMobile'    => '',
			'subHeadingTitleFontSizeMobile' => '',
			'headingTitleFontWeight'        => '600',
			'subHeadingTitleFontWeight'     => '400',
			'headingTag'                    => 'h2',
			'headingAlignment'              => 'center',
			'headingAlignmentTablet'        => 'center',
			'headingAlignmentMobile'        => 'center',
			'showHeading'                   => true,
			'showSubHeading'                => true,
			'showSeparator'                 => true,
			'separatorHeight'               => 3,
			'separatorWidth'                => 20,
			'headSpacing'                   => 15,
			'subheadSpacing'                => 15,
			'separatorSpacing'              => 15,
			'headSpacingTablet'             => 15,
			'subheadSpacingTablet'          => 15,
			'separatorSpacingTablet'        => 15,
			'headSpacingMobile'             => 15,
			'subheadSpacingMobile'          => 15,
			'separatorSpacingMobile'        => 15,
			'headingTitleLineHeight'        => 1,
			'subHeadingTitleLineHeight'     => 1,
			'headingTitleLetterSpacing'     => 0,
			'subHeadingTitleLetterSpacing'  => 0,
			'level'                         => 2,
			'textDecoration'                => 'none',
			'textDecorationSubHeading'      => 'none',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_advanced_heading_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test the values for default attributes for expand block
	 */
	public function test_responsive_block_expand_default_attributes() {
		$expected_values = array(
			'block_id'        => '',
			'blockTitle'      => 'Title for this block',
			'expandLessText'  => 'Some short text that can be expanded to show more details.',
			'expandMoreText'  => 'Some short text that can be expanded to show more details. Description for this block. Use this space for describing your block. Any text will do. Description for this block. You can use this space for describing your block.',
			'moreLabel'       => 'Show more',
			'lessLabel'       => 'Show less',
			'showTitle'       => true,
			'expandAlignment' => '',
			'textColor'       => '',
			'linkColor'       => '',
			'titleColor'      => '',
			'titleSpace'      => 28,
			'textSpace'       => 20,
			'linkSpace'       => 18,
			'titleFontFamily' => '',
			'textFontFamily'  => '',
			'linkFontFamily'  => '',
			'titleFontSize'   => 20,
			'titleFontWeight' => 400,
			'titleLineHeight' => 1,
			'textFontSize'    => 16,
			'textFontWeight'  => 400,
			'textLineHeight'  => 2,
			'linkFontSize'    => 16,
			'linkFontWeight'  => 400,
			'linkLineHeight'  => 1,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_expand_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for default attributes of post grid block
	 */
	public function test_get_responsive_block_post_grid_block_default_attributes() {
		$expected_values = array(
			'textAlignment'               => 'left',
			'postsToShow'                 => 6,
			'stackonMobile'               => true,
			'displayPostDate'             => true,
			'excludeCurrentPost'          => true,
			'displayPostExcerpt'          => true,
			'displayPostAuthor'           => true,
			'displayPostImage'            => true,
			'displayPostLink'             => true,
			'displayPostTitle'            => true,
			'displaySectionTitle'         => false,
			'postPagination'              => false,
			'equalHeight'                 => true,
			'postTitleTag'                => 'h3',
			'postLayout'                  => 'grid',
			'columns'                     => 2,
			'align'                       => 'center',
			'width'                       => 'wide',
			'orderBy'                     => 'date',
			'order'                       => 'desc',
			'readMoreText'                => 'Read More »',
			'offset'                      => 0,
			'excerptLength'               => 55,
			'postType'                    => 'post',
			'postTaxonomy'                => 'category',
			'taxonomyType'                => 'category',
			'paginationAlignment'         => 'left',
			'paginationLayout'            => '',
			'sectionTag'                  => 'section',
			'sectionTitle'                => '',
			'sectionTitleTag'             => 'h2',
			'imageSize'                   => 'full',
			'id'                          => '',
			'bgColor'                     => '#e4e4e4',
			'paginationBorderColor'       => '#e4e4e4',
			'paginationTextActiveColor'   => '',
			'paginationTextColor'         => '',
			'paginationActiveBorderColor' => '',
			'paginationBorderWidth'       => '',
			'paginationBorderRadius'      => '',
			'paginationSpacing'           => '',
			'imageBorderRadius'           => '',
			'textColor'                   => '#444444',
			'previousButtonText'          => 'Previous',
			'nextButtonText'              => 'Next',
			'imagePosition'               => 'top',
			'layout'                      => 'boxed',
			'metaColor'                   => '#444444',
			'readMoreLinkColor'           => '#0066cc',
			'readMoreHoverColor'          => '#0558ab',
			'titleColor'                  => '#444444',
			'titleHoverColor'             => '#444444',
			'contentPadding'              => 30,
			'mobileContentPadding'        => 10,
			'continueFontSize'            => '',
			'continueLineHeight'          => '',
			'continueFontWeight'          => '',
			'continueTextTransform'       => '',
			'titleFontSize'               => '',
			'titleFontSizeMobile'         => '',
			'titleFontSizeTablet'         => '',
			'titleLineHeight'             => '',
			'titleFontWeight'             => '',
			'titleTextTransform'          => '',
			'metaFontSize'                => '',
			'metaLineHeight'              => '',
			'metaFontWeight'              => '',
			'metaTextTransform'           => '',
			'titleFontFamily'             => '',
			'metaFontFamily'              => '',
			'excerptFontFamily'           => '',
			'excerptFontSize'             => '',
			'excerptLineHeight'           => '',
			'excerptFontWeight'           => '',
			'excerptTextTransform'        => '',
			'excerptBottomSpacing'        => '',
			'metaBottomSpacing'           => '',
			'titleBottomSpacing'          => '',
			'columnGap'                   => 20,
			'rowGap'                      => 0,
			'rowGapMobile'                => 0,
			'rowGapTablet'                => 0,
			'blockBorderWidth'            => '0',
			'blockBorderRadius'           => '0',
			'blockBorderStyle'            => 'none',
			'blockBorderColor'            => '#333',
			'pageLimit'                   => '10',
			'taxonomyType'                => 'category',
			'postGridBlockId'             => '',
			'boxShadowColor'              => '',
			'boxShadowHOffset'            => '0',
			'boxShadowVOffset'            => '0',
			'boxShadowBlur'               => '0',
			'boxShadowSpread'             => '0',
			'boxShadowPosition'           => 'outset',
			'hoverboxShadowColor'         => '#cccccc',
			'hoverboxShadowHOffset'       => 0,
			'hoverboxShadowVOffset'       => 0,
			'hoverboxShadowBlur'          => 6,
			'hoverboxShadowSpread'        => 1,
			'hoverboxShadowPosition'      => 'outset',
			'columnGapTablet'             => 20,
			'columnGapMobile'             => 20,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_post_grid_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for default attributes of post carousel block
	 */
	public function test_get_responsive_block_post_carousel_default_attributes() {
		$expected_values = array(
			'blockAlign'           => 'left',
			'columns'              => 2,
			'tcolumns'             => 1,
			'mcolumns'             => 1,
			'block_id'             => 1,
			'autoplaySpeed'        => 2000,
			'autoplay'             => true,
			'infiniteLoop'         => true,
			'pauseOnHover'         => true,
			'transitionSpeed'      => 500,
			'arrowSize'            => 20,
			'arrowDots'            => 'arrows_dots',
			'arrowBorderSize'      => 1,
			'arrowBorderRadius'    => 0,
			'postsToShow'          => 6,
			'displayPostDate'      => true,
			'displayPostExcerpt'   => true,
			'displayPostAuthor'    => true,
			'displayPostImage'     => true,
			'displayPostLink'      => true,
			'displayPostTitle'     => true,
			'displayPostComment'   => true,
			'displayPostTaxonomy'  => true,
			'buttonTarget'         => false,
			'equalHeight'          => true,
			'categories'           => '',
			'className'            => '',
			'postTitleTag'         => 'h3',
			'align'                => 'center',
			'order'                => 'desc',
			'orderBy'              => 'date',
			'readMoreText'         => 'Continue Reading',
			'offset'               => 0,
			'excerptLength'        => 20,
			'postType'             => 'post',
			'sectionTag'           => 'section',
			'sectionTitle'         => '',
			'sectionTitleTag'      => 'h2',
			'imageSize'            => 'full',
			'ctaHoverColor'        => '#ffffff',
			'bgColor'              => '#ffffff',
			'ctaColor'             => '#ffffff',
			'ctaBackColor'         => '#333333',
			'titleColor'           => '#333333',
			'contentColor'         => '#333333',
			'metaColor'            => '#333333',
			'arrowDotsColor'       => '#333333',
			'ctaHoverBackColor'    => '#444444',
			'ctaBorderColor'       => '',
			'ctaHoverBorderColor'  => '',
			'ctaBorderStyle'       => 'none',
			'ctaBorderRadius'      => 0,
			'ctaBorderWidth'       => 2,
			'ctaHpadding'          => 20,
			'ctaVpadding'          => 15,
			'contentPadding'       => 20,
			'contentPaddingMobile' => 20,
			'rowGap'               => 20,
			'columnGap'            => 20,
			'imageSpace'           => null,
			'titleSpace'           => null,
			'dateSpace'            => 20,
			'excerptSpace'         => 20,
			'ctaSpace'             => 20,
			'titleFontSize'        => 20,
			'titleFontSizeMobile'  => 20,
			'titleFontSizeTablet'  => 20,
			'titleFontWeight'      => 100,
			'titleLineHeight'      => 1,
			'metaFontSize'         => 16,
			'metaFontWeight'       => 100,
			'metaLineHeight'       => 1,
			'excerptFontSize'      => 16,
			'excerptFontWeight'    => 100,
			'excerptLineHeight'    => 1,
			'ctaFontSize'          => 16,
			'ctaFontWeight'        => 100,
			'ctaLineHeight'        => 1,
			'opacity'              => 50,
			'imagePosition'        => 'background',
			'titleFontFamily'      => '',
			'metaFontFamily'       => '',
			'excerptFontFamily'    => '',
			'ctaFontFamily'        => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_post_carousel_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for default attributes of buttons block
	 */
	public function test_get_responsive_block_buttons_default_attributes() {
		$expected_values = array();
		$values          = self::$rbea_frontend_styles->get_responsive_block_buttons_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for accordion block default attributes
	 */
	public function test_get_responsive_block_accordian_block_default_attributes() {
		$expected_values = array(
			'block_id'                        => '',
			'layout'                          => 'accordion',
			'inactiveOtherItems'              => true,
			'expandFirstItem'                 => false,
			'enableSchemaSupport'             => false,
			'align'                           => 'left',
			'rowsGap'                         => 10,
			'columnsGap'                      => 10,
			'boxPaddingTypeMobile'            => 'px',
			'boxPaddingTypeTablet'            => 'px',
			'boxPaddingTypeDesktop'           => 'px',
			'vBoxPaddingMobile'               => 10,
			'hBoxPaddingMobile'               => 10,
			'vBoxPaddingTablet'               => 10,
			'hBoxPaddingTablet'               => 10,
			'vBoxPaddingDesktop'              => 10,
			'hBoxPaddingDesktop'              => 10,
			'titleTextColor'                  => '#313131',
			'titleTextActiveColor'            => '#656565',
			'titlePaddingTypeDesktop'         => 'px',
			'vtitlePaddingMobile'             => 10,
			'vtitlePaddingTablet'             => 10,
			'vtitlePaddingDesktop'            => 10,
			'htitlePaddingMobile'             => 10,
			'htitlePaddingTablet'             => 10,
			'htitlePaddingDesktop'            => 10,
			'contentTextColor'                => '#313131',
			'contentPaddingTypeDesktop'       => 'px',
			'vcontentPaddingMobile'           => 10,
			'vcontentPaddingTablet'           => 10,
			'vcontentPaddingDesktop'          => 10,
			'hcontentPaddingMobile'           => 10,
			'hcontentPaddingTablet'           => 10,
			'hcontentPaddingDesktop'          => 10,
			'titleActiveTextColor'            => '',
			'titleActiveBackgroundColor'      => '',
			'iconColor'                       => '',
			'iconActiveColor'                 => '',
			'titleFontWeight'                 => '',
			'titleFontSize'                   => '',
			'titleLineHeight'                 => '',
			'titleFontFamily'                 => '',
			'contentFontFamily'               => '',
			'contentFontWeight'               => '',
			'contentFontSize'                 => '',
			'contentLineHeight'               => '',
			'icon'                            => 'fas fa-plus',
			'iconActive'                      => 'fas fa-minus',
			'iconAlign'                       => 'row',
			'iconSize'                        => 12,
			'iconSizeTablet'                  => 12,
			'iconSizeMobile'                  => 12,
			'iconSizeType'                    => 'px',
			'columns'                         => 2,
			'schema'                          => '',
			'enableToggle'                    => true,
			'equalHeight'                     => true,
			'titleLeftPaddingTablet'          => 10,
			'titleBottomPaddingTablet'        => 10,
			'titleLeftPaddingDesktop'         => 10,
			'titleBottomPaddingDesktop'       => 10,
			'titleLeftPaddingMobile'          => 10,
			'titleBottomPaddingMobile'        => 10,
			'headingTag'                      => 'span',
			'titleBackgroundColorOpacity'     => 100,
			'marginV'                         => '',
			'marginH'                         => '',
			'titleSecondaryBackgroundColor'   => '',
			'titleGradientDegree'             => 100,
			'titleBgGradient'                 => false,
			'titleBackgroundColor'            => '#ffffff',
			'contentSecondaryBackgroundColor' => '',
			'contentGradientDegree'           => 100,
			'contentBgGradient'               => false,
			'contentBackgroundColor'          => '#eeeeee',
			'contentBackgroundColorOpacity'   => 100,
			'borderStyle'                     => 'solid',
			'borderColor'                     => '',
			'borderRadius'                    => 2,
			'borderWidth'                     => 1,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_accordian_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for accordion child block default attributes
	 */
	public function test_get_responsive_block_accordian_child_block_default_attributes() {
		$expected_values = array(
			'block_id'          => '',
			'title'             => 'What is Accordion?',
			'content'           => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
			'icon'              => 'fas fa-plus',
			'iconActive'        => 'fas fa-minus',
			'layout'            => 'accordion',
			'headingTag'        => 'span',
			'borderStyle'       => 'solid',
			'borderColor'       => 'black',
			'borderWidth'       => 1,
			'borderRadius'      => 2,
			'boxShadowColor'    => '#fff',
			'boxShadowHOffset'  => 9,
			'boxShadowVOffset'  => 9,
			'boxShadowBlur'     => 9,
			'boxShadowSpread'   => 9,
			'boxShadowPosition' => 'outset',
			'titlePadding'      => 10,
			'contentPadding'    => 10,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_accordian_child_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for advanced column child block default attributes
	 */
	public function test_get_responsive_block_advanced_column_child_block_default_attributes() {
		$expected_values = array(
			'width'                    => 50,
			'topPadding'               => '',
			'bottomPadding'            => '',
			'leftPadding'              => '',
			'rightPadding'             => '',
			'leftMargin'               => '',
			'rightMargin'              => '',
			'topMargin'                => '',
			'bottomMargin'             => '',
			'topPaddingTablet'         => '',
			'bottomPaddingTablet'      => '',
			'leftPaddingTablet'        => '',
			'rightPaddingTablet'       => '',
			'leftMarginTablet'         => '',
			'rightMarginTablet'        => '',
			'topMarginTablet'          => '',
			'bottomMarginTablet'       => '',
			'topPaddingMobile'         => '',
			'bottomPaddingMobile'      => '',
			'leftPaddingMobile'        => '',
			'rightPaddingMobile'       => '',
			'leftMarginMobile'         => '',
			'rightMarginMobile'        => '',
			'topMarginMobile'          => '',
			'bottomMarginMobile'       => '',
			'block_id'                 => '',
			'blockBorderStyle'         => 'none',
			'blockBorderWidth'         => 1,
			'blockBorderRadius'        => '',
			'blockBorderColor'         => '',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => 0,
			'boxShadowSpread'          => 0,
			'boxShadowPosition'        => 'outset',
			'hoverboxShadowColor'      => '#cccccc',
			'hoverboxShadowHOffset'    => 0,
			'hoverboxShadowVOffset'    => 0,
			'hoverboxShadowBlur'       => 6,
			'hoverboxShadowSpread'     => 1,
			'hoverboxShadowPosition'   => 'outset',
			'opacity'                  => 20,
			'colorLocation1'           => 0,
			'colorLocation2'           => 100,
			'gradientDirection'        => 90,
			'hovercolorLocation1'      => 0,
			'hovercolorLocation2'      => 100,
			'hovergradientDirection'   => 90,
			'backgroundImage'          => '',
			'backgroundPosition'       => 'center center',
			'backgroundSize'           => 'cover',
			'backgroundRepeat'         => 'no-repeat',
			'backgroundAttachment'     => 'scroll',
			'backgroundImageColor'     => '',
			'overlayType'              => 'color',
			'gradientOverlayColor1'    => '',
			'gradientOverlayColor2'    => '',
			'gradientOverlayType'      => 'linear',
			'gradientOverlayLocation1' => 0,
			'gradientOverlayLocation2' => 100,
			'gradientOverlayAngle'     => 0,
			'gradientOverlayPosition'  => 'center center',
			'backgroundType'           => '',
			'backgroundColor'          => '',
			'backgroundColor1'         => '',
			'backgroundColor2'         => '#fff',
			'hoverbackgroundColor1'    => '',
			'hoverbackgroundColor2'    => '#fff',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_advanced_column_child_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for buttons child default attributes
	 */
	public function test_get_responsive_block_buttons_child_default_attributes() {
		$expected_values = array(
			'buttonAlignment'      => 'center',
			'fontFamily'           => 'Default',
			'fontWeight'           => '',
			'fontSubset'           => '',
			'label'                => '#Click Here',
			'link'                 => '',
			'target'               => '_blank',
			'iconsize'             => 16,
			'counterId'            => 1,
			'vPadding'             => 10,
			'hPadding'             => 14,
			'vPaddingTablet'       => 10,
			'hPaddingTablet'       => 14,
			'vPaddingMobile'       => 10,
			'hPaddingMobile'       => 14,
			'vMargin'              => 10,
			'vMarginTablet'        => 10,
			'vMarginMobile'        => 10,
			'hMargin'              => 14,
			'hMarginTablet'        => 10,
			'hMarginMobile'        => 5,
			'borderWidth'          => 1,
			'borderRadius'         => 2,
			'borderStyle'          => 'solid',
			'borderColor'          => '',
			'borderHColor'         => '',
			'color'                => '',
			'background'           => '',
			'hColor'               => '',
			'sizeType'             => 'px',
			'sizeMobile'           => '',
			'sizeTablet'           => '',
			'lineHeight'           => '',
			'lineHeightType'       => 'em',
			'lineHeightMobile'     => '',
			'lineHeightTablet'     => '',
			'opensInNewTab'        => '',
			'colorLocation1'       => 0,
			'colorLocation2'       => 100,
			'gradientDirection'    => 90,
			'backgroundColor1'     => '',
			'backgroundColor2'     => '',
			'opacity'              => 100,
			'icon'                 => '',
			'iconPosition'         => 'after',
			'buttonFontFamily'     => '',
			'buttonFontSize'       => '',
			'buttonFontSizeTablet' => '',
			'buttonFontSizeMobile' => '',
			'buttonLineHeight'     => '',
			'boxShadowColor'       => '',
			'boxShadowHOffset'     => 0,
			'boxShadowVOffset'     => 0,
			'boxShadowBlur'        => '',
			'boxShadowSpread'      => '',
			'boxShadowPosition'    => 'outset',
			'icon_color'           => '#3a3a3a',
			'icon_hover_color'     => '',
			'hbackground'          => '',
			'iconSpace'            => 8,
			'buttonFontWeight'     => '400',
			'inheritFromTheme'     => false,
			'hoverEffect'          => '',
			'backgroundType'       => 'none',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_buttons_child_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for call to action default attributes
	 */
	public function test_get_responsive_block_call_to_action_default_attributes() {
		$expected_values = array(
			'block_id'                 => '',
			'buttonText'               => '',
			'buttonUrl'                => '',
			'buttonAlignment'          => 'center',
			'buttonBackgroundColor'    => '#2091e1',
			'buttonTextColor'          => '#fff',
			'buttonSize'               => 'responsive-block-editor-addons-cta-button-size-medium',
			'buttonShape'              => 'responsive-block-editor-addons-cta-button-shape-rounded',
			'buttonTarget'             => false,
			'ctaTitle'                 => '',
			'ctaTitleFontFamily'       => '',
			'ctaTextFontFamily'        => '',
			'ctaTitleFontSize'         => '22',
			'ctaTitleFontSizeMobile'   => '22',
			'ctaTitleFontSizeTablet'   => '22',
			'ctaTextFontSize'          => '16',
			'ctaTextFontSizeMobile'    => '16',
			'ctaTextFontSizeTablet'    => '16',
			'ctaText'                  => '',
			'ctaWidth'                 => '',
			'ctaBackgroundColor'       => '#f2f2f2',
			'ctaTextColor'             => '',
			'imgURL'                   => '',
			'imgID'                    => '',
			'imgAlt'                   => '',
			'dimRatio'                 => 50,
			'opacity'                  => 100,
			'headingLineHeight'        => 1.8,
			'headingFontWeight'        => '400',
			'contentLineHeight'        => 1.75,
			'contentFontWeight'        => '400',
			'buttonvPadding'           => 10,
			'buttonhPadding'           => 14,
			'buttonborderWidth'        => 1,
			'buttonborderStyle'        => 'solid',
			'icon'                     => '',
			'iconPosition'             => 'after',
			'counterId'                => 1,
			'hbuttonBackgroundColor'   => '',
			'hbuttonTextColor'         => '#e6f2ff',
			'buttonborderColor'        => '',
			'buttonborderHColor'       => '',
			'resctaType'               => 'button',
			'ctalinkText'              => '',
			'titleSpace'               => 25,
			'subtitleSpace'            => 28,
			'titleSpaceMobile'         => 25,
			'subtitleSpaceMobile'      => 28,
			'titleSpaceTablet'         => 25,
			'subtitleSpaceTablet'      => 28,
			'iconSpace'                => 8,
			'colorLocation1'           => 0,
			'colorLocation2'           => 100,
			'gradientDirection'        => 90,
			'backgroundColor1'         => '',
			'backgroundColor2'         => '',
			'backgroundType'           => 'color',
			'buttoncolorLocation1'     => 0,
			'buttoncolorLocation2'     => 100,
			'buttongradientDirection'  => 90,
			'buttonbackgroundColor1'   => '',
			'buttonbackgroundColor2'   => '',
			'buttonbackgroundType'     => 'color',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => '',
			'boxShadowSpread'          => '',
			'boxShadowPosition'        => 'outset',
			'icon_color'               => '#3a3a3a',
			'topPadding'               => 20,
			'bottomPadding'            => 20,
			'leftPadding'              => 20,
			'rightPadding'             => 20,
			'topPaddingMobile'         => 20,
			'bottomPaddingMobile'      => 20,
			'leftPaddingMobile'        => 20,
			'rightPaddingMobile'       => 20,
			'topPaddingTablet'         => 20,
			'bottomPaddingTablet'      => 20,
			'leftPaddingTablet'        => 20,
			'rightPaddingTablet'       => 20,
			'imagePosition'            => 'center center',
			'imageRepeat'              => 'no-repeat',
			'thumbsize'                => 'cover',
			'buttonSpace'              => 28,
			'buttonSpaceMobile'        => 28,
			'buttonSpaceTablet'        => 28,
			'borderRadius'             => 12,
			'buttonTextFontFamily'     => '',
			'buttonTextFontSize'       => 18,
			'buttonTextFontSizeMobile' => 18,
			'buttonTextFontSizeTablet' => 18,
			'buttonTextLineHeight'     => 1,
			'buttonTextFontWeight'     => '400',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_call_to_action_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for card block default attributes
	 */
	public function test_get_responsive_block_card_default_attributes() {
		$expected_values = array(
			'block_id'                => '',
			'cardsArray'              => '',
			'count'                   => '',
			'gutter'                  => 'medium',
			'stack'                   => 'mobile',
			'contentAlign'            => 'center',
			'textColor'               => '',
			'itemBackgroundColor'     => '',
			'buttonColor'             => '',
			'buttonTextColor'         => '#fff',
			'boxShadowColor'          => '',
			'boxShadowHOffset'        => 0,
			'boxShadowVOffset'        => 0,
			'boxShadowBlur'           => 0,
			'boxShadowSpread'         => 0,
			'boxShadowPosition'       => 'outset',
			'titleSpace'              => 8,
			'subtitleSpace'           => 16,
			'contentSpace'            => 16,
			'buttonSpace'             => 20,
			'borderWidth'             => 0,
			'borderRadius'            => 12,
			'opacity'                 => 100,
			'resshowImage'            => true,
			'colorLocation1'          => 0,
			'colorLocation2'          => 100,
			'gradientDirection'       => 90,
			'backgroundImage'         => '',
			'backgroundColor'         => '',
			'backgroundColor1'        => '',
			'backgroundColor2'        => '#fff',
			'backgroundType'          => 'none',
			'imageopacity'            => 20,
			'imageSize'               => 'full',
			'imagePosition'           => 'center center',
			'imageRepeat'             => 'no-repeat',
			'thumbsize'               => 'cover',
			'imageheight'             => 200,
			'blockmargin'             => 2,
			'blockzindex'             => 1,
			'icon'                    => '',
			'iconPosition'            => 'after',
			'icon_color'              => '#3a3a3a',
			'counterId'               => 1,
			'buttonhColor'            => '',
			'buttonhTextColor'        => '#e6f2ff',
			'butopacity'              => 100,
			'vPadding'                => 10,
			'hPadding'                => 14,
			'vMargin'                 => 10,
			'hMargin'                 => 0,
			'butborderWidth'          => 1,
			'butborderRadius'         => 2,
			'butborderStyle'          => 'none',
			'buttonSize'              => 'responsive-block-editor-addons-button-size-medium',
			'buttoncolorLocation1'    => 0,
			'buttoncolorLocation2'    => 100,
			'buttongradientDirection' => 90,
			'buttonbackgroundColor1'  => '',
			'buttonbackgroundColor2'  => '#fff',
			'buttonbackgroundType'    => 'none',
			'icon_hcolor'             => '#3a3a3a',
			'headingFontFamily'       => '',
			'subFontFamily'           => '',
			'contentFontFamily'       => '',
			'subLineHeight'           => 1,
			'subFontWeight'           => 400,
			'subFontSize'             => 16,
			'headingLineHeight'       => 1,
			'headingFontWeight'       => 900,
			'headingFontSize'         => 20,
			'contentLineHeight'       => 2,
			'contentFontSize'         => 16,
			'contentFontWeight'       => 400,
			'blockbotmargin'          => 2,
			'blockleftmargin'         => 0,
			'blockrightmargin'        => 0,
			'contenttopSpace'         => 16,
			'bgimageSize'             => 'full',
			'bgimagePosition'         => 'center center',
			'bgimageRepeat'           => 'no-repeat',
			'bgthumbsize'             => 'cover',
			'borderStyle'             => 'none',
			'buttonTarget'            => 'false',
			'contentAlignment'        => 'left',
			'borderColor'             => '',
			'backgroundImageOne'      => '',
			'backgroundImageTwo'      => '',
			'backgroundImageThree'    => '',
			'backgroundImageFour'     => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_card_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for content timeline default attributes
	 */
	public function test_get_responsive_block_content_timeline_default_attributes() {
		$expected_values = array(
			'block_id'            => '',
			'timelinAlignment'    => 'center',
			'timelineItems'       => '',
			'dateFormat'          => 'F j, Y',
			'headingTag'          => 'h4',
			't_date'              => '',
			'displayPostDate'     => true,
			'count'               => 5,
			'dateBottomspace'     => 5,
			'itemBorderStyle'     => 'none',
			'itemBorderColor'     => '',
			'itemBorderWidth'     => 1,
			'itemBorderRadius'    => 2,
			'itemPadding'         => 20,
			'horizontalSpace'     => 0,
			'verticalSpace'       => 15,
			'headingBottomMargin' => 15,
			'dateLineHeight'      => 1,
			'contentFontFamily'   => '',
			'headingFontFamily'   => '',
			'dateFontFamily'      => '',
			'dateFontWeight'      => '400',
			'dateFontSize'        => 16,
			'headingLineHeight'   => 1,
			'headingFontWeight'   => '400',
			'headingFontSize'     => 20,
			'dateColor'           => '',
			'headingColor'        => '',
			'contentColor'        => '',
			'backgroundColor'     => '#eee',
			'counterId'           => 1,
			'contentLineHeight'   => 2,
			'contentFontSize'     => 16,
			'contentFontWeight'   => '400',
			'opacity'             => 100,
			'separatorColor'      => '#eee',
			'iconColor'           => '#333',
			'separatorBg'         => '#eee',
			'separatorBorder'     => '#eee',
			'separatorFillColor'  => '#61ce70',
			'iconFocus'           => '#fff',
			'iconBgFocus'         => '#61ce70',
			'borderFocus'         => '#5cb85c',
			'separatorwidth'      => 3,
			'borderwidth'         => 0,
			'connectorBgsize'     => 35,
			'iconSize'            => 20,
			'icon'                => 'fa fa-calendar-alt',
			'stack'               => 'mobile',
			'arrowlinAlignment'   => 'center',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_content_timeline_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for flipbox default attributes
	 */
	public function test_get_responsive_block_flipbox_default_attributes() {
		$expected_values = array(
			'block_id'                 => '',
			'flipboxArray'             => '',
			'count'                    => '',
			'height'                   => 420,
			'iconSize'                 => 50,
			'backIconSize'             => 50,
			'transitionSpeed'          => 8,
			'backgroundImage'          => '',
			'backgroundPosition'       => 'center center',
			'backgroundAttachment'     => 'scroll',
			'backgroundRepeat'         => 'no-repeat',
			'backgroundSize'           => 'cover',
			'backBackgroundImage'      => '',
			'backBackgroundPosition'   => 'center center',
			'backBackgroundAttachment' => 'scroll',
			'backBackgroundRepeat'     => 'no-repeat',
			'backBackgroundSize'       => 'cover',
			'colorOpacity'             => 30,
			'backColorOpacity'         => 30,
			'imageOpacity'             => 30,
			'backImageOpacity'         => 30,
			'buttonbackgroundType'     => 'none',
			'buttoncolorLocation1'     => 0,
			'buttoncolorLocation2'     => 100,
			'buttongradientDirection'  => 90,
			'buttonbackgroundColor1'   => '#333',
			'buttonbackgroundColor2'   => '',
			'buttonHTextColor'         => '#fff',
			'buttonHColor'             => '#333',
			'buttonopacity'            => 100,
			'buttonHopacity'           => 100,
			'buttonHbackgroundType'    => 'none',
			'buttonHcolorLocation1'    => 0,
			'buttonHcolorLocation2'    => 100,
			'buttonHgradientDirection' => 90,
			'buttonHbackgroundColor1'  => '#333',
			'buttonHbackgroundColor2'  => '',
			'buttonBorderRadius'       => 0,
			'buttonHpadding'           => 20,
			'buttonVpadding'           => 10,
			'iconSelected'             => 'editor-textcolor',
			'flipStyleSelected'        => 'LTR',
			'align'                    => 'wide',
			'gutter'                   => 'medium',
			'contentAlign'             => 'center',
			'frontTextColor'           => '',
			'frontBackgroundColor'     => '#fff',
			'backTextColor'            => '',
			'backBackgroundColor'      => '#fff',
			'buttonColor'              => '#333',
			'buttonTextColor'          => '',
			'iconColor'                => '',
			'backIconColor'            => '',
			'borderStyle'              => 'none',
			'borderWidth'              => 2,
			'borderRadius'             => '',
			'borderColor'              => '',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => 0,
			'boxShadowSpread'          => 0,
			'boxShadowPosition'        => 'outset',
			'showFrontIcon'            => true,
			'showFrontTitle'           => true,
			'showFrontSubtitle'        => true,
			'showBackIcon'             => true,
			'showBackTitle'            => true,
			'showBackSubtitle'         => true,
			'showBackButton'           => true,
			'colorButtonSelected'      => '',
			'topMargin'                => 0,
			'bottomMargin'             => 0,
			'topPadding'               => 0,
			'bottomPadding'            => 0,
			'leftPadding'              => 0,
			'rightPadding'             => 0,
			'backtopPadding'           => 0,
			'backbottomPadding'        => 0,
			'backleftPadding'          => 0,
			'backrightPadding'         => 0,
			'flipBoxGutterGap'         => 10,
			'stack'                    => 'mobile',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_flipbox_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for gallery masonry default attributes
	 */
	public function test_get_responsive_block_gallery_masonry_block_default_attributes() {
		$expected_values = array();
		$values          = self::$rbea_frontend_styles->get_responsive_block_gallery_masonry_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for googlemap default attributes
	 */
	public function test_get_responsive_block_googlemap_default_attributes() {
		$expected_values = array(
			'address' => '',
			'apiKey'  => '',
			'zoom'    => 12,
			'height'  => 400,
			'pinned'  => false,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_googlemap_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for icon list block default attributes
	 */
	public function test_get_responsive_block_icon_list_block_default_attributes() {
		$expected_values = array(
			'align'               => 'left',
			'icon_count'          => 1,
			'icons'               => array(),
			'gap'                 => 10,
			'inner_gap'           => 15,
			'iconPosition'        => 'middle',
			'size'                => 16,
			'sizeMobile'          => 16,
			'sizeTablet'          => 16,
			'bgSize'              => 0,
			'bgSizeMobile'        => 0,
			'bgSizeTablet'        => 0,
			'border'              => 0,
			'borderRadius'        => 0,
			'hideLabel'           => false,
			'labelFontFamily'     => '',
			'labelFontWeight'     => '',
			'labelFontSize'       => '',
			'labelFontSizeTablet' => '',
			'labelFontSizeMobile' => '',
			'labelFontLineHeight' => 1,
			'icon_layout'         => 'vertical',
			'fontSizeType'        => 'px',
			'block_id'            => 1,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_icon_list_block_default_attributes();
		$this->assertEquals( $expected_values['icons'], $values['icons'] );
		unset( $expected_values['icons'] );
		unset( $values['icons'] );
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for icons list child default attributes
	 */
	public function test_get_responsive_block_icon_list_child_block_default_attributes() {
		$expected_values = array(
			'label'                   => '#Label',
			'image_icon'              => 'icon',
			'icon'                    => 'fab fa-arrow-circle-right',
			'hideLabel'               => false,
			'image'                   => '',
			'icon_color'              => '#3a3a3a',
			'label_color'             => '',
			'icon_hover_color'        => '',
			'label_hover_color'       => '',
			'icon_bg_color'           => '',
			'icon_bg_hover_color'     => '',
			'icon_border_color'       => '',
			'icon_border_hover_color' => '',
			'link'                    => '#',
			'target'                  => false,
			'disableLink'             => true,
			'block_id'                => 1,
			'source_type'             => 'icon',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_icon_list_child_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for image box default attributes
	 */
	public function test_get_responsive_block_image_boxes_default_attributes() {
		$expected_values = array(
			'block_id'                      => '',
			'imageboxesBlock'               => '',
			'counterId'                     => 1,
			'count'                         => '',
			'titleHeadingTag'               => 'h3',
			'gutter'                        => 'medium',
			'contentAlign'                  => 'center',
			'textColor'                     => '',
			'itemBackgroundColor'           => '#fff',
			'hoverTextColor'                => '',
			'verticalAlignment'             => 'center',
			'itemHoverBackgroundColor'      => '#fff',
			'hoverBorderColor'              => '',
			'titleSpacing'                  => '',
			'descriptionSpacing'            => '',
			'blockBorderRadius'             => '',
			'blockBorderStyle'              => 'solid',
			'blockBorderWidth'              => 2,
			'blockBorderColor'              => '#1E1E1E',
			'boxPaddingLeft'                => 15,
			'boxPaddingRight'               => 15,
			'boxPaddingBottom'              => 15,
			'boxPaddingTop'                 => 15,
			'boxHeight'                     => '',
			'hasArrow'                      => '',
			'hasArrow'                      => '',
			'arrowColor'                    => '',
			'arrowSize'                     => '',
			'boxShadowColor'                => '#fff',
			'boxShadowHOffset'              => 9,
			'boxShadowVOffset'              => 9,
			'boxShadowBlur'                 => 9,
			'opacity'                       => 70,
			'hoverOpacity'                  => 70,
			'boxShadowSpread'               => 9,
			'boxShadowPosition'             => 'outset',
			'backgroundPosition'            => '',
			'backgroundSize'                => '',
			'backgroundRepeat'              => '',
			'imageHoverEffect'              => '',
			'bggradient'                    => '',
			'secondaryBackgroundColor'      => '',
			'hoverSecondaryBackgroundColor' => '',
			'gradientDegree'                => 180,
			'bgGradient'                    => false,
			'hoverGradientDegree'           => 180,
			'hoverBgGradient'               => false,
			'titleFontFamily'               => '',
			'descriptionFontFamily'         => '',
			'titleFontSize'                 => '',
			'titleFontSizeMobile'           => '',
			'titleFontSizeTablet'           => '',
			'titleFontWeight'               => '',
			'imageSize'                     => 'full',
			'titleLineHeight'               => '',
			'titleColor'                    => '#1E1E1E',
			'descriptionFontSize'           => '',
			'descriptionFontWeight'         => '',
			'descriptionLineHeight'         => '',
			'descriptionColor'              => '#1E1E1E',
			'backgroundImageOne'            => '',
			'backgroundImageTwo'            => '',
			'backgroundImageThree'          => '',
			'backgroundImageFour'           => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_image_boxes_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test image slider default attributes
	 */
	public function test_get_responsive_block_image_slider_default_attributes() {
		$expected_values = array(
			'block_id'              => '',
			'gutter'                => 5,
			'gutterMobile'          => 5,
			'gridSize'              => 'lrg',
			'height'                => 400,
			'width'                 => '',
			'customWidth'           => false,
			'pageDots'              => false,
			'prevNextButtons'       => true,
			'autoPlay'              => false,
			'autoPlaySpeed'         => 3000,
			'draggable'             => true,
			'alignCells'            => false,
			'pauseHover'            => false,
			'freeScroll'            => false,
			'isSmallImage'          => false,
			'thumbnails'            => false,
			'responsiveHeight'      => false,
			'borderWidth'           => '',
			'iconBackgroundRadius'  => 20,
			'iconBackgroundOpacity' => 90,
			'iconBackgroundColor'   => '',
			'borderColor'           => '',
			'iconColor'             => '',
			'borderStyle'           => '',
			'counterId'             => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_image_slider_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for info block default attributes
	 */
	public function test_get_responsive_block_info_block_default_attributes() {
		$expected_values = array(
			'block_id'                 => '',
			'inheritFromTheme'         => false,
			'resprefixTitle'           => 'Prefix',
			'classMigrate'             => false,
			'resinfoBlockTitle'        => 'Info Box',
			'resDescHeading'           => 'Click here to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.',
			'resheadingAlign'          => 'center',
			'alignment'                => 'center',
			'resheadingColor'          => '',
			'ressubheadingColor'       => '',
			'resprefixColor'           => '',
			'icon'                     => 'fa fa-star',
			'imgiconPosition'          => 'above-title',
			'resIconSize'              => 40,
			'iconColor'                => '#333',
			'resprefixFontSize'        => '',
			'resprefixFontWeight'      => '',
			'resprefixLineHeight'      => '',
			'resheadingTag'            => 'h3',
			'resheadFontFamily'        => '',
			'ressubHeadFontFamily'     => '',
			'resheadFontSize'          => '',
			'resheadFontSizeMobile'    => '',
			'resheadFontSizeTablet'    => '',
			'resheadFontWeight'        => '700',
			'resheadLineHeight'        => '',
			'ressubHeadFontSize'       => '',
			'ressubHeadFontSizeTablet' => '',
			'ressubHeadFontSizeMobile' => '',
			'ressubHeadFontWeight'     => '100',
			'ressubHeadLineHeight'     => '',
			'resheadSpace'             => 10,
			'ressubHeadSpace'          => 10,
			'resseperatorSpace'        => 10,
			'source_type'              => 'icon',
			'ressourceAlign'           => 'top',
			'resctaTarget'             => false,
			'ctaIcon'                  => '',
			'resseperatorPosition'     => 'after_title',
			'resseperatorStyle'        => 'solid',
			'resseperatorColor'        => '',
			'resseperatorWidth'        => 30,
			'resseparatorWidthType'    => '%',
			'resseperatorThickness'    => 2,
			'resctaType'               => 'none',
			'resctaText'               => 'Read More',
			'resctaLink'               => '#',
			'resctaLinkColor'          => '#333',
			'resctaFontSize'           => '',
			'resctaFontWeight'         => '',
			'resctaBtnLinkColor'       => '#333',
			'resctaBgColor'            => 'transparent',
			'resctaBorderColor'        => '#333',
			'resctaBorderStyle'        => 'solid',
			'ctaBtnVertPadding'        => 10,
			'ctaBtnHrPadding'          => 14,
			'resctaBorderWidth'        => 1,
			'resctaBorderRadius'       => 0,
			'resprefixSpace'           => 5,
			'iconLeftMargin'           => 0,
			'iconRightMargin'          => 0,
			'iconTopMargin'            => 5,
			'iconBottomMargin'         => 5,
			'iconLeftMarginMobile'     => 0,
			'iconRightMarginMobile'    => 0,
			'iconTopMarginMobile'      => 5,
			'iconBottomMarginMobile'   => 5,
			'iconLeftMarginTablet'     => 0,
			'iconRightMarginTablet'    => 0,
			'iconTopMarginTablet'      => 5,
			'iconBottomMarginTablet'   => 5,
			'iconImage'                => '',
			'imageSize'                => 'thumbnail',
			'imageWidth'               => 120,
			'imageWidthTablet'         => '',
			'imageWidthMobile'         => '',
			'imageWidthType'           => true,
			'stack'                    => 'tablet',
			'resshowPrefix'            => true,
			'resshowTitle'             => true,
			'resshowDesc'              => true,
			'blockBorderStyle'         => 'none',
			'blockBorderWidth'         => 1,
			'blockBorderRadius'        => '',
			'blockBorderColor'         => '',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => '',
			'boxShadowSpread'          => '',
			'boxShadowPosition'        => 'outset',
			'imageBoxShadowColor'      => '',
			'imageBoxShadowHOffset'    => 0,
			'imageBoxShadowVOffset'    => 0,
			'imageBoxShadowBlur'       => '',
			'imageBoxShadowSpread'     => '',
			'imageBoxShadowPosition'   => 'outset',
			'counterId'                => 1,
			'boxBackgroundColor'       => '#ffffff',
			'contentPadding'           => 0,
			'opacity'                  => 100,
			'imageopacity'             => 100,
			'imgURL'                   => '',
			'imgID'                    => '',
			'imgAlt'                   => '',
			'dimRatio'                 => 50,
			'hoverctaBtnLinkColor'     => '#333',
			'hoverctaBgColor'          => 'transparent',
			'hoverctaBorderColor'      => '#333',
			'imagePosition'            => 'center center',
			'imageRepeat'              => 'no-repeat',
			'thumbsize'                => 'cover',
			'backgroundAttachment'     => 'scroll',
			'sepSpace'                 => 10,
			'icon_color'               => '#3a3a3a',
			'icon_hcolor'              => '#3a3a3a',
			'resImageBorderColor'      => '#333',
			'resImageBorderStyle'      => 'none',
			'resImageBorderRadius'     => 0,
			'resImageBorderWidth'      => 2,
			'ctaTextFontFamily'        => '',
			'ctaTextFontSize'          => '',
			'ctaTextFontSizeMobile'    => '',
			'ctaTextFontSizeTablet'    => '',
			'ctaTextFontWeight'        => '',
			'ctaTextLineHeight'        => '',
			'ctaBottomMargin'          => 10,
			'hoverboxShadowColor'      => '#ccc',
			'hoverboxShadowHOffset'    => 0,
			'hoverboxShadowVOffset'    => 0,
			'hoverboxShadowBlur'       => 6,
			'hoverboxShadowSpread'     => 1,
			'hoverboxShadowPosition'   => 'outset',
			'iconBackgroundColor'      => '#0066cc',
			'iconBackgroundHoverColor' => '',
			'iconBackgroundType'       => 'none',
			'iconPadding'              => 5,
			'iconBorderRadius'         => 0,
			'iconBorderWidth'          => 1,

		);
		$values = self::$rbea_frontend_styles->get_responsive_block_info_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for post timeline default attributes
	 */
	public function test_get_responsive_block_post_timeline_default_attributes() {
		$expected_values = array(
			'categories'          => '',
			'className'           => '',
			'postsToShow'         => 6,
			'displayPostDate'     => true,
			'displayPostExcerpt'  => true,
			'displayPostAuthor'   => true,
			'displayPostImage'    => true,
			'displayPostLink'     => true,
			'displayPostTitle'    => true,
			'displaySectionTitle' => false,
			'postTitleTag'        => 'h3',
			'postLayout'          => 'grid',
			'columns'             => 2,
			'align'               => 'center',
			'timelinAlignment'    => 'center',
			'arrowlinAlignment'   => 'center',
			'width'               => 'wide',
			'order'               => 'desc',
			'orderBy'             => 'date',
			'readMoreText'        => 'Continue Reading',
			'offset'              => 0,
			'excerptLength'       => 55,
			'postType'            => 'post',
			'sectionTag'          => 'section',
			'sectionTitle'        => '',
			'sectionTitleTag'     => 'h2',
			'imageSize'           => 'full',
			'url'                 => '',
			'source'              => 'attribute',
			'selector'            => 'img',
			'attribute'           => 'src',
			'id'                  => '',
			'bgColor'             => '#e4e4e4',
			'textColor'           => '#333',
			'contentPadding'      => 20,
			'authorSpace'         => '',
			'excerptSpace'        => '',
			'blockSpace'          => '',
			'headingSpace'        => '',
			'headingColor'        => '#333',
			'authorColor'         => '#626e81',
			'continueColor'       => '#333',
			'dateFontFamily'      => '',
			'headingFontFamily'   => '',
			'authorFontFamily'    => '',
			'contentFontFamily'   => '',
			'continueFontFamily'  => '',
			'connectorColor'      => '#eeeeee',
			'dateFontSize'        => 16,
			'dateFontWeight'      => 400,
			'dateLineHeight'      => 1.75,
			'headingFontSize'     => 20,
			'headingFontWeight'   => 700,
			'headingLineHeight'   => 1.5,
			'authorFontSize'      => 14,
			'authorFontWeight'    => 400,
			'authorLineHeight'    => 1.5,
			'contentFontSize'     => 16,
			'contentFontWeight'   => 400,
			'contentLineHeight'   => 1.75,
			'continueFontSize'    => 16,
			'continueFontWeight'  => 700,
			'continueLineHeight'  => 1.75,
			'icon'                => 'calendar-alt',
			'iconSize'            => 16,
			'bgSize'              => 35,
			'borderWidth'         => 0,
			'connectorWidth'      => 3,
			'iconColor'           => '#333',
			'separatorBg'         => '#eee',
			'separatorBorder'     => '#eee',
			'separatorFillColor'  => '#61ce70',
			'iconFocus'           => '#fff',
			'iconBgFocus'         => '#61ce70',
			'borderFocus'         => '#5cb85c',
			'continuebgColor'     => '',
			'borderColor'         => '',
			'hColor'              => '#333',
			'continuebghColor'    => '',
			'borderHColor'        => '',
			'target'              => true,
			'borderRadius'        => 0,
			'verSpace'            => 0,
			'horSpace'            => 0,
			'stack'               => 'mobile',
			'boxShadowColor'      => '',
			'boxShadowPosition'   => 'outset',
			'boxShadowHOffset'    => 0,
			'boxShadowVOffset'    => 0,
			'boxShadowBlur'       => 0,
			'boxShadowSpread'     => 0,
			'taxonomyType'        => 'category',
			'block_id'            => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_post_timeline_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for pricing list default attributes
	 */
	public function test_get_responsive_block_pricing_list_default_attributes() {
		$expected_values = array(
			'block_id'              => '',
			'pricingList'           => '',
			'topPadding'            => 5,
			'bottomPadding'         => 5,
			'leftPadding'           => 5,
			'rightPadding'          => 5,
			'rowGap'                => 10,
			'columnGap'             => 10,
			'titleSpace'            => 10,
			'titleFontFamily'       => '',
			'descriptionFontFamily' => '',
			'priceFontFamily'       => '',
			'titleFontSize'         => '',
			'titleFontWeight'       => '',
			'titleLineHeight'       => '',
			'descriptionFontSize'   => '',
			'descriptionFontWeight' => '',
			'descriptionLineHeight' => '',
			'priceFontSize'         => '',
			'priceFontWeight'       => '',
			'priceLineHeight'       => '',
			'seperatorStyle'        => 'dashed',
			'seperatorWidth'        => 100,
			'seperatorThickness'    => 1,
			'seperatorColor'        => '',
			'titleColor'            => '',
			'descColor'             => '',
			'priceColor'            => '',
			'columns'               => 2,
			'count'                 => '',
			'contentAlign'          => 'left',
			'imagePosition'         => 'top',
			'imageAlignment'        => 'middle',
			'imageSize'             => 'medium',
			'imageWidth'            => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_pricing_list_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for pricing table default attributes
	 */
	public function test_get_responsive_block_pricing_table_default_attributes() {
		$expected_values = array(
			'block_id'                 => '',
			'pricingTable'             => '',
			'blockId'                  => '',
			'count'                    => 2,
			'gutter'                   => 'medium',
			'contentAlign'             => 'center',
			'textColor'                => '',
			'titleColor'               => '',
			'prefixColor'              => '',
			'priceColor'               => '',
			'suffixColor'              => '',
			'subpriceColor'            => '',
			'featuresColor'            => '',
			'itemBackgroundColor'      => '',
			'blockBorderStyle'         => 'none',
			'blockBorderWidth'         => 1,
			'blockBorderRadius'        => 0,
			'blockBorderColor'         => '',
			'sectionTag'               => 'section',
			'opacity'                  => 30,
			'blockBackColorOpacity'    => 100,
			'columnBackColorOpacity'   => 100,
			'colorLocation1'           => 0,
			'colorLocation2'           => 100,
			'gradientDirection'        => 90,
			'backgroundImage'          => '',
			'backgroundColor'          => '',
			'backgroundColor1'         => '',
			'backgroundColor2'         => '#fff',
			'backgroundType'           => 'none',
			'blockopacity'             => '30',
			'blockcolorLocation1'      => 0,
			'blockcolorLocation2'      => 100,
			'blockgradientDirection'   => 90,
			'blockbackgroundImage'     => '',
			'blockbackgroundColor'     => '',
			'blockbackgroundColor1'    => '',
			'blockbackgroundColor2'    => '#fff',
			'blockbackgroundType'      => 'none',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => 0,
			'boxShadowSpread'          => 0,
			'boxShadowPosition'        => 'outset',
			'buttonBoxShadowColor'     => '',
			'buttonBoxShadowHOffset'   => 0,
			'buttonBoxShadowVOffset'   => 0,
			'buttonBoxShadowBlur'      => 0,
			'buttonBoxShadowSpread'    => 0,
			'buttonBoxShadowPosition'  => 'outset',
			'ctaColor'                 => '#ffffff',
			'ctaBackColor'             => '#3f46ae',
			'ctaHoverColor'            => '#ffffff',
			'ctaHoverBackColor'        => '#3f46ae',
			'ctaBorderColor'           => '#333',
			'ctaBorderStyle'           => 'none',
			'ctaBorderRadius'          => 0,
			'ctaBorderWidth'           => 2,
			'ctaHpadding'              => 30,
			'ctaVpadding'              => 15,
			'buttonbackgroundType'     => 'color',
			'buttoncolorLocation1'     => 0,
			'buttoncolorLocation2'     => 100,
			'buttongradientDirection'  => 90,
			'buttonbackgroundColor1'   => '',
			'buttonbackgroundColor2'   => '#fff',
			'buttonHbackgroundType'    => 'color',
			'buttonHcolorLocation1'    => 0,
			'buttonHcolorLocation2'    => 100,
			'buttonHgradientDirection' => 90,
			'buttonHbackgroundColor1'  => '',
			'buttonHbackgroundColor2'  => '#fff',
			'titleFontFamily'          => '',
			'amountFontFamily'         => '',
			'prefixFontFamily'         => '',
			'suffixFontFamily'         => '',
			'subpriceFontFamily'       => '',
			'featuresFontFamily'       => '',
			'ctaFontFamily'            => '',
			'titleFontSize'            => '',
			'titleFontWeight'          => '',
			'titleLineHeight'          => '',
			'amountFontSize'           => '',
			'amountFontWeight'         => '',
			'amountLineHeight'         => '',
			'subpriceFontSize'         => '',
			'subpriceFontWeight'       => '',
			'subpriceLineHeight'       => '',
			'subpriceTextTransform'    => 'uppercase',
			'prefixFontSize'           => '',
			'prefixFontWeight'         => '',
			'prefixLineHeight'         => '',
			'suffixFontSize'           => '',
			'suffixFontWeight'         => '',
			'suffixLineHeight'         => '',
			'featuresFontSize'         => '',
			'featuresFontWeight'       => '',
			'featuresLineHeight'       => '',
			'ctaFontSize'              => '',
			'ctaFontWeight'            => '',
			'ctaLineHeight'            => '',
			'blockTopPadding'          => 0,
			'blockBottomPadding'       => 0,
			'blockLeftPadding'         => 0,
			'blockRightPadding'        => 0,
			'columnTopPadding'         => 64,
			'columnBottomPadding'      => 64,
			'columnLeftPadding'        => 24,
			'columnRightPadding'       => 24,
			'showImage'                => true,
			'showTitle'                => true,
			'showPrefix'               => true,
			'showPrice'                => true,
			'showSuffix'               => true,
			'showSubprice'             => true,
			'showFeatures'             => true,
			'showButton'               => true,
			'buttonTarget'             => false,
			'titleSpace'               => '',
			'priceSpace'               => '',
			'subpriceSpace'            => 0,
			'buttonSpace'              => '',
			'featuresSpace'            => '',
			'blockAlign'               => 'center',
			'imageWidth'               => '',
			'imageSize'                => 'full',
			'imageShape'               => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_pricing_table_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for section default attributes
	 */
	public function test_get_responsive_block_section_default_attributes() {
		$expected_values = array(
			'block_id'                 => '',
			'blockId'                  => '',
			'align'                    => '',
			'width'                    => 900,
			'innerWidth'               => 1140,
			'innerWidthTablet'         => 1140,
			'innerWidthMobile'         => 1140,
			'innerWidthType'           => 'px',
			'themeWidth'               => false,
			'topPadding'               => 10,
			'topPaddingMobile'         => 10,
			'topPaddingTablet'         => 10,
			'bottomPadding'            => 10,
			'bottomPaddingMobile'      => 10,
			'bottomPaddingTablet'      => 10,
			'leftPadding'              => 10,
			'leftPaddingMobile'        => 10,
			'leftPaddingTablet'        => 10,
			'rightPadding'             => 10,
			'rightPaddingMobile'       => 10,
			'rightPaddingTablet'       => 10,
			'topMargin'                => 0,
			'bottomMargin'             => 0,
			'leftMargin'               => 0,
			'rightMargin'              => 0,
			'topMarginTablet'          => 0,
			'bottomMarginTablet'       => 0,
			'leftMarginTablet'         => 0,
			'rightMarginTablet'        => 0,
			'topMarginMobile'          => 0,
			'bottomMarginMobile'       => 0,
			'leftMarginMobile'         => 0,
			'rightMarginMobile'        => 0,
			'blockBorderStyle'         => 'none',
			'blockBorderWidth'         => 1,
			'blockBorderRadius'        => 0,
			'blockBorderColor'         => '#000',
			'sectionTag'               => 'section',
			'opacity'                  => 20,
			'colorLocation1'           => 0,
			'colorLocation2'           => 100,
			'gradientDirection'        => 90,
			'backgroundImage'          => '',
			'backgroundPosition'       => 'center-center',
			'backgroundPositionTablet' => 'center center',
			'backgroundPositionMobile' => 'center center',
			'backgroundSize'           => 'cover',
			'backgroundSizeTablet'     => 'cover',
			'backgroundSizeMobile'     => 'cover',
			'backgroundRepeat'         => 'no-repeat',
			'backgroundAttachment'     => 'scroll',
			'backgroundImageColor'     => '#fff',
			'overlayType'              => 'color',
			'gradientOverlayColor1'    => '#fff',
			'gradientOverlayColor2'    => '#fff',
			'gradientOverlayType'      => 'linear',
			'gradientOverlayLocation1' => 0,
			'gradientOverlayLocation2' => 100,
			'gradientOverlayAngle'     => 0,
			'gradientOverlayPosition'  => 'center center',
			'backgroundVideo'          => '',
			'backgroundColor'          => '#fff',
			'backgroundColor1'         => '#fff',
			'backgroundColor2'         => '#fff',
			'backgroundType'           => 'none',
			'boxShadowColor'           => '#fff',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => 0,
			'boxShadowSpread'          => 0,
			'boxShadowPosition'        => 'outset',
			'z_index'                  => 1,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_section_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for shape divider default attributes
	 */
	public function test_get_responsive_block_shape_divider_default_attributes() {
		$expected_values = array(
			'block_id'               => '',
			'align'                  => 'full',
			'height'                 => 100,
			'heightTablet'           => '',
			'heightMobile'           => '',
			'shapeHeight'            => 100,
			'shapeHeightTablet'      => 0,
			'shapeHeightMobile'      => 0,
			'backgroundHeight'       => 50,
			'backgroundHeightTablet' => '',
			'backgroundHeightMobile' => '',
			'syncHeight'             => true,
			'syncHeightAlt'          => true,
			'verticalFlip'           => false,
			'horizontalFlip'         => false,
			'color'                  => '',
			'customColor'            => '',
			'backgroundColor'        => '#fff',
			'customBackgroundColor'  => '#fff',
			'noBottomMargin'         => true,
			'noTopMargin'            => true,
			'justAdded'              => true,
			'colorLocation1'         => 0,
			'colorLocation2'         => 100,
			'gradientDirection'      => 90,
			'backgroundColor1'       => '#fff',
			'backgroundColor2'       => '#fff',
			'backgroundType'         => 'none',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_shape_divider_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for spacer default attributes
	 */
	public function test_get_responsive_block_spacer_default_attributes() {
		$expected_values = array(
			'height'       => 100,
			'heightTablet' => 100,
			'heightMobile' => 100,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_spacer_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for team block default attributes
	 */
	public function test_get_responsive_block_team_default_attributes() {
		$expected_values = array(
			'block_id'                 => '',
			'teamBlock'                => 'teamBlock',
			'teamImgURL'               => '',
			'counterId'                => '1',
			'count'                    => 2,
			'gutter'                   => 'medium',
			'designationColor'         => '',
			'descriptionColor'         => '',
			'socialIconColor'          => '#0066CC',
			'titleColor'               => '',
			'titleFontWeight'          => '',
			'designationFontWeight'    => '',
			'descriptionFontWeight'    => '',
			'titleLineHeight'          => '',
			'designationLineHeight'    => '',
			'descriptionLineHeight'    => '',
			'imageSize'                => 'full',
			'titleFontFamily'          => '',
			'designationFontFamily'    => '',
			'descriptionFontFamily'    => '',
			'titleFontSize'            => 23,
			'designationFontSize'      => 15,
			'descriptionFontSize'      => 15,
			'socialIconFontSize'       => 23,
			'imageMarginTop'           => '',
			'imageMarginBottom'        => '',
			'iconSize'                 => '',
			'titleSpacing'             => '',
			'designationSpacing'       => '',
			'descriptionSpacing'       => '',
			'socialIconSpacing'        => '',
			'imageStyle'               => '0%',
			'imageWidth'               => 120,
			'imageWidthMobile'         => 120,
			'imageWidthTablet'         => 120,
			'backgroundColor'          => '',
			'borderColor'              => '',
			'borderWidth'              => 2,
			'borderRadius'             => 2,
			'padding'                  => 2,
			'alignment'                => 'center',
			'imageShape'               => '',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => 0,
			'boxShadowSpread'          => 0,
			'boxShadowPosition'        => 'outset',
			'opacity'                  => 50,
			'secondaryBackgroundColor' => '',
			'gradientDegree'           => 100,
			'colorLocation1'           => 0,
			'colorLocation2'           => 100,
			'bgGradient'               => '',
			'backgroundImage'          => '',
			'backgroundPosition'       => 'center center',
			'backgroundRepeat'         => 'no-repeat',
			'backgroundSize'           => 'cover',
			'backgroundAttachment'     => 'scroll',
			'showImage'                => true,
			'showName'                 => true,
			'showDesignation'          => true,
			'showDescription'          => true,
			'showSocialIcons'          => true,
			'facebook'                 => '',
			'twitter'                  => '',
			'linkedin'                 => '',
			'instagram'                => '',
			'email'                    => '',
			'youtube'                  => '',
			'pinterest'                => '',
			'stack'                    => 'mobile',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_team_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for testimonial block default attributes
	 */
	public function test_get_responsive_block_testimonial_default_attributes() {
		$expected_values = array(
			'block_id'                   => '',
			'testimonialBlock'           => '',
			'counterId'                  => '',
			'count'                      => '',
			'gutter'                     => 'medium',
			'testimonialAlignment'       => '',
			'testimonialBackgroundColor' => '#f2f2f2',
			'testimonialTextColor'       => '',
			'testimonialNameColor'       => '',
			'testimonialTitleColor'      => '',
			'titleFontSize'              => '',
			'titleLineHeight'            => '',
			'titleFontWeight'            => '',
			'titleTextTransform'         => '',
			'nameFontSize'               => '',
			'nameLineHeight'             => '',
			'imageWidth'                 => '',
			'nameFontFamily'             => '',
			'titleFontFamily'            => '',
			'contentFontFamily'          => '',
			'nameFontWeight'             => '',
			'nameTextTransform'          => '',
			'contentFontSize'            => '',
			'contentLineHeight'          => 1.6,
			'contentFontWeight'          => '',
			'contentTextTransform'       => '',
			'testimonialCiteAlign'       => 'left-aligned',
			'backgroundColor'            => '#f2f2f2',
			'borderStyle'                => 'none',
			'borderWidth'                => 1,
			'borderColor'                => '',
			'borderRadius'               => 2,
			'padding'                    => 20,
			'paddingTablet'              => 20,
			'paddingMobile'              => 20,
			'contentSpacing'             => 8,
			'titleSpacing'               => '',
			'nameSpacing'                => -5,
			'imageSpacing'               => '',
			'alignment'                  => 'center',
			'imageShape'                 => '',
			'imageSize'                  => 'full',
			'boxShadowColor'             => '#fff',
			'boxShadowHOffset'           => 0,
			'boxShadowVOffset'           => 0,
			'boxShadowBlur'              => 0,
			'boxShadowSpread'            => 0,
			'boxShadowPosition'          => 'outset',
			'hoverboxShadowColor'        => '#ccc',
			'hoverboxShadowHOffset'      => 0,
			'hoverboxShadowVOffset'      => 0,
			'hoverboxShadowBlur'         => 6,
			'hoverboxShadowSpread'       => 1,
			'hoverboxShadowPosition'     => 'outset',
			'opacity'                    => 0.7,
			'gradientDegree'             => 180,
			'bgGradient'                 => false,
			'backgroundImage'            => '',
			'backgroundPosition'         => '',
			'backgroundSize'             => '',
			'backgroundRepeat'           => '',
			'imageHoverEffect'           => '',
			'bggradient'                 => '',
			'secondaryBackgroundColor'   => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_testimonial_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

		/**
		 * Test for testimonial slider
		 */
	public function test_get_responsive_block_testimonial_slider_block_default_attributes() {
		$expected_values = array(
			'test_item_count'         => 3,
			'classMigrate'            => false,
			'test_block'              => array(),
			'skin'                    => 'default',
			'bubblePadding'           => 20,
			'bubbleBorderRadius'      => 0,
			'bubbleColor'             => 'center',
			'headingAlign'            => 'center',
			'headingAlignMobile'      => 'center',
			'headingAlignTablet'      => 'center',
			'descColor'               => '#333',
			'companyColor'            => '#888888',
			'authorColor'             => '#333',
			'iconimgStyle'            => 'circle',
			'imagePosition'           => 'bottom',
			'imageAlignment'          => 'top',
			'nameFontSizeType'        => 'px',
			'nameFontSize'            => '',
			'nameFontSizeTablet'      => '',
			'nameFontSizeMobile'      => '',
			'nameFontFamily'          => 'Default',
			'nameFontWeight'          => '',
			'nameFontSubset'          => '',
			'nameLineHeightType'      => 'em',
			'nameLineHeight'          => '',
			'nameLineHeightTablet'    => '',
			'nameLineHeightMobile'    => '',
			'nameLoadGoogleFonts'     => false,
			'companyFontSizeType'     => 'px',
			'companyFontSize'         => '',
			'companyFontSizeTablet'   => '',
			'companyFontSizeMobile'   => '',
			'companyFontFamily'       => 'Default',
			'companyFontWeight'       => '',
			'companyFontSubset'       => '',
			'companyLineHeightType'   => 'em',
			'companyLineHeight'       => '',
			'companyLineHeightTablet' => '',
			'companyLineHeightMobile' => '',
			'companyLoadGoogleFonts'  => false,
			'descFontSizeType'        => 'px',
			'descFontSize'            => '',
			'descFontSizeTablet'      => '',
			'descFontSizeMobile'      => '',
			'descFontFamily'          => 'Default',
			'descFontWeight'          => '',
			'descFontSubset'          => '',
			'descLineHeightType'      => 'em',
			'descLineHeight'          => '',
			'descLineHeightTablet'    => '',
			'descLineHeightMobile'    => '',
			'descLoadGoogleFonts'     => false,
			'nameSpace'               => 5,
			'descSpace'               => 15,
			'block_id'                => 'not_set',
			'authorSpace'             => 5,
			'imgVrPadding'            => 10,
			'imgHrPadding'            => 10,
			'imgTopPadding'           => 10,
			'imgBottomPadding'        => 10,
			'iconImage'               => array(
				'url' => '',
				'alt' => 'InfoBox placeholder img',
			),
			'imageSize'               => 'thumbnail',
			'imageWidth'              => 60,
			'columns'                 => 1,
			'tcolumns'                => 1,
			'mcolumns'                => 1,
			'pauseOnHover'            => true,
			'infiniteLoop'            => true,
			'transitionSpeed'         => 500,
			'autoplay'                => true,
			'autoplaySpeed'           => 2000,
			'arrowDots'               => 'arrows_dots',
			'arrowSize'               => 20,
			'arrowBorderSize'         => 1,
			'arrowBorderRadius'       => 0,
			'rowGap'                  => 10,
			'columnGap'               => 10,
			'contentPadding'          => 5,
			'backgroundType'          => '',
			'backgroundImage'         => '',
			'backgroundPosition'      => 'center-center',
			'backgroundSize'          => 'cover',
			'backgroundRepeat'        => 'no-repeat',
			'backgroundColor'         => '',
			'backgroundImageColor'    => '',
			'borderStyle'             => 'none',
			'borderWidth'             => '1',
			'borderRadius'            => '',
			'borderColor'             => '',
			'backgroundOpacity'       => 50,
			'arrowColor'              => '#333',
			'stack'                   => 'tablet',
			'blockPadding'            => 45,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_testimonial_slider_block_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values['iconImage'], $values['iconImage'] ) );
		unset( $expected_values['iconImage'] );
		unset( $values['iconImage'] );
		$this->assertEmpty( array_diff_assoc( $expected_values['test_block'], $values['test_block'] ) );
		unset( $expected_values['test_block'] );
		unset( $values['test_block'] );
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

		/**
		 * Test for video popup default attributes
		 */
	public function test_get_responsive_block_video_popup_default_attributes() {
		$expected_values = array(
			'block_id'               => '',
			'align'                  => '',
			'videoLink'              => '',
			'videoID'                => '',
			'borderRadius'           => '',
			'shadow'                 => '',
			'playButtonType'         => 'normal',
			'playButtonColor'        => '',
			'playButtonSize'         => 30,
			'vidwidth'               => '',
			'vidwidthTablet'         => '',
			'vidwidthMobile'         => '',
			'vidheight'              => '',
			'vidheightTablet'        => '',
			'vidheightMobile'        => '',
			'vidBackgroundColor'     => '',
			'opacity'                => 50,
			'imgURL'                 => '',
			'imgID'                  => '',
			'imgAlt'                 => '',
			'counterId'              => 1,
			'butopacity'             => 100,
			'blockBorderStyle'       => 'none',
			'blockBorderWidth'       => 1,
			'blockBorderRadius'      => '',
			'blockBorderColor'       => '',
			'boxShadowColor'         => '',
			'boxShadowHOffset'       => 0,
			'boxShadowVOffset'       => 0,
			'boxShadowBlur'          => '',
			'boxShadowSpread'        => '',
			'boxShadowPosition'      => 'outset',
			'previewBackgroundColor' => '#000000',
			'hoverEffect'            => '',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_video_popup_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

		/**
		 * Test for advanced columns default attributes
		 */
	public function test_get_responsive_block_advanced_columns_default_attributes() {
		$expected_values = array(
			'columnGap'                => 'default',
			'widthType'                => 'px',
			'contentWidth'             => 'theme',
			'stack'                    => 'mobile',
			'columns'                  => 2,
			'width'                    => 900,
			'topPadding'               => 10,
			'bottomPadding'            => 10,
			'leftPadding'              => 10,
			'rightPadding'             => 10,
			'topPaddingTablet'         => '',
			'bottomPaddingTablet'      => '',
			'leftPaddingTablet'        => '',
			'rightPaddingTablet'       => '',
			'topPaddingMobile'         => '',
			'bottomPaddingMobile'      => '',
			'leftPaddingMobile'        => '',
			'rightPaddingMobile'       => '',
			'topMargin'                => 0,
			'bottomMargin'             => 0,
			'topMarginTablet'          => '',
			'bottomMarginTablet'       => '',
			'topMarginMobile'          => '',
			'bottomMarginMobile'       => '',
			'blockBorderStyle'         => 'none',
			'blockBorderWidth'         => 1,
			'blockBorderRadius'        => '',
			'blockBorderColor'         => '',
			'boxShadowColor'           => '',
			'boxShadowHOffset'         => 0,
			'boxShadowVOffset'         => 0,
			'boxShadowBlur'            => 0,
			'boxShadowSpread'          => 0,
			'boxShadowPosition'        => 'outset',
			'opacity'                  => 20,
			'colorLocation1'           => 0,
			'colorLocation2'           => 100,
			'gradientDirection'        => 90,
			'backgroundType'           => '',
			'backgroundColor'          => '',
			'backgroundColor1'         => '',
			'backgroundColor2'         => '#fff',
			'backgroundImage'          => '',
			'backgroundPosition'       => 'center-center',
			'backgroundSize'           => 'cover',
			'backgroundRepeat'         => 'no-repeat',
			'backgroundAttachment'     => 'scroll',
			'backgroundImageColor'     => '',
			'overlayType'              => 'color',
			'gradientOverlayColor1'    => '',
			'gradientOverlayColor2'    => '',
			'gradientOverlayType'      => 'linear',
			'gradientOverlayLocation1' => 0,
			'gradientOverlayLocation2' => 100,
			'gradientOverlayAngle'     => 0,
			'gradientOverlayPosition'  => 'center center',
			'blockAlign'               => 'left',
			'verticalAlign'            => 'flex-start',
			'blockId'                  => '',
			'height'                   => 'normal',
			'customHeight'             => 50,
			'z_index'                  => 1,

		);
		$values = self::$rbea_frontend_styles->get_responsive_block_advanced_columns_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for count up default attributes
	 */
	public function test_get_responsive_block_count_up_default_attributes() {
		$expected_values = array(
			'block_id'              => '',
			'countUp'               => '',
			'count'                 => '',
			'gutter'                => 'medium',
			'contentAlign'          => 'center',
			'textColor'             => '',
			'itemBackgroundColor'   => '',
			'contentFontFamily'     => '',
			'headingFontFamily'     => '',
			'dateFontFamily'        => '',
			'dateLineHeight'        => 1,
			'dateFontWeight'        => '400',
			'dateFontSize'          => 40,
			'dateFontSizeMobile'    => 40,
			'dateFontSizeTablet'    => 40,
			'headingLineHeight'     => 1.8,
			'titleFontWeight'       => '900',
			'headingFontSize'       => 16,
			'headingFontSizeTablet' => '',
			'headingFontSizeMobile' => '',
			'blockBorderRadius'     => '',
			'blockBorderColor'      => '',
			'numColor'              => '',
			'titleColor'            => '',
			'titleSpacing'          => '',
			'numberSpacing'         => '',
			'descriptionSpacing'    => '',
			'contentLineHeight'     => 1.75,
			'contentFontWeight'     => '400',
			'contentFontSize'       => 16,
			'contentFontSizeMobile' => 16,
			'contentFontSizeTablet' => 16,
			'icon'                  => 'welcome-add-page',
			'resshowIcon'           => false,
			'resshowTitle'          => true,
			'resshowDesc'           => true,
			'blockBorderStyle'      => 'none',
			'blockBorderWidth'      => 1,
			'opacity'               => 10,
			'icon_color'            => '#3a3a3a',
			'iconsize'              => 16,
			'resshowNum'            => true,
			'titleSpace'            => 20,
			'contentSpace'          => 30,
			'numSpace'              => 20,
			'iconStyle'             => 'none',
			'shapeBorderRadius'     => 100,
			'shapePadding'          => 20,
			'shapeBorder'           => 2,
			'iconShapeColor'        => '#add5ef',
			'contentSpacing'        => 0,
			'iconSpacing'           => 16,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_count_up_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for blockquote default attributes
	 */
	public function test_get_responsive_block_blockquote_default_attributes() {
		$expected_values = array(
			'block_id'                => '',
			'quoteContent'            => '',
			'quoteBackgroundColor'    => '',
			'quoteTextColor'          => '',
			'quoteFontFamily'         => '',
			'quoteFontSize'           => 18,
			'quoteFontWeight'         => '400',
			'quoteLineHeight'         => 1,
			'quoteSize'               => 70,
			'quoteColor'              => '',
			'borderStyle'             => 'none',
			'borderWidth'             => 1,
			'blockBorderRadius'       => 0,
			'borderColor'             => '',
			'leftPadding'             => 60,
			'rightPadding'            => 60,
			'topPadding'              => 70,
			'bottomPadding'           => 70,
			'leftPaddingMobile'       => 60,
			'rightPaddingMobile'      => 60,
			'topPaddingMobile'        => 70,
			'bottomPaddingMobile'     => 70,
			'leftPaddingTablet'       => 60,
			'rightPaddingTablet'      => 60,
			'topPaddingTablet'        => 70,
			'bottomPaddingTablet'     => 70,
			'quoteHposition'          => 30,
			'quoteVposition'          => 20,
			'quoteAlign'              => 'left-aligned',
			'quoteOpacity'            => 100,
			'showQuote'               => true,
			'opacity'                 => 100,
			'colorLocation1'          => 0,
			'colorLocation2'          => 100,
			'gradientDirection'       => 90,
			'backgroundImage'         => '',
			'backgroundVideo'         => '',
			'backgroundColor'         => '',
			'backgroundColor1'        => '',
			'backgroundColor2'        => '',
			'backgroundType'          => 'none',
			'icon'                    => 'round-fat',
			'boxShadowColor'          => '#fff',
			'boxShadowHOffset'        => 0,
			'boxShadowVOffset'        => 0,
			'boxShadowBlur'           => 20,
			'boxShadowSpread'         => 20,
			'boxShadowPosition'       => 'outset',
			'textSpacingTop'          => 60,
			'textSpacingTopMobile'    => 30,
			'textSpacingTopTablet'    => 30,
			'textSpacingBottom'       => 0,
			'textSpacingBottomMobile' => 0,
			'textSpacingBottomTablet' => 0,
			'textSpacingLeft'         => 70,
			'textSpacingLeftMobile'   => 35,
			'textSpacingLeftTablet'   => 35,
			'textSpacingRight'        => 70,
			'textSpacingRightMobile'  => 35,
			'textSpacingRightTablet'  => 35,

		);
		$values = self::$rbea_frontend_styles->get_responsive_block_blockquote_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for divider default attributes
	 */
	public function test_get_responsive_block_divider_default_attributes() {
		$expected_values = array(
			'block_id'               => '',
			'spacerHeight'           => 30,
			'spacerDivider'          => false,
			'spacerDividerStyle'     => 'solid',
			'spacerDividerColor'     => '#000',
			'spacerDividerHeight'    => 7,
			'spacerDividerWidth'     => 60,
			'spacerDividerAlignment' => 'center',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_divider_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for count down default attributes
	 */
	public function test_get_responsive_block_count_down_default_attributes() {
		$expected_values = array(
			'block_id'                     => '',
			'date'                         => '',
			'days'                         => '0',
			'hours'                        => '0',
			'minutes'                      => '0',
			'seconds'                      => '0',
			'digitDaysLabel'               => 'Days',
			'digitHoursLabel'              => 'Hours',
			'digitMinutesLabel'            => 'Minutes',
			'digitSecondsLabel'            => 'Seconds',
			'showDigitLabels'              => true,
			'showDaysBox'                  => true,
			'showHoursBox'                 => true,
			'showMinutesBox'               => true,
			'showSecondsBox'               => true,
			'digitFontFamily'              => '',
			'digitFontSize'                => 48,
			'digitFontSizeMobile'          => 14,
			'digitFontSizeTablet'          => 28,
			'digitFontWeight'              => '500',
			'digitLetterSpacing'           => 1,
			'digitLineHeight'              => 2,
			'digitColor'                   => '#fff',
			'labelFontFamily'              => '',
			'labelFontSize'                => 14,
			'labelFontSizeMobile'          => 12,
			'labelFontSizeTablet'          => 14,
			'labelColor'                   => '#fff',
			'labelLineHeight'              => 2,
			'labelFontWeight'              => '500',
			'labelLeftPadding'             => 0,
			'labelLetterSpacing'           => 1,
			'boxItemMarginTop'             => 0,
			'boxItemMarginRight'           => 0,
			'boxItemMarginBottom'          => 0,
			'boxItemMarginLeft'            => 0,
			'boxItemMarginTopTablet'       => 0,
			'boxItemMarginRightTablet'     => 0,
			'boxItemMarginBottomTablet'    => 0,
			'boxItemMarginLeftTablet'      => 0,
			'boxItemMarginTopMobile'       => 0,
			'boxItemMarginRightMobile'     => 0,
			'boxItemMarginBottomMobile'    => 0,
			'boxItemMarginLeftMobile'      => 0,
			'boxItemTextAlign'             => 'center',
			'boxHeight'                    => '',
			'boxWidth'                     => 140,
			'boxMargin'                    => 10,
			'boxHeightMobile'              => '',
			'boxWidthMobile'               => 80,
			'boxMarginMobile'              => 8,
			'boxHeightTablet'              => '',
			'boxWidthTablet'               => 140,
			'boxMarginTablet'              => 10,
			'boxPaddingTop'                => 0,
			'boxPaddingRight'              => 0,
			'boxPaddingBottom'             => 10,
			'boxPaddingLeft'               => 0,
			'boxPaddingTopMobile'          => 0,
			'boxPaddingRightMobile'        => 0,
			'boxPaddingBottomMobile'       => 10,
			'boxPaddingLeftMobile'         => 0,
			'boxPaddingTopTablet'          => 0,
			'boxPaddingRightTablet'        => 0,
			'boxPaddingBottomTablet'       => 10,
			'boxPaddingLeftTablet'         => 0,
			'showBoxBorder'                => true,
			'boxBorderColor'               => '000',
			'boxBorderSize'                => 0,
			'boxBorderStyle'               => 'solid',
			'borderRadiusTopLeft'          => 0,
			'borderRadiusTopRight'         => 0,
			'borderRadiusBottomRight'      => 0,
			'borderRadiusBottomLeft'       => 0,
			'showBoxShadow'                => true,
			'boxShadowHOffset'             => 0,
			'boxShadowVOffset'             => 0,
			'boxShadowBlur'                => 0,
			'boxShadowPosition'            => 'outset',
			'boxShadowSpread'              => 0,
			'boxShadowColor'               => '#000',
			'boxBackgroundColor'           => '#6EC1E4',
			'containerMarginTop'           => 0,
			'containerMarginRight'         => 0,
			'containerMarginBottom'        => 0,
			'containerMarginLeft'          => 0,
			'containerPaddingTop'          => 0,
			'containerPaddingRight'        => 0,
			'containerPaddingBottom'       => 0,
			'containerPaddingLeft'         => 0,
			'containerMarginTopTablet'     => 0,
			'containerMarginRightTablet'   => 0,
			'containerMarginBottomTablet'  => 0,
			'containerMarginLeftTablet'    => 0,
			'containerPaddingTopTablet'    => 0,
			'containerPaddingRightTablet'  => 0,
			'containerPaddingBottomTablet' => 0,
			'containerPaddingLeftTablet'   => 0,
			'containerMarginTopMobile'     => 0,
			'containerMarginRightMobile'   => 0,
			'containerMarginBottomMobile'  => 0,
			'containerMarginLeftMobile'    => 0,
			'containerPaddingTopMobile'    => 0,
			'containerPaddingRightMobile'  => 0,
			'containerPaddingBottomMobile' => 0,
			'containerPaddingLeftMobile'   => 0,
			'justifyItems'                 => 'center',
			'displayInline'                => false,
			'stackOnMobile'                => false,
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_count_down_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}

	/**
	 * Test for table of contents default attributes
	 */
	public function test_get_responsive_block_table_of_contents_default_attributes() {
		$expected_values = array(
			'block_id'                   => '',
			'classMigrate'               => false,
			'isCollapsible'              => false,
			'icon'                       => 'fa-angle-down',
			'heading'                    => 'Table Of Contents',
			'headingTitle'               => 'Table Of Contents',
			'borderStyle'                => 'solid',
			'borderWidth'                => 1,
			'borderRadius'               => 0,
			'borderColor'                => '#333',
			'blockTopPadding'            => 0,
			'blockTopPaddingMobile'      => 0,
			'blockTopPaddingTablet'      => 0,
			'blockBottomPadding'         => 0,
			'blockBottomPaddingTablet'   => 0,
			'blockBottomPaddingMobile'   => 0,
			'blockRightPadding'          => 0,
			'blockRightPaddingMobile'    => 0,
			'blockRightPaddingTablet'    => 0,
			'blockLeftPadding'           => 0,
			'blockLeftPaddingTablet'     => 0,
			'blockLeftPaddingMobile'     => 0,
			'blockTopMargin'             => 0,
			'blockTopMarginMobile'       => 0,
			'blockTopMarginTablet'       => 0,
			'blockBottomMargin'          => 0,
			'blockBottomMarginTablet'    => 0,
			'blockBottomMarginMobile'    => 0,
			'blockRightMargin'           => 0,
			'blockRightMarginMobile'     => 0,
			'blockRightMarginTablet'     => 0,
			'blockLeftMargin'            => 0,
			'blockLeftMarginTablet'      => 0,
			'blockLeftMarginMobile'      => 0,
			'zIndex'                     => 0,
			'headingFontFamily'          => 'Default',
			'headingFontWeight'          => '500',
			'headingFontSize'            => 16,
			'headingFontSizeTablet'      => 16,
			'headingFontSizeMobile'      => 14,
			'headingLineHeight'          => 1,
			'contentFontFamily'          => 'Default',
			'contentFontWeight'          => '500',
			'contentFontSize'            => 16,
			'contentFontSizeTablet'      => 16,
			'contentFontSizeMobile'      => 14,
			'contentLineHeight'          => 1.8,
			'align'                      => 'left',
			'headingColor'               => '#fff',
			'headingBgColor'             => '#0984ff',
			'headingColorHover'          => '',
			'headingBgColorHover'        => '',
			'bodyColor'                  => '',
			'bodyBgColor'                => '#fff',
			'bodyColorHover'             => '',
			'bodyBgColorHover'           => '',
			'headingTopPadding'          => 15,
			'headingTopPaddingMobile'    => 15,
			'headingTopPaddingTablet'    => 15,
			'headingBottomPadding'       => 15,
			'headingBottomPaddingTablet' => 15,
			'headingBottomPaddingMobile' => 15,
			'headingRightPadding'        => 20,
			'headingRightPaddingMobile'  => 20,
			'headingRightPaddingTablet'  => 20,
			'headingLeftPadding'         => 20,
			'headingLeftPaddingTablet'   => 20,
			'headingLeftPaddingMobile'   => 20,
			'headingTopMargin'           => 0,
			'headingTopMarginMobile'     => 0,
			'headingTopMarginTablet'     => 0,
			'headingBottomMargin'        => 0,
			'headingBottomMarginTablet'  => 0,
			'headingBottomMarginMobile'  => 0,
			'headingRightMargin'         => 0,
			'headingRightMarginMobile'   => 0,
			'headingRightMarginTablet'   => 0,
			'headingLeftMargin'          => 0,
			'headingLeftMarginTablet'    => 0,
			'headingLeftMarginMobile'    => 0,
			'contentTopPadding'          => 15,
			'contentTopPaddingMobile'    => 15,
			'contentTopPaddingTablet'    => 15,
			'contentBottomPadding'       => 15,
			'contentBottomPaddingTablet' => 15,
			'contentBottomPaddingMobile' => 15,
			'contentRightPadding'        => 20,
			'contentRightPaddingMobile'  => 20,
			'contentRightPaddingTablet'  => 20,
			'contentLeftPadding'         => 20,
			'contentLeftPaddingTablet'   => 20,
			'contentLeftPaddingMobile'   => 20,
			'contentTopMargin'           => 0,
			'contentTopMarginMobile'     => 0,
			'contentTopMarginTablet'     => 0,
			'contentBottomMargin'        => 0,
			'contentBottomMarginTablet'  => 0,
			'contentBottomMarginMobile'  => 0,
			'contentRightMargin'         => 0,
			'contentRightMarginMobile'   => 0,
			'contentRightMarginTablet'   => 0,
			'contentLeftMargin'          => 0,
			'contentLeftMarginTablet'    => 0,
			'contentLeftMarginMobile'    => 0,
			'blockWidth'                 => 100,
			'blockBorderStyle'           => 'solid',
			'blockBorderWidth'           => 1,
			'blockBorderRadius'          => '',
			'blockBorderColor'           => '#0984ff',
			'headingBorderStyle'         => '',
			'headingBorderWidth'         => 1,
			'headingBorderRadius'        => 0,
			'headingBorderColor'         => '',
			'bodyBorderStyle'            => '',
			'bodyBorderWidth'            => 1,
			'bodyBorderRadius'           => 0,
			'bodyBorderColor'            => '',
			'tableType'                  => 'unordered',
			'orderListType'              => 'none',
			'headerLayout'               => 'fill',
			'backgroundImage'            => '',
			'backgroundPosition'         => 'center-center',
			'backgroundSize'             => 'cover',
			'backgroundRepeat'           => 'no-repeat',
			'backgroundColor'            => '',
			'backgroundVideo'            => '',
			'backgroundType'             => 'none',
		);
		$values          = self::$rbea_frontend_styles->get_responsive_block_table_of_contents_default_attributes();
		$this->assertEmpty( array_diff_assoc( $expected_values, $values ) );
	}
}
