<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_restaurant_layout',
	'collection' => array(
		'slug'      => 'restaurant',
		'label'     => __( 'Restaurant', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"228b0d7c-7a48-4896-8d52-3f2b0b018816","topPadding":0,"bottomPadding":0,"bottomPaddingMobile":50,"bottomPaddingTablet":100,"leftPadding":0,"rightPadding":0,"opacity":100,"backgroundColor":"#fff0dc","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-228b0d7c-7a48-4896-8d52-3f2b0b018816 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"2c1e1544-ac13-4356-8207-ffe4ece8e254"} -->
    <div class="block-2c1e1544-ac13-4356-8207-ffe4ece8e254 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":25,"rightPadding":25,"bottomPaddingTablet":0,"bottomPaddingMobile":50,"block_id":"f360de48-20bc-469f-8ade-8e43d61bd984","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-f360de48-20bc-469f-8ade-8e43d61bd984"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0f97e685-99c4-48c6-baf2-482a4ec69818","showSubHeading":true,"showSeparator":false,"headSpacing":30,"subheadSpacing":30,"headSpacingTablet":30,"subheadSpacingTablet":30,"headSpacingMobile":30,"subheadSpacingMobile":30,"headingTitleFontSize":60,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"700","headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0f97e685-99c4-48c6-baf2-482a4ec69818"><h2 class="responsive-heading-title-text">Experience the great food</h2><p class="responsive-heading-desc-text">Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard&nbsp;</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"b36e0c47-5de2-40f2-bb83-b1433e8cce77","label":"View Our Menu","link":"#","target":false,"vPadding":20,"hPadding":30,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":0,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#ffffff","background":"#ffb200","hColor":"#ffffff","buttonFontSize":16,"buttonFontSizeTablet":16,"buttonFontSizeMobile":16,"buttonLineHeight":1,"hbackground":"#eaa300","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-b36e0c47-5de2-40f2-bb83-b1433e8cce77 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">View Our Menu</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"block_id":"f46d7795-cd89-485a-890c-da6fa86b94ed","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-f46d7795-cd89-485a-890c-da6fa86b94ed"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":487,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/hotel1.png" alt="" class="wp-image-487"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"0e01fe7b-86a9-496f-9790-86849b2a5ca3","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/hotelgb.jpg","backgroundPosition":"center center","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-0e01fe7b-86a9-496f-9790-86849b2a5ca3 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"b69126d7-f73a-4a9e-b00e-65b600bd0861"} -->
    <div class="block-b69126d7-f73a-4a9e-b00e-65b600bd0861 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"width":33.333,"bottomPadding":0,"leftPadding":0,"rightPadding":20,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":20,"bottomPaddingMobile":50,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"8220fa53-ef0a-49df-bb0e-bdf6771c9b45","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-8220fa53-ef0a-49df-bb0e-bdf6771c9b45"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"14bf77ea-c769-46bd-ab7e-80359b38ce2b","showSeparator":false,"headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":28,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-14bf77ea-c769-46bd-ab7e-80359b38ce2b"><h3 class="responsive-heading-title-text">Welcome to The Tasty Time</h3><p class="responsive-heading-desc-text">Lorem<strong>&nbsp;</strong>Ipsum&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":40,"bottomPadding":0,"leftPadding":0,"topPaddingTablet":20,"bottomPaddingTablet":0,"rightPaddingTablet":10,"topPaddingMobile":0,"bottomPaddingMobile":50,"rightPaddingMobile":0,"block_id":"a8dfa4e3-3f3a-4e67-b394-3f856e6f3788","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-a8dfa4e3-3f3a-4e67-b394-3f856e6f3788"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":490,"sizeSlug":"full","linkDestination":"none"} -->
    <figure class="wp-block-image size-full"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/food1.jpg" alt="" class="wp-image-490"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"leftPadding":0,"leftPaddingTablet":10,"leftPaddingMobile":0,"block_id":"8f97956b-9661-4464-a1e4-a45ee780fe7e","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-8f97956b-9661-4464-a1e4-a45ee780fe7e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":489,"sizeSlug":"full","linkDestination":"none"} -->
    <figure class="wp-block-image size-full"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/food-2.jpg" alt="" class="wp-image-489"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"83ac155a-f716-4f94-81d8-401a37f37baa","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/hotelgb3.jpg","backgroundPosition":"center center","backgroundAttachment":"fixed","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-83ac155a-f716-4f94-81d8-401a37f37baa background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"5db3cd6b-003b-41c3-b9bd-9477ce4009bd","showSeparator":false,"headSpacing":30,"subheadSpacing":30,"headSpacingTablet":30,"subheadSpacingTablet":30,"headSpacingMobile":30,"subheadSpacingMobile":30,"headingTitleFontSize":40,"headingTitleFontWeight":"300","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-5db3cd6b-003b-41c3-b9bd-9477ce4009bd"><h3 class="responsive-heading-title-text">Discover Our Menu</h3><p class="responsive-heading-desc-text">LoremIpsum&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons -->
    <div class="wp-block-responsive-block-editor-addons-buttons center tabletAligncenter mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"3b43d0a0-7328-456e-a768-069d38d8ae1e","label":"View Our Menu","link":"#","target":false,"vPadding":20,"hPadding":30,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":0,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#ffffff","background":"#ffb200","hColor":"#ffffff","buttonFontSize":16,"buttonFontSizeTablet":16,"buttonFontSizeMobile":16,"buttonLineHeight":1,"hbackground":"#eaa300","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-3b43d0a0-7328-456e-a768-069d38d8ae1e responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">View Our Menu</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"ff8beaba-d160-4842-acd1-c692c27a2f11","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":100,"backgroundColor":"#ffffff","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-ff8beaba-d160-4842-acd1-c692c27a2f11 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0d1b59a3-7887-475f-b2f4-8d19c15b27a7","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":50,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":30,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0d1b59a3-7887-475f-b2f4-8d19c15b27a7"><h3 class="responsive-heading-title-text">Sample Menu</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":50,"leftPadding":0,"rightPadding":0,"block_id":"80c0aa16-42bb-49a1-8f73-c89a9d90e09f"} -->
    <div class="block-80c0aa16-42bb-49a1-8f73-c89a9d90e09f responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"65607f02-1e78-40f9-bc99-a096cd4fb7cb","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-65607f02-1e78-40f9-bc99-a096cd4fb7cb"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"5b8ff473-bb57-4f77-9040-fed6126f4689","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":30,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":25,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-5b8ff473-bb57-4f77-9040-fed6126f4689"><h3 class="responsive-heading-title-text">Starter</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"88f6f78a-048b-4167-9568-562e1a90e22a","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-88f6f78a-048b-4167-9568-562e1a90e22a"><h3 class="responsive-heading-title-text">Chicken Quesadillas</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"988733dd-89b5-466d-bc0f-656aba2a7f61","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-988733dd-89b5-466d-bc0f-656aba2a7f61"><p class="responsive-heading-desc-text">$10.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"e3c69697-4711-4cb2-9d7a-63931db5c95b","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-e3c69697-4711-4cb2-9d7a-63931db5c95b"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"86a22b1a-f5bd-4f5e-a19e-ad189c0b6ae8","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":30,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":25,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-86a22b1a-f5bd-4f5e-a19e-ad189c0b6ae8"><h3 class="responsive-heading-title-text">Main</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"a4c05ab8-7b4e-474b-aa74-2fae459e4e14","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-a4c05ab8-7b4e-474b-aa74-2fae459e4e14"><h3 class="responsive-heading-title-text">Fish Pie</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"389793dd-e8fb-4880-9399-7e8b8b4e5c46","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-389793dd-e8fb-4880-9399-7e8b8b4e5c46"><p class="responsive-heading-desc-text">$20.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"eee01626-6273-476b-8b9f-aac914e46a10","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-eee01626-6273-476b-8b9f-aac914e46a10"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"5e34c693-c5d7-4619-9e8c-d62663fc3a93","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":30,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":25,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-5e34c693-c5d7-4619-9e8c-d62663fc3a93"><h3 class="responsive-heading-title-text">Desert</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"32c4a0e1-9e66-43aa-8e73-dcafcee90eb0","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-32c4a0e1-9e66-43aa-8e73-dcafcee90eb0"><h3 class="responsive-heading-title-text">Ambrosia</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"361bba69-08b7-4b74-b4aa-09b77b623b31","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-361bba69-08b7-4b74-b4aa-09b77b623b31"><p class="responsive-heading-desc-text">$10.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns -->
    
    <!-- wp:responsive-block-editor-addons/buttons -->
    <div class="wp-block-responsive-block-editor-addons-buttons center tabletAligncenter mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"2591d8f9-864f-44db-b86a-40cc22ed463e","label":"View Our Full Menu","link":"#","target":false,"vPadding":20,"hPadding":30,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":0,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#ffffff","background":"#ffb200","hColor":"#ffffff","buttonFontSize":16,"buttonFontSizeTablet":16,"buttonFontSizeMobile":16,"buttonLineHeight":1,"hbackground":"#eaa300","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-2591d8f9-864f-44db-b86a-40cc22ed463e responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">View Our Full Menu</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"5df0bd92-cef0-4c06-b845-168fdabd71c5","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":100,"backgroundColor":"#f4fffd","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-5df0bd92-cef0-4c06-b845-168fdabd71c5 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"60e267d1-6bed-490e-9692-10814d40f08e","showSeparator":false,"headSpacing":30,"subheadSpacing":50,"headSpacingTablet":30,"subheadSpacingTablet":50,"headSpacingMobile":30,"subheadSpacingMobile":50,"headingTitleFontSize":40,"headingTitleFontWeight":"300","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-60e267d1-6bed-490e-9692-10814d40f08e"><h3 class="responsive-heading-title-text">Book Your Table</h3><p class="responsive-heading-desc-text">To Book a Table, Call Us +123 4567 890 or Use the Form Below</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"b02fb825-c956-4450-9670-0aaf74645cc2"} -->
    <div class="block-b02fb825-c956-4450-9670-0aaf74645cc2 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"leftPadding":30,"rightPadding":30,"bottomMargin":0,"bottomMarginTablet":0,"bottomMarginMobile":50,"block_id":"ef03c7b8-755d-4467-b0ab-69d41d0efcfd","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-ef03c7b8-755d-4467-b0ab-69d41d0efcfd"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":501,"sizeSlug":"full","linkDestination":"none"} -->
    <figure class="wp-block-image size-full"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/plate2.png" alt="" class="wp-image-501"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"block_id":"8951708f-6c8f-41c8-bd91-df218c036987","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#fcfcfc"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-8951708f-6c8f-41c8-bd91-df218c036987"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:shortcode -->
    [wpforms id="859" title="false"]
    <!-- /wp:shortcode --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"16164e59-e077-40c7-9d81-0ae22b50c33f","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":80,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/restaurant4.jpg","backgroundPosition":"center center","backgroundImageColor":"#000000","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-16164e59-e077-40c7-9d81-0ae22b50c33f background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"bafcd3dd-50a3-493a-a038-e337ed68efb7"} -->
    <div class="block-bafcd3dd-50a3-493a-a038-e337ed68efb7 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"bottomPaddingMobile":30,"leftPaddingMobile":20,"block_id":"73e9f819-d4fd-43cb-a98d-ad1902704448","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-73e9f819-d4fd-43cb-a98d-ad1902704448"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"align":"left","id":484,"sizeSlug":"full","linkDestination":"none"} -->
    <div class="wp-block-image"><figure class="alignleft size-full"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/restaurant-logo2.png" alt="" class="wp-image-484"/></figure></div>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"bottomPaddingMobile":30,"block_id":"e72cbbad-4122-4e53-aa1a-5e9dde5d535f","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-e72cbbad-4122-4e53-aa1a-5e9dde5d535f"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9bcb6c0b-6572-4f98-929e-9cf68ffdb1e0","showSubHeading":false,"showSeparator":false,"headSpacing":30,"headSpacingTablet":30,"headSpacingMobile":20,"headingTitleFontSize":29,"headingTitleFontWeight":"400","headingTitleColor":"#ffffff","headingTag":"h5","level":5,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-9bcb6c0b-6572-4f98-929e-9cf68ffdb1e0"><h5 class="responsive-heading-title-text">Open Hours</h5></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"inner_gap":0,"labelFontWeight":"400","labelFontSize":16,"labelFontLineHeight":1.6,"block_id":"8e836d15-0fa1-4118-a814-eb459392a265"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-8e836d15-0fa1-4118-a814-eb459392a265"><div class="responsive-block-editor-addons-icon-wrap-8e836d15-0fa1-4118-a814-eb459392a265 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Mon-Sat: 10:00 AM - 08.00 PM","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"#FFFFFF","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"9d7e6c93-bccd-40e8-91ad-2ec3ed5df753"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-9d7e6c93-bccd-40e8-91ad-2ec3ed5df753"><div class="responsive-block-editor-addons-icon-9d7e6c93-bccd-40e8-91ad-2ec3ed5df753 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Mon-Sat: 10:00 AM - 08.00 PM</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Sunday: 10:00 AM - 10.00 PM","icon":"","label_color":"#ffffff","icon_hover_color":"","label_hover_color":"#ffffff","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"321bdc5d-6be4-44a2-9774-ead4e0aecf47"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-321bdc5d-6be4-44a2-9774-ead4e0aecf47"><div class="responsive-block-editor-addons-icon-321bdc5d-6be4-44a2-9774-ead4e0aecf47 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Sunday: 10:00 AM - 10.00 PM</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"bottomPaddingMobile":30,"block_id":"9cb36396-809d-4053-bc6c-5ac9eff1c141","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-9cb36396-809d-4053-bc6c-5ac9eff1c141"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"2c8bfa71-656a-4184-88f0-404d5d68176b","showSubHeading":true,"showSeparator":false,"headSpacing":30,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":29,"headingTitleFontWeight":"400","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingTag":"h5","level":5,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-2c8bfa71-656a-4184-88f0-404d5d68176b"><h5 class="responsive-heading-title-text">Location</h5><p class="responsive-heading-desc-text">123, Main Street, Anytown, ST 12345</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"bottomPaddingMobile":0,"block_id":"2b791397-9431-4d57-9cb2-fc8ab0f276b6","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-2b791397-9431-4d57-9cb2-fc8ab0f276b6"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"49054514-6434-46f8-b6b0-08059b916040","showSubHeading":false,"showSeparator":false,"headSpacing":30,"headSpacingTablet":30,"headSpacingMobile":20,"headingTitleFontSize":29,"headingTitleFontWeight":"400","headingTitleColor":"#ffffff","headingTag":"h5","level":5,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-49054514-6434-46f8-b6b0-08059b916040"><h5 class="responsive-heading-title-text">Reservation</h5></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"inner_gap":0,"labelFontWeight":"400","labelFontSize":16,"labelFontLineHeight":1.6,"block_id":"1790c216-5d65-4025-bc3c-3c14e1ad12ad"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-1790c216-5d65-4025-bc3c-3c14e1ad12ad"><div class="responsive-block-editor-addons-icon-wrap-1790c216-5d65-4025-bc3c-3c14e1ad12ad responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"+123 4567 890","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"#FFFFFF","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"4a7059ef-124d-4226-bca4-b16b6b7f4457"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-4a7059ef-124d-4226-bca4-b16b6b7f4457"><div class="responsive-block-editor-addons-icon-4a7059ef-124d-4226-bca4-b16b6b7f4457 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">+123 4567 890</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"hello@example.com","icon":"","label_color":"#ffffff","icon_hover_color":"","label_hover_color":"#ffffff","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"85ecfafb-4898-43a5-bf44-534faeb6ed2e"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-85ecfafb-4898-43a5-bf44-534faeb6ed2e"><div class="responsive-block-editor-addons-icon-85ecfafb-4898-43a5-bf44-534faeb6ed2e responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">hello@example.com</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Restaurant', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Restaurant', 'responsive-block-editor-addons' ),
		esc_html__( 'Cafe', 'responsive-block-editor-addons' ),
		esc_html__( 'Food', 'responsive-block-editor-addons' ),
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
