<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_photography_studio_layout',
	'collection' => array(
		'slug'      => 'photography-studio',
		'label'     => __( 'Photography Studio', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"ebded5ab-3c7e-4333-a529-2845573daade","topPadding":0,"topPaddingMobile":40,"topPaddingTablet":40,"bottomPadding":0,"bottomPaddingMobile":40,"bottomPaddingTablet":40,"leftPadding":0,"leftPaddingMobile":40,"leftPaddingTablet":40,"rightPadding":0,"rightPaddingMobile":40,"rightPaddingTablet":40,"opacity":100,"backgroundColor":"#000000","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-ebded5ab-3c7e-4333-a529-2845573daade background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"3d62d110-5544-4df2-8004-5144ba21928f"} -->
    <div class="block-3d62d110-5544-4df2-8004-5144ba21928f responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":300,"bottomPadding":300,"leftPadding":0,"rightPadding":100,"topPaddingTablet":200,"bottomPaddingTablet":200,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"block_id":"0853d48e-e703-4f84-a24b-16b927a8c677","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-0853d48e-e703-4f84-a24b-16b927a8c677"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0aef59d4-c384-4ac1-81fe-b2c380d1551a","showSubHeading":false,"showSeparator":false,"headSpacing":70,"separatorSpacing":0,"headSpacingTablet":70,"separatorSpacingTablet":0,"headSpacingMobile":20,"separatorSpacingMobile":0,"headingTitleFontSize":65,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":50,"headingTitleFontWeight":"700","headingTitleLineHeight":1.4,"headingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0aef59d4-c384-4ac1-81fe-b2c380d1551a"><h2 class="responsive-heading-title-text">Photography Studio</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"c48a1202-ad00-41a9-8ac6-5554f406dd40","label":"Read More About Us","link":"#","target":false,"vPadding":25,"hPadding":50,"vPaddingTablet":25,"hPaddingTablet":50,"vPaddingMobile":15,"hPaddingMobile":15,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderWidth":2,"borderRadius":50,"borderColor":"#ffffff","borderHColor":"","color":"#ffffff","background":"#000000","hColor":"#000000","buttonFontSize":15,"buttonFontSizeTablet":15,"buttonFontSizeMobile":15,"buttonLineHeight":1,"hbackground":"#ffffff","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-c48a1202-ad00-41a9-8ac6-5554f406dd40 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">Read More About Us</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"topPaddingTablet":10,"bottomPaddingTablet":10,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"6fde1389-af85-404f-b9b0-3e13e59eb68e","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-6fde1389-af85-404f-b9b0-3e13e59eb68e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":57,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-banner-home.png" alt="" class="wp-image-57"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"cb5357ed-6d90-4ec2-acf8-4a1cc0b7007d","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":0,"bottomPaddingMobile":0,"bottomPaddingTablet":0,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"opacity":100,"backgroundColor":"#000000","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-cb5357ed-6d90-4ec2-acf8-4a1cc0b7007d background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"3f8e730d-4f7b-410f-b0ac-05db0752a2e4"} -->
    <div class="block-3f8e730d-4f7b-410f-b0ac-05db0752a2e4 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"width":33.3333,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"86fbdb56-c0e6-454c-ab11-931f0206166f","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-86fbdb56-c0e6-454c-ab11-931f0206166f"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"5b541d1d-2597-44e1-b955-8803b2ae5620","showSubHeading":true,"showSeparator":false,"headSpacing":20,"subheadSpacing":20,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":20,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":20,"separatorSpacingMobile":0,"headingTitleFontSize":50,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":50,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-5b541d1d-2597-44e1-b955-8803b2ae5620"><h2 class="responsive-heading-title-text">Best Shots</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"fd164518-1dd5-4368-bc72-ce608c79f6f6","label":"Browse All Images","link":"#","target":false,"vPadding":25,"hPadding":50,"vPaddingTablet":25,"hPaddingTablet":50,"vPaddingMobile":15,"hPaddingMobile":15,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderWidth":2,"borderRadius":50,"borderColor":"#ffffff","borderHColor":"","color":"#ffffff","background":"#000000","hColor":"#000000","buttonFontSize":15,"buttonFontSizeTablet":15,"buttonFontSizeMobile":15,"buttonLineHeight":1,"hbackground":"#ffffff","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-fd164518-1dd5-4368-bc72-ce608c79f6f6 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">Browse All Images</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"c91b0d57-f02d-4096-9ee0-cd2dc254ceca","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c91b0d57-f02d-4096-9ee0-cd2dc254ceca"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"2b6a124e-83f9-49c6-b9dd-ab7eff6387a1","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":77,"title":"best-shot2","filename":"best-shot2.jpg","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot2.jpg","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/best-shot2/","alt":"","author":"17","description":"","caption":"","name":"best-shot2","status":"inherit","uploadedTo":0,"date":"2020-12-23T06:32:33.000Z","modified":"2020-12-23T06:32:33.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"dc1f87b2c5","delete":"752c6e8036","edit":"d4bbb3f972"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=77\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":203213,"filesizeHumanReadable":"198 KB","context":"","height":650,"width":370,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot2-150x150.jpg","orientation":"landscape"},"medium":{"height":300,"width":171,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot2-171x300.jpg","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot2.jpg","height":650,"width":370,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":329.99,"imageWidthTablet":210.33,"imageWidthMobile":323,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"2b6a124e-83f9-49c6-b9dd-ab7eff6387a1","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-2b6a124e-83f9-49c6-b9dd-ab7eff6387a1"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot2.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"45f4af39-b1d2-4b00-9604-9d6e76bb1627","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-45f4af39-b1d2-4b00-9604-9d6e76bb1627"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"ab2c9099-cd9e-4f0d-8ad2-f2e600fff925","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":84,"title":"best-shot","filename":"best-shot.jpg","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot.jpg","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/best-shot/","alt":"","author":"17","description":"","caption":"","name":"best-shot","status":"inherit","uploadedTo":0,"date":"2020-12-23T06:47:14.000Z","modified":"2020-12-23T06:47:14.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"a1f80a29d8","delete":"afbc888589","edit":"2098ccf453"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=84\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":160560,"filesizeHumanReadable":"157 KB","context":"","height":560,"width":370,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot-150x150.jpg","orientation":"landscape"},"medium":{"height":300,"width":198,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot-198x300.jpg","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot.jpg","height":560,"width":370,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":329.99,"imageWidthTablet":210.33,"imageWidthMobile":323,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"ab2c9099-cd9e-4f0d-8ad2-f2e600fff925","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-ab2c9099-cd9e-4f0d-8ad2-f2e600fff925"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/best-shot.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"a11fa154-7cd7-4e4f-bc1f-66ec499e4f48","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":0,"bottomPaddingMobile":0,"bottomPaddingTablet":0,"leftPadding":0,"rightPadding":0,"opacity":100,"backgroundColor":"#000000","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-a11fa154-7cd7-4e4f-bc1f-66ec499e4f48 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"40c08cbc-fd55-49c3-b8cf-d840d1bfdde1","showSubHeading":false,"showSeparator":false,"headSpacing":20,"subheadSpacing":20,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":20,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":20,"separatorSpacingMobile":0,"headingTitleFontSize":50,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":50,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-40c08cbc-fd55-49c3-b8cf-d840d1bfdde1"><h2 class="responsive-heading-title-text">Services</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"10c9740f-c45d-4f3c-af17-046cc9c3923b"} -->
    <div class="block-10c9740f-c45d-4f3c-af17-046cc9c3923b responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"width":33.3333,"topPadding":270,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":0,"rightMargin":10,"topMargin":0,"bottomMargin":0,"topPaddingTablet":270,"bottomPaddingTablet":30,"leftPaddingTablet":30,"rightPaddingTablet":30,"leftMarginTablet":0,"rightMarginTablet":10,"topMarginTablet":0,"bottomMarginTablet":0,"topPaddingMobile":270,"bottomPaddingMobile":30,"leftPaddingMobile":30,"rightPaddingMobile":30,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":10,"block_id":"1fff1aa3-e56e-4696-9f33-d9f5e879c584","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-services.png","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-1fff1aa3-e56e-4696-9f33-d9f5e879c584"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"45fcfec5-0edd-405e-8c21-c83397a1a5f3","showSubHeading":true,"showSeparator":false,"headSpacing":20,"subheadSpacing":0,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"headingTitleFontSize":25,"headingTitleFontSizeMobile":25,"headingTitleFontSizeTablet":25,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-45fcfec5-0edd-405e-8c21-c83397a1a5f3"><h2 class="responsive-heading-title-text">Shooting</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":270,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":0,"bottomMargin":0,"topPaddingTablet":270,"bottomPaddingTablet":30,"leftPaddingTablet":30,"rightPaddingTablet":30,"leftMarginTablet":5,"rightMarginTablet":5,"topMarginTablet":0,"bottomMarginTablet":0,"topPaddingMobile":270,"bottomPaddingMobile":30,"leftPaddingMobile":30,"rightPaddingMobile":30,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":10,"block_id":"4fa6d46e-0526-47eb-931d-381802f99acc","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-services1.png","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-4fa6d46e-0526-47eb-931d-381802f99acc"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"ac3aa46e-f137-409c-99f3-1ab145c098c1","showSubHeading":true,"showSeparator":false,"headSpacing":20,"subheadSpacing":0,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"headingTitleFontSize":25,"headingTitleFontSizeMobile":25,"headingTitleFontSizeTablet":25,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-ac3aa46e-f137-409c-99f3-1ab145c098c1"><h2 class="responsive-heading-title-text">Video</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":270,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":0,"topMargin":0,"bottomMargin":0,"topPaddingTablet":270,"bottomPaddingTablet":30,"leftPaddingTablet":30,"rightPaddingTablet":30,"leftMarginTablet":10,"rightMarginTablet":0,"topMarginTablet":0,"bottomMarginTablet":0,"topPaddingMobile":270,"bottomPaddingMobile":30,"leftPaddingMobile":30,"rightPaddingMobile":30,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":0,"block_id":"c3d114c1-acba-4bd9-8075-ccef99f17c74","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-services2.png","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c3d114c1-acba-4bd9-8075-ccef99f17c74"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"5cfb1c77-3c7f-4df3-a32a-f3e31d38e76f","showSubHeading":true,"showSeparator":false,"headSpacing":20,"subheadSpacing":0,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"headingTitleFontSize":25,"headingTitleFontSizeMobile":25,"headingTitleFontSizeTablet":25,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-5cfb1c77-3c7f-4df3-a32a-f3e31d38e76f"><h2 class="responsive-heading-title-text">Editing</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"f6a1ea75-5a7e-4ca6-8ba8-824482542fbd","topPadding":110,"topPaddingMobile":110,"topPaddingTablet":110,"bottomPadding":70,"bottomPaddingMobile":70,"bottomPaddingTablet":70,"opacity":100,"backgroundColor":"#000000","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-f6a1ea75-5a7e-4ca6-8ba8-824482542fbd background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"4bcfd85e-1b46-4945-b345-1ac0d8e71e7f","showSubHeading":false,"showSeparator":false,"headSpacing":20,"subheadSpacing":20,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":20,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":20,"separatorSpacingMobile":0,"headingTitleFontSize":50,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":50,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-4bcfd85e-1b46-4945-b345-1ac0d8e71e7f"><h2 class="responsive-heading-title-text">Portfolio</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"001ea0a6-f176-4c60-acb0-c34bc5bf6e06"} -->
    <div class="block-001ea0a6-f176-4c60-acb0-c34bc5bf6e06 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"leftMargin":0,"rightMargin":0,"topMargin":0,"bottomMargin":0,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginTablet":0,"bottomMarginTablet":0,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":0,"block_id":"3e580baa-c9b5-477c-863d-2de8f548e436","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-3e580baa-c9b5-477c-863d-2de8f548e436"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"915cf6f3-a755-4b2d-af2a-56a82a58d308","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":120,"title":"portfolio","filename":"portfolio.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio-2/","alt":"","author":"17","description":"","caption":"","name":"portfolio-2","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:31:16.000Z","modified":"2020-12-23T07:31:16.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"65fbc4be3b","delete":"7932be1ca4","edit":"792e0bb532"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=120\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":193599,"filesizeHumanReadable":"189 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"915cf6f3-a755-4b2d-af2a-56a82a58d308","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-915cf6f3-a755-4b2d-af2a-56a82a58d308"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"5a541369-1ad2-4484-b915-1977e1daa928","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-5a541369-1ad2-4484-b915-1977e1daa928"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"a79e544e-ef3b-4ed6-9a4c-6ab357734ab6","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":125,"title":"portfolio1","filename":"portfolio1.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio1/","alt":"","author":"17","description":"","caption":"","name":"portfolio1","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:43:44.000Z","modified":"2020-12-23T07:43:44.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"eae7072855","delete":"6217b093fb","edit":"493176309f"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=125\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":207976,"filesizeHumanReadable":"203 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"a79e544e-ef3b-4ed6-9a4c-6ab357734ab6","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-a79e544e-ef3b-4ed6-9a4c-6ab357734ab6"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"752b2f26-2548-48c8-8806-928abbf105c6","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-752b2f26-2548-48c8-8806-928abbf105c6"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"64a3e868-43bf-4caa-b3ba-e87e7dcc5139","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":126,"title":"portfolio2","filename":"portfolio2.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio2/","alt":"","author":"17","description":"","caption":"","name":"portfolio2","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:44:38.000Z","modified":"2020-12-23T07:44:38.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"76958ea579","delete":"2411062033","edit":"0cb454ef20"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=126\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":152480,"filesizeHumanReadable":"149 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"64a3e868-43bf-4caa-b3ba-e87e7dcc5139","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-64a3e868-43bf-4caa-b3ba-e87e7dcc5139"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"897ddcef-69b0-4495-8705-9847a65e422d","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-897ddcef-69b0-4495-8705-9847a65e422d"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"d17cfba3-a607-4bdf-92cc-96aec1439305","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":127,"title":"portfolio3","filename":"portfolio3.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio3/","alt":"","author":"17","description":"","caption":"","name":"portfolio3","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:45:23.000Z","modified":"2020-12-23T07:45:23.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"98208014ed","delete":"5e8ecd791e","edit":"c28215c22d"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=127\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":57917,"filesizeHumanReadable":"57 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"d17cfba3-a607-4bdf-92cc-96aec1439305","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-d17cfba3-a607-4bdf-92cc-96aec1439305"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"a805ca23-2562-4dd3-a91a-425d29b60031","showHeading":false,"showSeparator":false,"seperatorPosition":"belowDesc","separatorHeight":2,"separatorWidth":81,"separatorWidthType":"px","separatorColor":"#ffffff","subheadSpacing":0,"separatorSpacing":0,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-a805ca23-2562-4dd3-a91a-425d29b60031"><p class="responsive-heading-desc-text"><a href="#"><span class="has-inline-color has-button-hover-text-color-color"><span style="text-decoration: underline">Browse All</span></span></a></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"f404141e-e3dd-4ef6-a6d5-d06630735319","topPadding":60,"topPaddingMobile":60,"topPaddingTablet":60,"bottomPadding":60,"bottomPaddingMobile":60,"bottomPaddingTablet":60,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"opacity":100,"backgroundColor":"#000000","backgroundType":"color","boxShadowColor":"#ffffff","boxShadowVOffset":-2,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-f404141e-e3dd-4ef6-a6d5-d06630735319 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/section {"block_id":"dbe603b8-1ea0-484a-8190-87082f9a8dd3","topPadding":50,"topPaddingTablet":20,"bottomPadding":50,"bottomPaddingTablet":20,"leftPadding":0,"leftPaddingTablet":20,"rightPadding":50,"rightPaddingTablet":20,"opacity":0} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-dbe603b8-1ea0-484a-8190-87082f9a8dd3 background-type-none alignundefined"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"90daa9d1-6d40-499e-918e-0953c35b8bc9","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":150,"title":"photo-studio-logo","filename":"photo-studio-logo.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-studio-logo.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/photo-studio-logo/","alt":"","author":"17","description":"","caption":"","name":"photo-studio-logo","status":"inherit","uploadedTo":0,"date":"2020-12-23T08:02:23.000Z","modified":"2020-12-23T08:02:23.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"a230387fb3","delete":"b6c53da17a","edit":"13169f6356"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=150\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":3959,"filesizeHumanReadable":"4 KB","context":"","height":65,"width":187,"orientation":"landscape","sizes":{"thumbnail":{"height":65,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-studio-logo-150x65.png","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-studio-logo.png","height":65,"width":187,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":187,"imageWidthTablet":187,"imageWidthMobile":187,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"90daa9d1-6d40-499e-918e-0953c35b8bc9","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-90daa9d1-6d40-499e-918e-0953c35b8bc9"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/photo-studio-logo.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"align":"center","gap":28,"size":31,"hideLabel":true,"icon_layout":"horizontal","block_id":"36f71e91-94b7-4617-b9e4-837b6ea9f33a"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list horizontal responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-horizontal responsive-block-editor-addons-icon-list__no-label responsive-block-editor-addons-36f71e91-94b7-4617-b9e4-837b6ea9f33a"><div class="responsive-block-editor-addons-icon-wrap-36f71e91-94b7-4617-b9e4-837b6ea9f33a responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"hideLabel":true,"icon":"facebook-f","icon_color":"#ffffff","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"3e5ee3e4-f1e3-4321-b9f6-d3d2f04a4c92"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-3e5ee3e4-f1e3-4321-b9f6-d3d2f04a4c92"><a target="_self" rel="noopener noreferrer" aria-label="#Label" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-3e5ee3e4-f1e3-4321-b9f6-d3d2f04a4c92 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 264 512"><path d="M76.7 512V283H0v-91h76.7v-71.7C76.7 42.4 124.3 0 193.8 0c33.3 0 61.9 2.5 70.2 3.6V85h-48.2c-37.8 0-45.1 18-45.1 44.3V192H256l-11.7 91h-73.6v229"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"hideLabel":true,"icon":"instagram","icon_color":"#ffffff","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"e4eeb705-70b1-4e66-bd59-ad7ee51f38d5"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-e4eeb705-70b1-4e66-bd59-ad7ee51f38d5"><a target="_self" rel="noopener noreferrer" aria-label="#Label" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-e4eeb705-70b1-4e66-bd59-ad7ee51f38d5 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512"><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"hideLabel":true,"icon":"google-plus-g","icon_color":"#ffffff","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"e7490219-133c-4479-ae12-cc21e44c3235"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-e7490219-133c-4479-ae12-cc21e44c3235"><a target="_self" rel="noopener noreferrer" aria-label="#Label" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-e7490219-133c-4479-ae12-cc21e44c3235 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 640 512"><path d="M386.061 228.496c1.834 9.692 3.143 19.384 3.143 31.956C389.204 370.205 315.599 448 204.8 448c-106.084 0-192-85.915-192-192s85.916-192 192-192c51.864 0 95.083 18.859 128.611 50.292l-52.126 50.03c-14.145-13.621-39.028-29.599-76.485-29.599-65.484 0-118.92 54.221-118.92 121.277 0 67.056 53.436 121.277 118.92 121.277 75.961 0 104.513-54.745 108.965-82.773H204.8v-66.009h181.261zm185.406 6.437V179.2h-56.001v55.733h-55.733v56.001h55.733v55.733h56.001v-55.733H627.2v-56.001h-55.733z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"hideLabel":true,"icon":"pinterest-p","icon_color":"#ffffff","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"58f561fa-ab60-41d1-8f05-643f897fbd48"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-58f561fa-ab60-41d1-8f05-643f897fbd48"><a target="_self" rel="noopener noreferrer" aria-label="#Label" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-58f561fa-ab60-41d1-8f05-643f897fbd48 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 384 512"><path d="M204 6.5C101.4 6.5 0 74.9 0 185.6 0 256 39.6 296 63.6 296c9.9 0 15.6-27.6 15.6-35.4 0-9.3-23.7-29.1-23.7-67.8 0-80.4 61.2-137.4 140.4-137.4 68.1 0 118.5 38.7 118.5 109.8 0 53.1-21.3 152.7-90.3 152.7-24.9 0-46.2-18-46.2-43.8 0-37.8 26.4-74.4 26.4-113.4 0-66.2-93.9-54.2-93.9 25.8 0 16.8 2.1 35.4 9.6 50.7-13.8 59.4-42 147.9-42 209.1 0 18.9 2.7 37.5 4.5 56.4 3.4 3.8 1.7 3.4 6.9 1.5 50.4-69 48.6-82.5 71.4-172.8 12.3 23.4 44.1 36 69.3 36 106.2 0 153.9-103.5 153.9-196.8C384 71.3 298.2 6.5 204 6.5z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"hideLabel":true,"icon":"linkedin-in","icon_color":"#ffffff","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"65b8f22f-7fd0-4a20-8486-3706d06384e9"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-65b8f22f-7fd0-4a20-8486-3706d06384e9"><a target="_self" rel="noopener noreferrer" aria-label="#Label" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-65b8f22f-7fd0-4a20-8486-3706d06384e9 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448.1 512"><path d="M100.3 448H7.4V148.9h92.9V448zM53.8 108.1C24.1 108.1 0 83.5 0 53.8S24.1 0 53.8 0s53.8 24.1 53.8 53.8-24.1 54.3-53.8 54.3zM448 448h-92.7V302.4c0-34.7-.7-79.2-48.3-79.2-48.3 0-55.7 37.7-55.7 76.7V448h-92.8V148.9h89.1v40.8h1.3c12.4-23.5 42.7-48.3 87.9-48.3 94 0 111.3 61.9 111.3 142.3V448h-.1z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list -->
    
    <!-- wp:spacer {"height":20} -->
    <div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"eb2072f0-466b-46e9-9bf2-77725a29a71b","showHeading":false,"showSeparator":false,"subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":18,"subHeadingTitleFontSizeMobile":18,"subHeadingTitleFontSizeTablet":18,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#cccccc"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-eb2072f0-466b-46e9-9bf2-77725a29a71b"><p class="responsive-heading-desc-text">+123 4567890 | contact@example.com</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"8792d63d-6938-4906-97cf-4ae39fa5d502","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":18,"subHeadingTitleFontSizeMobile":18,"subHeadingTitleFontSizeTablet":18,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#cccccc"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-8792d63d-6938-4906-97cf-4ae39fa5d502"><p class="responsive-heading-desc-text">123, Main Street, Anytown, ST 12345</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Photography Studio', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
		esc_html__( 'Photography', 'responsive-block-editor-addons' ),
		esc_html__( 'Creative', 'responsive-block-editor-addons' ),
		esc_html__( 'Design', 'responsive-block-editor-addons' ),
		esc_html__( 'Agency', 'responsive-block-editor-addons' ),
		esc_html__( 'Studio', 'responsive-block-editor-addons' ),
		esc_html__( 'Photography Studio', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
