<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_corporate_lawyer_about_layout',
	'collection' => array(
		'slug'      => 'corporate-lawyer-about',
		'label'     => __( 'About Corporate Lawyer', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"5dd3a74a-f348-4a6c-9969-ed1bac74c585","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-5dd3a74a-f348-4a6c-9969-ed1bac74c585 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0c0d5cac-1e63-4331-a335-90008356500d","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":80,"headSpacingTablet":80,"headSpacingMobile":80,"headingTitleFontSize":39,"headingTitleFontWeight":"700"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0c0d5cac-1e63-4331-a335-90008356500d"><h2 class="responsive-heading-title-text">ABOUT US</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"ac37b635-f40f-4629-a2d1-33217cf072d4"} -->
    <div class="block-ac37b635-f40f-4629-a2d1-33217cf072d4 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"leftPaddingMobile":30,"rightPaddingMobile":30,"block_id":"2ed93de9-ed1e-4b96-9c65-417309a1b76d","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-2ed93de9-ed1e-4b96-9c65-417309a1b76d"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"deae8823-94fc-45d0-86be-8358bf4a7e30","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-deae8823-94fc-45d0-86be-8358bf4a7e30"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.<br><br>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"block_id":"c65f01f8-e794-44d0-b74d-dfd41b76c45a","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c65f01f8-e794-44d0-b74d-dfd41b76c45a"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"8e779082-bf2a-4b4b-a425-75b384444aa0","classMigrate":true,"imgiconPosition":"left","ressubHeadFontWeight":"400","resheadSpace":20,"source_type":"image","resseperatorStyle":"none","iconRightMargin":20,"iconImage":{"id":106,"title":"vision","filename":"vision.jpg","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision.jpg","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/vision/","alt":"","author":"17","description":"","caption":"","name":"vision","status":"inherit","uploadedTo":0,"date":"2020-12-24T07:25:50.000Z","modified":"2020-12-24T07:25:50.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 24, 2020","nonces":{"update":"63960f7151","delete":"850b475fa5","edit":"607876992e"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=106\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":4344,"filesizeHumanReadable":"4 KB","context":"","height":200,"width":200,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision-150x150.jpg","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision.jpg","height":200,"width":200,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":192.5,"imageWidthTablet":128,"imageWidthMobile":119,"stack":"mobile","resshowPrefix":false,"counterId":"8e779082-bf2a-4b4b-a425-75b384444aa0","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-8e779082-bf2a-4b4b-a425-75b384444aa0"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Our Vision</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    
    <!-- wp:spacer {"height":70} -->
    <div style="height:70px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"e91d9207-0b3b-4476-9d1f-1950bafff951","classMigrate":true,"imgiconPosition":"left","ressubHeadFontWeight":"400","resheadSpace":20,"source_type":"image","resseperatorStyle":"none","iconRightMargin":20,"iconImage":{"id":107,"title":"mission","filename":"mission.jpg","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission.jpg","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/mission/","alt":"","author":"17","description":"","caption":"","name":"mission","status":"inherit","uploadedTo":0,"date":"2020-12-24T07:25:54.000Z","modified":"2020-12-24T07:25:54.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 24, 2020","nonces":{"update":"9999b52980","delete":"9f4c6db2c5","edit":"32eb353323"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=107\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":5496,"filesizeHumanReadable":"5 KB","context":"","height":200,"width":200,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission-150x150.jpg","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission.jpg","height":200,"width":200,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":192.5,"imageWidthTablet":128,"imageWidthMobile":119,"stack":"mobile","resshowPrefix":false,"counterId":"e91d9207-0b3b-4476-9d1f-1950bafff951","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-e91d9207-0b3b-4476-9d1f-1950bafff951"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Our Mission</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    
    <!-- wp:spacer {"height":60} -->
    <div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"92c969d5-5057-454d-a3a7-ad280e785645","topPadding":90,"topPaddingMobile":50,"topPaddingTablet":50,"bottomPadding":90,"bottomPaddingMobile":50,"bottomPaddingTablet":50,"leftPadding":0,"leftPaddingMobile":30,"leftPaddingTablet":30,"rightPadding":0,"rightPaddingMobile":30,"rightPaddingTablet":30,"opacity":100,"backgroundColor":"#8c2849","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-92c969d5-5057-454d-a3a7-ad280e785645 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"1387cf49-1cfc-429b-b967-d79c5f11e862","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":80,"headSpacingTablet":80,"headSpacingMobile":80,"headingTitleFontSize":39,"headingTitleFontSizeMobile":40,"headingTitleFontWeight":"700","headingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-1387cf49-1cfc-429b-b967-d79c5f11e862"><h2 class="responsive-heading-title-text">EXPERT ATTORNEYS</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"600733fb-5c7e-4ef2-8c98-6b4f04e196af"} -->
    <div class="block-600733fb-5c7e-4ef2-8c98-6b4f04e196af responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"width":33.33,"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":15,"rightMargin":15,"topMargin":15,"bottomMargin":15,"topPaddingTablet":20,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":30,"bottomPaddingMobile":30,"leftPaddingMobile":0,"rightPaddingMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":30,"bottomMarginMobile":0,"block_id":"48f509d8-e3ed-490f-89e7-1337745c9f16","boxShadowColor":"#0f0f2b","boxShadowBlur":50,"hoverboxShadowColor":"#0f0f2b","hoverboxShadowBlur":50,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-48f509d8-e3ed-490f-89e7-1337745c9f16"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":134,"width":300,"height":300,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large is-resized"><img src="http://testccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer3.jpg" alt="" class="wp-image-134" width="300" height="300"/></figure>
    <!-- /wp:image -->
    
    <!-- wp:spacer {"height":5} -->
    <div style="height:5px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"1b35da6b-ded5-4a3b-a194-85382108a344","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":15,"subHeadingTitleFontWeight":"300","subHeadingTitleLineHeight":2.1,"subHeadingTitleColor":"#353535"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-1b35da6b-ded5-4a3b-a194-85382108a344"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"43eb36ef-ac44-49ee-9730-c28b151499ec","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontFamily":"Montserrat","headingTitleFontSize":17,"headingTitleColor":"#000000","subHeadingTitleFontFamily":"Montserrat","subHeadingTitleFontSize":14,"subHeadingTitleFontWeight":"700","subHeadingTitleColor":"#555555"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-43eb36ef-ac44-49ee-9730-c28b151499ec"><h2 class="responsive-heading-title-text">SMITH DOE</h2><p class="responsive-heading-desc-text">CEO/Founder</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.33,"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":15,"rightMargin":15,"topMargin":15,"bottomMargin":15,"topPaddingTablet":20,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":30,"bottomPaddingMobile":30,"leftPaddingMobile":0,"rightPaddingMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":30,"bottomMarginMobile":0,"block_id":"0042b35c-2cbb-4a49-85d1-4264853128e2","boxShadowColor":"#0f0f2b","boxShadowBlur":50,"hoverboxShadowColor":"#0f0f2b","hoverboxShadowBlur":50,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-0042b35c-2cbb-4a49-85d1-4264853128e2"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":137,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer2.jpg" alt="" class="wp-image-137"/></figure>
    <!-- /wp:image -->
    
    <!-- wp:spacer {"height":5} -->
    <div style="height:5px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"71b56880-616d-4f2d-a50a-2eb8d395c1fb","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":15,"subHeadingTitleFontWeight":"300","subHeadingTitleLineHeight":2.1,"subHeadingTitleColor":"#353535"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-71b56880-616d-4f2d-a50a-2eb8d395c1fb"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"1dc14e83-66cc-4532-9462-c68109792d62","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontFamily":"Montserrat","headingTitleFontSize":17,"headingTitleColor":"#000000","subHeadingTitleFontFamily":"Montserrat","subHeadingTitleFontSize":14,"subHeadingTitleFontWeight":"700","subHeadingTitleColor":"#555555"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-1dc14e83-66cc-4532-9462-c68109792d62"><h2 class="responsive-heading-title-text">JOHN DOE</h2><p class="responsive-heading-desc-text">Employment Lawyer</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":33.33,"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":15,"rightMargin":15,"topMargin":15,"bottomMargin":15,"topPaddingTablet":20,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":30,"bottomPaddingMobile":30,"leftPaddingMobile":0,"rightPaddingMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":30,"bottomMarginMobile":0,"block_id":"427a9b10-7fab-4e7d-aeab-8aeb6a7d7655","boxShadowColor":"#0f0f2b","boxShadowBlur":50,"hoverboxShadowColor":"#0f0f2b","hoverboxShadowBlur":50,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-427a9b10-7fab-4e7d-aeab-8aeb6a7d7655"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":139,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer1.jpg" alt="" class="wp-image-139"/></figure>
    <!-- /wp:image -->
    
    <!-- wp:spacer {"height":5} -->
    <div style="height:5px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"249713f4-4ba8-47ef-a30f-c8ccafc2f1d8","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":15,"subHeadingTitleFontWeight":"300","subHeadingTitleLineHeight":2.1,"subHeadingTitleColor":"#353535"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-249713f4-4ba8-47ef-a30f-c8ccafc2f1d8"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"091faf6c-0ee4-40a9-88bd-bb1083cbba49","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontFamily":"Montserrat","headingTitleFontSize":17,"headingTitleColor":"#000000","subHeadingTitleFontFamily":"Montserrat","subHeadingTitleFontSize":14,"subHeadingTitleFontWeight":"700","subHeadingTitleColor":"#555555"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-091faf6c-0ee4-40a9-88bd-bb1083cbba49"><h2 class="responsive-heading-title-text">RICHARD ROE</h2><p class="responsive-heading-desc-text">Family Lawyer</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"185d8795-c06a-4d8b-a3b1-d3460b4d1493","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-185d8795-c06a-4d8b-a3b1-d3460b4d1493 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"7f93d54d-30cb-4aa2-836f-ca74cf72c2fe"} -->
    <div class="block-7f93d54d-30cb-4aa2-836f-ca74cf72c2fe responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":20,"bottomPadding":20,"leftPadding":20,"rightPadding":20,"block_id":"a372b12e-149a-4fc6-b72d-3eae38555196","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-a372b12e-149a-4fc6-b72d-3eae38555196"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"28485a6b-d741-48f0-8ad8-a5cc501e07fe","classMigrate":true,"resheadingAlign":"left","ressubHeadFontSize":16,"ressubHeadFontWeight":"400","ressubHeadSpace":15,"source_type":"image","resseperatorStyle":"none","iconBottomMargin":15,"iconImage":{"id":35,"title":"lawyer","filename":"lawyer.png","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer.png","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/lawyer/","alt":"","author":"17","description":"","caption":"","name":"lawyer","status":"inherit","uploadedTo":0,"date":"2020-12-24T05:48:06.000Z","modified":"2020-12-24T05:48:06.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 24, 2020","nonces":{"update":"f226798875","delete":"743d2f72e7","edit":"69068bf337"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=35\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":3079,"filesizeHumanReadable":"3 KB","context":"","height":62,"width":211,"orientation":"landscape","sizes":{"thumbnail":{"height":62,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer-150x62.png","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer.png","height":62,"width":211,"orientation":"landscape"}},"compat":{"item":"","meta":""},"mediaStates":"Logo"},"imageWidth":210,"imageWidthTablet":211,"imageWidthMobile":211,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"28485a6b-d741-48f0-8ad8-a5cc501e07fe","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-28485a6b-d741-48f0-8ad8-a5cc501e07fe"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"fc898195-589b-4789-910b-4a0b4c22294e","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subHeadingTitleLineHeight":1.4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-fc898195-589b-4789-910b-4a0b4c22294e"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text, make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":20,"bottomPadding":20,"leftPadding":50,"rightPadding":20,"leftPaddingMobile":20,"block_id":"51a195b4-40ee-48b3-a516-92e4f8ba9e30","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-51a195b4-40ee-48b3-a516-92e4f8ba9e30"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"09f3c69d-4527-4dd7-a863-7b83a4a80a09","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":12,"headSpacingTablet":12,"headSpacingMobile":12,"headingTitleFontSize":21.33,"headingTitleFontWeight":"700","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-09f3c69d-4527-4dd7-a863-7b83a4a80a09"><h4 class="responsive-heading-title-text">Quick Links</h4></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"gap":0,"inner_gap":0,"labelFontWeight":"400","labelFontSize":16,"labelFontLineHeight":1.6,"block_id":"88506bc3-df44-4cb5-963a-ba6c445a3894"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-88506bc3-df44-4cb5-963a-ba6c445a3894"><div class="responsive-block-editor-addons-icon-wrap-88506bc3-df44-4cb5-963a-ba6c445a3894 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Home","icon":"","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"96c4d90a-63a6-4244-b7ca-18cfa43f6afc"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-96c4d90a-63a6-4244-b7ca-18cfa43f6afc"><a target="_self" rel="noopener noreferrer" aria-label="Home" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-96c4d90a-63a6-4244-b7ca-18cfa43f6afc responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Home</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Services","icon":"","disableLink":false,"block_id":"255bbc41-7e51-4a01-a87c-e32ed78a59a4"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-255bbc41-7e51-4a01-a87c-e32ed78a59a4"><a target="_self" rel="noopener noreferrer" aria-label="Services" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-255bbc41-7e51-4a01-a87c-e32ed78a59a4 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Services</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"About","icon":"","disableLink":false,"block_id":"5cdb2c07-412d-45dd-8762-e382ef147d9e"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-5cdb2c07-412d-45dd-8762-e382ef147d9e"><a target="_self" rel="noopener noreferrer" aria-label="About" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-5cdb2c07-412d-45dd-8762-e382ef147d9e responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">About</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Blog","icon":"","disableLink":false,"block_id":"238a46cd-0c90-43e0-9728-3eb2ca627fbf"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-238a46cd-0c90-43e0-9728-3eb2ca627fbf"><a target="_self" rel="noopener noreferrer" aria-label="Blog" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-238a46cd-0c90-43e0-9728-3eb2ca627fbf responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Blog</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Contact","icon":"","disableLink":false,"block_id":"db7a1e9a-10a5-499f-9c2c-e91f0b681dc3"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-db7a1e9a-10a5-499f-9c2c-e91f0b681dc3"><a target="_self" rel="noopener noreferrer" aria-label="Contact" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-db7a1e9a-10a5-499f-9c2c-e91f0b681dc3 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Contact</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":20,"bottomPadding":20,"leftPadding":50,"rightPadding":20,"leftPaddingTablet":20,"leftPaddingMobile":20,"block_id":"b58d6411-657d-43c5-a2e8-29c09753a0ad","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-b58d6411-657d-43c5-a2e8-29c09753a0ad"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"4c0b4745-0973-4ea0-b207-63818f221d33","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":12,"headSpacingTablet":12,"headSpacingMobile":12,"headingTitleFontSize":21.33,"headingTitleFontWeight":"700","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-4c0b4745-0973-4ea0-b207-63818f221d33"><h4 class="responsive-heading-title-text">Contact Us</h4></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"262f4e64-196c-4e67-b9d9-6aaefa12b9d0","classMigrate":true,"alignment":"left","icon":"map-marker-alt","imgiconPosition":"left","resIconSize":30,"resheadFontSize":18,"ressubHeadFontSize":14,"ressubHeadFontWeight":"400","resheadSpace":2,"resseperatorStyle":"none","resprefixSpace":0,"iconRightMargin":5,"stack":"mobile","resshowPrefix":false,"counterId":"262f4e64-196c-4e67-b9d9-6aaefa12b9d0","sepSpace":0,"icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-262f4e64-196c-4e67-b9d9-6aaefa12b9d0"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 384 512"><path d="M172.268 501.67C26.97 291.031 0 269.413 0 192 0 85.961 85.961 0 192 0s192 85.961 192 192c0 77.413-26.97 99.031-172.268 309.67-9.535 13.774-29.93 13.773-39.464 0zM192 272c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Address</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">123, Main Street, Anytown, ST 12345.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"1826cd70-a2a8-4053-8f87-cc2e36f82087","classMigrate":true,"alignment":"left","icon":"envelope","imgiconPosition":"left","resIconSize":30,"resheadFontSize":18,"ressubHeadFontSize":14,"ressubHeadFontWeight":"400","resheadSpace":2,"resseperatorStyle":"none","resprefixSpace":0,"iconRightMargin":5,"stack":"mobile","resshowPrefix":false,"counterId":"1826cd70-a2a8-4053-8f87-cc2e36f82087","sepSpace":0,"icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-1826cd70-a2a8-4053-8f87-cc2e36f82087"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Send Mail</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">info@example.com</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"c5898346-07b8-49ca-8abb-0b7479744736","classMigrate":true,"alignment":"left","icon":"phone","imgiconPosition":"left","resIconSize":30,"resheadFontSize":18,"ressubHeadFontSize":14,"ressubHeadFontWeight":"400","resheadSpace":2,"resseperatorStyle":"none","resprefixSpace":0,"iconRightMargin":5,"stack":"mobile","resshowPrefix":false,"counterId":"c5898346-07b8-49ca-8abb-0b7479744736","sepSpace":0,"icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-c5898346-07b8-49ca-8abb-0b7479744736"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M493.4 24.6l-104-24c-11.3-2.6-22.9 3.3-27.5 13.9l-48 112c-4.2 9.8-1.4 21.3 6.9 28l60.6 49.6c-36 76.7-98.9 140.5-177.2 177.2l-49.6-60.6c-6.8-8.3-18.2-11.1-28-6.9l-112 48C3.9 366.5-2 378.1.6 389.4l24 104C27.1 504.2 36.7 512 48 512c256.1 0 464-207.5 464-464 0-11.2-7.7-20.9-18.6-23.4z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Call Us</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">123-456-7890</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'About | Corporate Lawyer', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
		esc_html__( 'Consulting', 'responsive-block-editor-addons' ),
		esc_html__( 'Law', 'responsive-block-editor-addons' ),
		esc_html__( 'Professional', 'responsive-block-editor-addons' ),
		esc_html__( 'About Corporate Lawyer', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
