<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_lifestyle_layout',
	'collection' => array(
		'slug'      => 'lifestyle',
		'label'     => __( 'Lifestyle', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"5ae204e6-78fc-4a09-8a31-fbebb800f87b","topPadding":150,"topPaddingMobile":0,"topPaddingTablet":100,"bottomPadding":0,"bottomPaddingMobile":19,"bottomPaddingTablet":16,"leftPadding":0,"leftPaddingMobile":20,"leftPaddingTablet":20,"rightPadding":0,"rightPaddingMobile":20,"rightPaddingTablet":20,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/home-banner.png","backgroundPosition":"center center","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-5ae204e6-78fc-4a09-8a31-fbebb800f87b background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"56490692-7a0f-47c5-977d-4ba2d0850b15"} -->
    <div class="block-56490692-7a0f-47c5-977d-4ba2d0850b15 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":60,"bottomPadding":150,"topPaddingTablet":80,"bottomPaddingTablet":60,"block_id":"cefee7f5-169f-45d8-aa0f-b1990506a56c","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-cefee7f5-169f-45d8-aa0f-b1990506a56c"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"e7824b7b-45eb-4525-b944-14de1a0af54f","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"700","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-e7824b7b-45eb-4525-b944-14de1a0af54f"><h2 class="responsive-heading-title-text">LATEST</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"03f386ff-9684-4ea8-9bbe-9e5fd36a7bb4","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"300","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-03f386ff-9684-4ea8-9bbe-9e5fd36a7bb4"><h2 class="responsive-heading-title-text">TRENDS</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"2f0b2029-b4e6-497d-a757-ed2103b0cb30","label":"READ MORE","link":"#","target":false,"vPadding":15,"hPadding":30,"vPaddingTablet":15,"hPaddingTablet":30,"vPaddingMobile":15,"hPaddingMobile":30,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderWidth":2,"borderRadius":0,"borderColor":"#0c0c0c","borderHColor":"","color":"#FFFFFF","background":"#0c0c0c","hColor":"#0c0c0c","buttonFontSize":16,"buttonLineHeight":1,"hbackground":"#FFFFFF","buttonFontWeight":"500","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-2f0b2029-b4e6-497d-a757-ed2103b0cb30 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">READ MORE</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":40,"topPaddingMobile":50,"block_id":"70d35639-d262-49cb-9c2b-fb257014f3a0","blockBorderStyle":"solid","blockBorderWidth":10,"blockBorderColor":"#0c0c0c","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-70d35639-d262-49cb-9c2b-fb257014f3a0"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":109,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/lifestyle-banner1.png" alt="" class="wp-image-109"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"c4b6d2eb-68f4-45d4-8bd5-ae3bbe5b1a6b","topPadding":150,"topPaddingMobile":0,"topPaddingTablet":80,"bottomPadding":0,"bottomPaddingMobile":0,"bottomPaddingTablet":80,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":20,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":20,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/home-banner-background.png","backgroundPosition":"center center","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-c4b6d2eb-68f4-45d4-8bd5-ae3bbe5b1a6b background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"f74fd61b-67bb-43ff-be7f-352510dcdb81"} -->
    <div class="block-f74fd61b-67bb-43ff-be7f-352510dcdb81 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":41,"topMarginMobile":50,"block_id":"38e11c4e-1d6c-463e-a0ec-73be4086512d","blockBorderStyle":"solid","blockBorderWidth":10,"blockBorderColor":"#aaaaaa","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-38e11c4e-1d6c-463e-a0ec-73be4086512d"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":118,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/lifestyle-banner2.png" alt="" class="wp-image-118"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":59,"bottomPadding":150,"topPaddingTablet":50,"bottomPaddingTablet":10,"topPaddingMobile":50,"bottomPaddingMobile":50,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"498445c3-79a5-4131-8b26-cbafad7a0f71","blockBorderColor":"#aaaaaa","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-498445c3-79a5-4131-8b26-cbafad7a0f71"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"52bf3eab-1261-432f-bcb8-ac71e74f2618","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"700","headingTitleColor":"#0c0c0c","headingAlignment":"right","headingAlignmentTablet":"right","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-52bf3eab-1261-432f-bcb8-ac71e74f2618"><h2 class="responsive-heading-title-text">GET NEW</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"07d0068a-1f2a-4675-b19f-eeded49d0f43","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"300","headingTitleColor":"#0c0c0c","headingAlignment":"right","headingAlignmentTablet":"right","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-07d0068a-1f2a-4675-b19f-eeded49d0f43"><h2 class="responsive-heading-title-text">OFFICE LOOK</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"right","buttonAlignmentTablet":"right","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons right tabletAlignright mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"b15df4cd-0001-417c-a38d-8049e1695140","label":"READ MORE","link":"#","target":false,"vPadding":15,"hPadding":30,"vPaddingTablet":15,"hPaddingTablet":30,"vPaddingMobile":15,"hPaddingMobile":30,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderWidth":2,"borderRadius":0,"borderColor":"#0c0c0c","borderHColor":"","color":"#FFFFFF","background":"#0c0c0c","hColor":"#0c0c0c","buttonFontSize":16,"buttonLineHeight":1,"hbackground":"#FFFFFF","buttonFontWeight":"500","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-b15df4cd-0001-417c-a38d-8049e1695140 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">READ MORE</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"ce8510c3-1883-4b6a-9d6c-a2a2497d7b76","topPadding":150,"topPaddingMobile":80,"topPaddingTablet":80,"bottomPadding":0,"bottomPaddingMobile":16,"bottomPaddingTablet":16,"leftPadding":0,"leftPaddingTablet":20,"rightPadding":0,"rightPaddingTablet":40,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/home-banner-background2.png","backgroundPosition":"center center","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-ce8510c3-1883-4b6a-9d6c-a2a2497d7b76 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"b248a8b5-ce54-4148-b6bf-2781f4751322"} -->
    <div class="block-b248a8b5-ce54-4148-b6bf-2781f4751322 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"bottomPadding":150,"topPaddingTablet":0,"bottomPaddingTablet":150,"bottomPaddingMobile":40,"block_id":"4a40c0b2-4c6d-4abf-a2d2-12bb49cf892b","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-4a40c0b2-4c6d-4abf-a2d2-12bb49cf892b"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"402a56ec-c6a4-428c-ab7d-06ccda52af1f","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"700","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-402a56ec-c6a4-428c-ab7d-06ccda52af1f"><h2 class="responsive-heading-title-text">2020</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"02ec79f5-bcf4-4d4d-b0e4-ce84951ec99b","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":40,"headingTitleFontSizeTablet":40,"headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-02ec79f5-bcf4-4d4d-b0e4-ce84951ec99b"><h2 class="responsive-heading-title-text">WINTER</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"675a54fc-da16-47bd-a923-37b756a82e12","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"300","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-675a54fc-da16-47bd-a923-37b756a82e12"><h2 class="responsive-heading-title-text">TRENDS</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"ff275345-1125-465f-b1b4-8da8ffe01b88","label":"READ MORE","link":"#","target":false,"vPadding":15,"hPadding":30,"vPaddingTablet":15,"hPaddingTablet":30,"vPaddingMobile":15,"hPaddingMobile":30,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderWidth":2,"borderRadius":0,"borderColor":"#0c0c0c","borderHColor":"","color":"#FFFFFF","background":"#0c0c0c","hColor":"#0c0c0c","buttonFontSize":16,"buttonLineHeight":1,"hbackground":"#FFFFFF","buttonFontWeight":"500","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-ff275345-1125-465f-b1b4-8da8ffe01b88 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">READ MORE</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"rightMargin":55,"rightMarginTablet":0,"block_id":"09a16090-e67b-4c07-ae7f-ac94243a0ae3","blockBorderStyle":"solid","blockBorderWidth":10,"blockBorderColor":"#7a7a7a","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-09a16090-e67b-4c07-ae7f-ac94243a0ae3"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":136,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/lifestyle-banner3.png" alt="" class="wp-image-136"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"1824c291-c16b-4a65-af40-ce0ff80e1982","topPadding":150,"topPaddingMobile":100,"topPaddingTablet":150,"bottomPadding":0,"bottomPaddingMobile":0,"bottomPaddingTablet":0,"leftPadding":0,"leftPaddingMobile":20,"leftPaddingTablet":20,"rightPadding":0,"rightPaddingMobile":20,"rightPaddingTablet":20,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-1824c291-c16b-4a65-af40-ce0ff80e1982 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"71217dbc-6a24-4815-82c1-b49ef8745be0","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"700","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-71217dbc-6a24-4815-82c1-b49ef8745be0"><h2 class="responsive-heading-title-text">DESIGN YOUR</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"eae17970-b400-49fb-8e37-475bbafbfb4d","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headingTitleFontSize":40,"headingTitleFontSizeTablet":40,"headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-eae17970-b400-49fb-8e37-475bbafbfb4d"><h2 class="responsive-heading-title-text">WARDROBE</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"1e2037ca-48e8-4ae7-b239-40b14be8b63b","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headingTitleFontSize":80,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"300","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-1e2037ca-48e8-4ae7-b239-40b14be8b63b"><h2 class="responsive-heading-title-text">FOR ALL AGES</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":60,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"verticalAlign":"flex-end","block_id":"02de9c64-8d27-46d9-90ec-c08e3b826814"} -->
    <div class="block-02de9c64-8d27-46d9-90ec-c08e3b826814 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"topPadding":400,"bottomPadding":100,"leftPadding":30,"rightPadding":30,"block_id":"bfeb28b7-c1bf-4e74-9c9b-a979e3c6cfaf","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/services-color.jpg","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-bfeb28b7-c1bf-4e74-9c9b-a979e3c6cfaf"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/section {"block_id":"85372520-21b5-4f1f-b757-88fd476cdc87","topPadding":5,"topPaddingMobile":20,"topPaddingTablet":15,"bottomPadding":5,"bottomPaddingMobile":20,"bottomPaddingTablet":15,"leftPadding":5,"leftPaddingMobile":15,"rightPadding":5,"rightPaddingMobile":15,"opacity":35,"backgroundColor":"#0c0c0c","backgroundType":"color"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-85372520-21b5-4f1f-b757-88fd476cdc87 background-type-color alignundefined"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9b69d995-a139-439d-a125-9333da2fe728","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":0,"headingTitleFontSize":24,"headingTitleFontSizeTablet":18,"headingTitleFontWeight":"500","headingTitleLineHeight":1.2,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-9b69d995-a139-439d-a125-9333da2fe728"><h2 class="responsive-heading-title-text">FASHION WEEK</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":400,"bottomPadding":100,"leftPadding":30,"rightPadding":30,"block_id":"c65bf48e-0bc3-4f7f-9e42-4a1fea525d80","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/services-color3.jpg","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c65bf48e-0bc3-4f7f-9e42-4a1fea525d80"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/section {"block_id":"13bf50ce-9182-4ff1-9c9a-fce9e1197d2f","topPadding":5,"topPaddingMobile":20,"topPaddingTablet":15,"bottomPadding":5,"bottomPaddingMobile":20,"bottomPaddingTablet":15,"leftPadding":5,"leftPaddingMobile":15,"rightPadding":5,"rightPaddingMobile":15,"opacity":35,"backgroundColor":"#0c0c0c","backgroundType":"color"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-13bf50ce-9182-4ff1-9c9a-fce9e1197d2f background-type-color alignundefined"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"a97135a3-bd4f-4bd8-bcab-650e74e8232c","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":0,"headingTitleFontSize":24,"headingTitleFontSizeTablet":18,"headingTitleFontWeight":"500","headingTitleLineHeight":1.2,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-a97135a3-bd4f-4bd8-bcab-650e74e8232c"><h2 class="responsive-heading-title-text">MEN\'S CASUAL</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":400,"bottomPadding":100,"leftPadding":30,"rightPadding":30,"block_id":"5d061783-42f6-48f9-b1f1-d27c1b51702b","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/services-color1.jpg","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-5d061783-42f6-48f9-b1f1-d27c1b51702b"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/section {"block_id":"d15f3c3f-a400-482d-a872-8bffb1c90481","topPadding":5,"topPaddingMobile":20,"topPaddingTablet":15,"bottomPadding":5,"bottomPaddingMobile":20,"bottomPaddingTablet":15,"leftPadding":5,"leftPaddingMobile":15,"rightPadding":5,"rightPaddingMobile":15,"opacity":35,"backgroundColor":"#0c0c0c","backgroundType":"color"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-d15f3c3f-a400-482d-a872-8bffb1c90481 background-type-color alignundefined"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"cca6947e-f112-4a63-871c-c8c48ed9fbef","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":0,"headingTitleFontSize":24,"headingTitleFontSizeTablet":18,"headingTitleFontWeight":"500","headingTitleLineHeight":1.2,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-cca6947e-f112-4a63-871c-c8c48ed9fbef"><h2 class="responsive-heading-title-text">BEARD LOOK</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":400,"bottomPadding":100,"leftPadding":30,"rightPadding":30,"block_id":"ecc008fa-78f3-4cba-b242-528539e285da","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/services-color2.jpg","backgroundType":"image"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-ecc008fa-78f3-4cba-b242-528539e285da"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/section {"block_id":"49810cc2-bb23-43d3-ad88-5ed0cc8fad0c","topPadding":5,"topPaddingMobile":20,"topPaddingTablet":15,"bottomPadding":5,"bottomPaddingMobile":20,"bottomPaddingTablet":15,"leftPadding":5,"leftPaddingMobile":15,"leftPaddingTablet":5,"rightPadding":5,"rightPaddingMobile":15,"rightPaddingTablet":5,"opacity":35,"backgroundColor":"#0c0c0c","backgroundType":"color"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-49810cc2-bb23-43d3-ad88-5ed0cc8fad0c background-type-color alignundefined"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"abac0753-7de2-4ea5-943f-40aa0a24b596","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":0,"headingTitleFontSize":24,"headingTitleFontSizeMobile":18,"headingTitleFontSizeTablet":16,"headingTitleFontWeight":"500","headingTitleLineHeight":1.2,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-abac0753-7de2-4ea5-943f-40aa0a24b596"><h2 class="responsive-heading-title-text">GLAMOROUS LOOK</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"25453d96-60f3-4a44-8620-5fd4c2e50707","topPadding":150,"topPaddingMobile":150,"topPaddingTablet":150,"bottomPadding":150,"bottomPaddingMobile":150,"bottomPaddingTablet":150,"leftPadding":0,"leftPaddingMobile":20,"leftPaddingTablet":20,"rightPadding":0,"rightPaddingMobile":20,"rightPaddingTablet":20,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-25453d96-60f3-4a44-8620-5fd4c2e50707 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"102c4523-917c-44a5-97a7-263db9d598df"} -->
    <div class="block-102c4523-917c-44a5-97a7-263db9d598df responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"block_id":"6433dd4d-11a8-4586-a7c0-4cf33d359494","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-6433dd4d-11a8-4586-a7c0-4cf33d359494"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"f98649c1-c927-49f3-89e0-a6d007943af8","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headingTitleFontSize":40,"headingTitleFontSizeTablet":40,"headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-f98649c1-c927-49f3-89e0-a6d007943af8"><h2 class="responsive-heading-title-text">OUR</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9d4cba61-92fd-460a-9547-29fc64bc5d48","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headingTitleFontSize":90,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"300","headingTitleColor":"#0c0c0c","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-9d4cba61-92fd-460a-9547-29fc64bc5d48"><h2 class="responsive-heading-title-text">HAPPY CLIENTS!</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":120,"bottomPadding":120,"leftPadding":40,"rightPadding":40,"topPaddingMobile":20,"bottomPaddingMobile":20,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"99102267-6682-4212-9b40-ca1caf5ff8e5","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#f7f7f7"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-99102267-6682-4212-9b40-ca1caf5ff8e5"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/testimonial {"block_id":"701c209f-f930-4020-b5c0-7b70bb5ec8fc","testimonialBlock":[{"testimonialContent":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.","testimonialTitle":"Designer","testimonialName":"Jane Doe","testimonialImgId":175,"testimonialImgURL":{"id":175,"title":"yoga-jane-doe","filename":"yoga-jane-doe.png","url":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/yoga-jane-doe.png","link":"https://ccreadysites.cyberchimps.com/glifestyle/yoga-jane-doe/","alt":"","author":"17","description":"","caption":"","name":"yoga-jane-doe","status":"inherit","uploadedTo":0,"date":"2020-12-22T10:59:47.000Z","modified":"2020-12-22T10:59:47.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/glifestyle/wp-includes/images/media/default.png","dateFormatted":"December 22, 2020","nonces":{"update":"6567076c36","delete":"d669e1d481","edit":"a879cb4699"},"editLink":"https://ccreadysites.cyberchimps.com/glifestyle/wp-admin/post.php?post=175\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/glifestyle/wp-admin/profile.php","filesizeInBytes":9935,"filesizeHumanReadable":"10 KB","context":"","height":80,"width":80,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/yoga-jane-doe.png","height":80,"width":80,"orientation":"landscape"}},"compat":{"item":"","meta":""}}}],"count":1,"testimonialBackgroundColor":"#f7f7f7","testimonialNameColor":"#0c0c0c","testimonialTitleColor":"#32373c","titleFontSize":14,"titleFontWeight":"500","nameFontSize":16,"nameLineHeight":1.2,"nameFontWeight":"400","contentFontSize":16,"contentFontWeight":"500","contentSpacing":20,"nameSpacing":0,"imageSpacing":15,"imageShape":"circle","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-testimonial-wrapper responsive-block-editor-addons-block-testimonial block-701c209f-f930-4020-b5c0-7b70bb5ec8fc has-1-columns has-medium-gutter"><div class="wp-block-responsive-block-editor-addons-testimonial left-aligned responsive-block-editor-addons-font-size-undefined testimonial-box responsive-block-editor-addons-block-testimonial image-shape-circle"><div class="responsive-block-editor-addons-testimonial-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</div><div class="responsive-block-editor-addons-testimonial-info"><div class="responsive-block-editor-addons-testimonial-inner-block"><div class="responsive-block-editor-addons-testimonial-avatar-wrap"><div class="responsive-block-editor-addons-testimonial-image-wrap"><img class="responsive-block-editor-addons-testimonial-avatar" src="https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/yoga-jane-doe.png" alt="avatar"/></div></div><div class="responsive-block-editor-addons-testimonial-details"><h2 class="responsive-block-editor-addons-testimonial-name">Jane Doe</h2><small class="responsive-block-editor-addons-testimonial-title">Designer</small></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/testimonial --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"91e420e0-d88a-4141-a8a6-0987b3ca024d","topPadding":150,"topPaddingMobile":40,"topPaddingTablet":150,"bottomPadding":150,"bottomPaddingMobile":40,"bottomPaddingTablet":150,"leftPadding":0,"leftPaddingMobile":20,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":20,"rightPaddingTablet":0,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/glifestyle/wp-content/uploads/sites/121/2020/12/footer.jpg","backgroundPosition":"center center","backgroundAttachment":"fixed","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-91e420e0-d88a-4141-a8a6-0987b3ca024d background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"eb8dee4b-57e0-4ed3-aa59-f7bb9d944a9d","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":90,"headingTitleFontSizeTablet":60,"headingTitleFontWeight":"300","headingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-eb8dee4b-57e0-4ed3-aa59-f7bb9d944a9d"><h2 class="responsive-heading-title-text">CONTACT US</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"610d72b8-ac5b-4f9e-8328-4426cae5ee0b","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"headingTitleColor":"#FFFFFF","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.4,"subHeadingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-610d72b8-ac5b-4f9e-8328-4426cae5ee0b"><p class="responsive-heading-desc-text">Address : 123, Main Street, Anytown, ST 12345</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"55646cf3-91d2-4e22-afd2-6137c43b9911","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"headingTitleColor":"#FFFFFF","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.4,"subHeadingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-55646cf3-91d2-4e22-afd2-6137c43b9911"><p class="responsive-heading-desc-text">Email : hello@example.com</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"5a3d3b97-4d38-4884-899c-bad10b37818f","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"headingTitleColor":"#FFFFFF","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.4,"subHeadingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-5a3d3b97-4d38-4884-899c-bad10b37818f"><p class="responsive-heading-desc-text">Contact Number : +123 4567 890</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"align":"center","gap":25,"size":25,"hideLabel":true,"icon_layout":"horizontal","block_id":"f4b8c943-6011-4b79-af62-552c536a5af2"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list horizontal responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-horizontal responsive-block-editor-addons-icon-list__no-label responsive-block-editor-addons-f4b8c943-6011-4b79-af62-552c536a5af2"><div class="responsive-block-editor-addons-icon-wrap-f4b8c943-6011-4b79-af62-552c536a5af2 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"","hideLabel":true,"icon":"facebook-f","icon_color":"#FFFFFF","icon_hover_color":"#a9a9a9","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"faec1d93-6100-41f2-aa63-a8bdcb211e4f"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-faec1d93-6100-41f2-aa63-a8bdcb211e4f"><a target="_self" rel="noopener noreferrer" aria-label="" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-faec1d93-6100-41f2-aa63-a8bdcb211e4f responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 264 512"><path d="M76.7 512V283H0v-91h76.7v-71.7C76.7 42.4 124.3 0 193.8 0c33.3 0 61.9 2.5 70.2 3.6V85h-48.2c-37.8 0-45.1 18-45.1 44.3V192H256l-11.7 91h-73.6v229"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"","hideLabel":true,"icon":"twitter","icon_color":"#FFFFFF","icon_hover_color":"#a9a9a9","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"3b0ee124-d46d-4a48-9cfb-0dbbe6101a32"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-3b0ee124-d46d-4a48-9cfb-0dbbe6101a32"><a target="_self" rel="noopener noreferrer" aria-label="" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-3b0ee124-d46d-4a48-9cfb-0dbbe6101a32 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"","hideLabel":true,"icon":"linkedin-in","icon_color":"#FFFFFF","icon_hover_color":"#a9a9a9","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"cceee75e-9bf2-473f-8f42-c069dfbd48c9"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-cceee75e-9bf2-473f-8f42-c069dfbd48c9"><a target="_self" rel="noopener noreferrer" aria-label="" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-cceee75e-9bf2-473f-8f42-c069dfbd48c9 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448.1 512"><path d="M100.3 448H7.4V148.9h92.9V448zM53.8 108.1C24.1 108.1 0 83.5 0 53.8S24.1 0 53.8 0s53.8 24.1 53.8 53.8-24.1 54.3-53.8 54.3zM448 448h-92.7V302.4c0-34.7-.7-79.2-48.3-79.2-48.3 0-55.7 37.7-55.7 76.7V448h-92.8V148.9h89.1v40.8h1.3c12.4-23.5 42.7-48.3 87.9-48.3 94 0 111.3 61.9 111.3 142.3V448h-.1z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"","hideLabel":true,"icon":"instagram","icon_color":"#FFFFFF","icon_hover_color":"#a9a9a9","label_hover_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"017aba58-786e-41e3-98db-58ceb027897e"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-017aba58-786e-41e3-98db-58ceb027897e"><a target="_self" rel="noopener noreferrer" aria-label="" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-017aba58-786e-41e3-98db-58ceb027897e responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512"><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"","hideLabel":true,"icon":"pinterest-p","icon_color":"#FFFFFF","icon_hover_color":"#a9a9a9","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"1cec7310-f842-4f94-80ec-1b8446cf4c88"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-1cec7310-f842-4f94-80ec-1b8446cf4c88"><a target="_self" rel="noopener noreferrer" aria-label="" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-1cec7310-f842-4f94-80ec-1b8446cf4c88 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"><span class="responsive-block-editor-addons-icon-list__source-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 384 512"><path d="M204 6.5C101.4 6.5 0 74.9 0 185.6 0 256 39.6 296 63.6 296c9.9 0 15.6-27.6 15.6-35.4 0-9.3-23.7-29.1-23.7-67.8 0-80.4 61.2-137.4 140.4-137.4 68.1 0 118.5 38.7 118.5 109.8 0 53.1-21.3 152.7-90.3 152.7-24.9 0-46.2-18-46.2-43.8 0-37.8 26.4-74.4 26.4-113.4 0-66.2-93.9-54.2-93.9 25.8 0 16.8 2.1 35.4 9.6 50.7-13.8 59.4-42 147.9-42 209.1 0 18.9 2.7 37.5 4.5 56.4 3.4 3.8 1.7 3.4 6.9 1.5 50.4-69 48.6-82.5 71.4-172.8 12.3 23.4 44.1 36 69.3 36 106.2 0 153.9-103.5 153.9-196.8C384 71.3 298.2 6.5 204 6.5z"></path></svg></span></span></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Lifestyle', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Blog', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Blog', 'responsive-block-editor-addons' ),
		esc_html__( 'Wellness', 'responsive-block-editor-addons' ),
		esc_html__( 'Fashion', 'responsive-block-editor-addons' ),
		esc_html__( 'Lifestyle', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
