<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_one_page_biz_layout',
	'collection' => array(
		'slug'      => 'one-page-business',
		'label'     => __( 'One Page Business', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"ded82aeb-29dc-4351-a92c-0a077dfbc8a5","innerWidth":600,"topPadding":210,"topPaddingMobile":210,"topPaddingTablet":210,"bottomPadding":210,"bottomPaddingMobile":210,"bottomPaddingTablet":210,"leftPadding":0,"rightPadding":0,"opacity":68,"backgroundImage":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/business-baner.jpg","backgroundPosition":"center center","backgroundImageColor":"#0c0c0c","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-ded82aeb-29dc-4351-a92c-0a077dfbc8a5 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"d645f953-ddbb-41ad-a2ef-7025a3305e98","showSeparator":false,"headSpacing":20,"subheadSpacing":20,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":20,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":20,"separatorSpacingMobile":0,"headingTitleFontSize":40,"headingTitleFontSizeMobile":40,"headingTitleFontSizeTablet":40,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-d645f953-ddbb-41ad-a2ef-7025a3305e98"><h2 class="responsive-heading-title-text">WELCOME TO RESPONSIVE</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/buttons -->
    <div class="wp-block-responsive-block-editor-addons-buttons center tabletAligncenter mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"027e1195-b303-416f-8a87-77ca7f4ded91","label":"Read More","link":"#","target":false,"vPadding":15,"hPadding":30,"vPaddingTablet":15,"hPaddingTablet":30,"vPaddingMobile":15,"hPaddingMobile":30,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#ffffff","background":"#1874cd","hColor":"#ffffff","buttonFontSize":16,"buttonFontSizeTablet":16,"buttonFontSizeMobile":16,"buttonLineHeight":1,"hbackground":"#1657ba","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-027e1195-b303-416f-8a87-77ca7f4ded91 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">Read More</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"957a5b4b-b090-4109-9f36-6ccdb073244a","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"opacity":100,"backgroundColor":"#f9f9f9","backgroundType":"color","align":"full"} -->
    <div id="services" class="responsive-block-editor-addons-block-section-outer-wrap block-957a5b4b-b090-4109-9f36-6ccdb073244a background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"a02139ef-018f-4667-a458-6489fa4c6ee8","showSubHeading":false,"showSeparator":false,"headSpacing":50,"subheadSpacing":0,"separatorSpacing":0,"headSpacingTablet":50,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"headSpacingMobile":50,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"headingTitleFontSize":36,"headingTitleFontSizeMobile":36,"headingTitleFontSizeTablet":36,"headingTitleFontWeight":"700","headingTitleColor":"#333333","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-a02139ef-018f-4667-a458-6489fa4c6ee8"><h2 class="responsive-heading-title-text">SERVICES</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"block_id":"5c90c93d-56ed-4ced-b4e2-7bb5a0c493e6"} -->
    <div class="block-5c90c93d-56ed-4ced-b4e2-7bb5a0c493e6 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"topPaddingTablet":10,"bottomPaddingTablet":10,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"f46dfa8f-a82d-41dc-8e1a-8e9f6fd74b2e","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-f46dfa8f-a82d-41dc-8e1a-8e9f6fd74b2e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"ffa91df7-2886-479c-8481-4abc438c3ccb","classMigrate":true,"resheadingColor":"#000000","ressubheadingColor":"#000000","resheadFontSize":20,"resheadFontSizeMobile":20,"resheadFontSizeTablet":20,"ressubHeadFontSize":16,"ressubHeadFontSizeTablet":16,"ressubHeadFontSizeMobile":16,"ressubHeadFontWeight":"400","resheadSpace":28,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconImage":{"id":122,"title":"technical-support","filename":"technical-support.png","url":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png","link":"https://ccreadysites.cyberchimps.com/gone-page-biz/technical-support/","alt":"","author":"7","description":"","caption":"","name":"technical-support","status":"inherit","uploadedTo":0,"date":"2019-11-11T12:22:48.000Z","modified":"2019-11-11T12:22:48.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-includes/images/media/default.png","dateFormatted":"November 11, 2019","nonces":{"update":"56e56212cc","delete":"de0faf235c","edit":"527436bef3"},"editLink":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-admin/post.php?post=122\u0026action=edit","meta":false,"authorName":"manish","authorLink":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-admin/user-edit.php?user_id=7","filesizeInBytes":4503,"filesizeHumanReadable":"4 KB","context":"","height":128,"width":128,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png","height":128,"width":128,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":94,"imageWidthTablet":55,"imageWidthMobile":79,"resshowPrefix":false,"counterId":"ffa91df7-2886-479c-8481-4abc438c3ccb","contentPadding":20,"opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-ffa91df7-2886-479c-8481-4abc438c3ccb"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Service</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum dummy text ever since.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"topPaddingTablet":10,"bottomPaddingTablet":10,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"ca243fd6-98cf-45b7-8601-0968bb3ee07c","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-ca243fd6-98cf-45b7-8601-0968bb3ee07c"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"ec5b46c3-e698-4a7c-ad93-13cf395a7f4e","classMigrate":true,"resheadingColor":"#000000","ressubheadingColor":"#000000","resheadFontSize":20,"resheadFontSizeMobile":20,"resheadFontSizeTablet":20,"ressubHeadFontSize":16,"ressubHeadFontSizeTablet":16,"ressubHeadFontSizeMobile":16,"ressubHeadFontWeight":"400","resheadSpace":28,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconImage":{"id":122,"title":"technical-support","filename":"technical-support.png","url":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png","link":"https://ccreadysites.cyberchimps.com/gone-page-biz/technical-support/","alt":"","author":"7","description":"","caption":"","name":"technical-support","status":"inherit","uploadedTo":0,"date":"2019-11-11T12:22:48.000Z","modified":"2019-11-11T12:22:48.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-includes/images/media/default.png","dateFormatted":"November 11, 2019","nonces":{"update":"56e56212cc","delete":"de0faf235c","edit":"527436bef3"},"editLink":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-admin/post.php?post=122\u0026action=edit","meta":false,"authorName":"manish","authorLink":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-admin/user-edit.php?user_id=7","filesizeInBytes":4503,"filesizeHumanReadable":"4 KB","context":"","height":128,"width":128,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png","height":128,"width":128,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":94,"imageWidthTablet":55,"imageWidthMobile":79,"resshowPrefix":false,"counterId":"ec5b46c3-e698-4a7c-ad93-13cf395a7f4e","contentPadding":20,"opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-ec5b46c3-e698-4a7c-ad93-13cf395a7f4e"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Service</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum dummy text ever since.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":33.333,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"topPaddingTablet":10,"bottomPaddingTablet":10,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"24530f3c-7551-4707-9edf-a8ba20f777cd","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-24530f3c-7551-4707-9edf-a8ba20f777cd"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"a95efef4-92a5-4352-8a0f-cf2f07031b99","classMigrate":true,"resheadingColor":"#000000","ressubheadingColor":"#000000","resheadFontSize":20,"resheadFontSizeMobile":20,"resheadFontSizeTablet":20,"ressubHeadFontSize":16,"ressubHeadFontSizeTablet":16,"ressubHeadFontSizeMobile":16,"ressubHeadFontWeight":"400","resheadSpace":28,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconImage":{"id":122,"title":"technical-support","filename":"technical-support.png","url":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png","link":"https://ccreadysites.cyberchimps.com/gone-page-biz/technical-support/","alt":"","author":"7","description":"","caption":"","name":"technical-support","status":"inherit","uploadedTo":0,"date":"2019-11-11T12:22:48.000Z","modified":"2019-11-11T12:22:48.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-includes/images/media/default.png","dateFormatted":"November 11, 2019","nonces":{"update":"56e56212cc","delete":"de0faf235c","edit":"527436bef3"},"editLink":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-admin/post.php?post=122\u0026action=edit","meta":false,"authorName":"manish","authorLink":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-admin/user-edit.php?user_id=7","filesizeInBytes":4503,"filesizeHumanReadable":"4 KB","context":"","height":128,"width":128,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png","height":128,"width":128,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":94,"imageWidthTablet":55,"imageWidthMobile":79,"resshowPrefix":false,"counterId":"a95efef4-92a5-4352-8a0f-cf2f07031b99","contentPadding":20,"opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-a95efef4-92a5-4352-8a0f-cf2f07031b99"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/technical-support.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Service</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum dummy text ever since.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"b7501443-8acc-418c-9784-3983fae09982","topPadding":80,"topPaddingMobile":80,"topPaddingTablet":80,"bottomPadding":80,"bottomPaddingMobile":80,"bottomPaddingTablet":80,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"align":"full"} -->
    <div id="about" class="responsive-block-editor-addons-block-section-outer-wrap block-b7501443-8acc-418c-9784-3983fae09982 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"9d84703d-b19c-461e-bc38-1e0bbad47b99"} -->
    <div class="block-9d84703d-b19c-461e-bc38-1e0bbad47b99 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":45,"block_id":"b37f23ba-cbef-4429-bae5-e2803cdc6fdb","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-b37f23ba-cbef-4429-bae5-e2803cdc6fdb"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":109,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/about.jpg" alt="" class="wp-image-109"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":55,"topPadding":0,"bottomPadding":0,"leftPadding":40,"rightPadding":40,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":40,"rightPaddingTablet":40,"topPaddingMobile":20,"bottomPaddingMobile":20,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"20a6e0e8-46c8-47d8-ad67-ef466ffac909","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-20a6e0e8-46c8-47d8-ad67-ef466ffac909"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"55ee9415-a72e-4f6c-9944-63b505306ed2","showSeparator":false,"headSpacing":20,"subheadSpacing":0,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"headingTitleFontSize":36,"headingTitleFontSizeMobile":36,"headingTitleFontSizeTablet":36,"headingTitleFontWeight":"700","headingTitleColor":"#333333","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-55ee9415-a72e-4f6c-9944-63b505306ed2"><h2 class="responsive-heading-title-text">ABOUT</h2><p class="responsive-heading-desc-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"6ed63de2-8317-4469-81db-129484c5732a","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"opacity":76,"backgroundImage":"https://ccreadysites.cyberchimps.com/gone-page-biz/wp-content/uploads/sites/86/2019/11/about11.jpg","backgroundPosition":"center center","backgroundImageColor":"#0c0c0c","backgroundType":"image","align":"full"} -->
    <div id="contact" class="responsive-block-editor-addons-block-section-outer-wrap block-6ed63de2-8317-4469-81db-129484c5732a background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"ee50bcdb-3a0d-4640-8798-ff999225bdb8"} -->
    <div class="block-ee50bcdb-3a0d-4640-8798-ff999225bdb8 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":33.3333,"block_id":"06a90e84-f51a-46de-9b9a-e8c0c28de260","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-06a90e84-f51a-46de-9b9a-e8c0c28de260"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"89240915-e672-488c-981e-f352abce328f","showSubHeading":false,"showSeparator":false,"headSpacing":40,"headSpacingTablet":40,"headSpacingMobile":40,"headingTitleFontSize":21.333,"headingTitleFontSizeMobile":21.333,"headingTitleFontSizeTablet":21.333,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-89240915-e672-488c-981e-f352abce328f"><h4 class="responsive-heading-title-text">Reach Us</h4></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c4712484-b99e-446b-bee9-41d78dab7bd2","showSubHeading":true,"showSeparator":false,"subheadSpacing":40,"subheadSpacingTablet":40,"subheadSpacingMobile":40,"headingTitleFontSize":19.2,"headingTitleFontSizeMobile":19.2,"headingTitleFontSizeTablet":19.2,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleColor":"#ffffff","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-c4712484-b99e-446b-bee9-41d78dab7bd2"><h4 class="responsive-heading-title-text">Location</h4><p class="responsive-heading-desc-text">123, Main street, Anytown ST 12345.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"e14bbab0-f28b-4753-9972-f4feedf06c18","showSubHeading":true,"showSeparator":false,"subheadSpacing":40,"subheadSpacingTablet":40,"subheadSpacingMobile":40,"headingTitleFontSize":19.2,"headingTitleFontSizeMobile":19.2,"headingTitleFontSizeTablet":19.2,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleColor":"#ffffff","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-e14bbab0-f28b-4753-9972-f4feedf06c18"><h4 class="responsive-heading-title-text">Email</h4><p class="responsive-heading-desc-text">info@domain.com</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"b329fc9e-93e4-4ab3-b674-5f11b477f4c4","showSubHeading":true,"showSeparator":false,"headingTitleFontSize":19.2,"headingTitleFontSizeMobile":19.2,"headingTitleFontSizeTablet":19.2,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleColor":"#ffffff","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-b329fc9e-93e4-4ab3-b674-5f11b477f4c4"><h4 class="responsive-heading-title-text">Phone</h4><p class="responsive-heading-desc-text">+123 - 456 - 7890</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0009d8b8-9ff9-44b1-bd0f-e739d5091f9d","showHeading":false,"showSubHeading":true,"showSeparator":false,"subheadSpacing":50,"subheadSpacingTablet":50,"subheadSpacingMobile":50,"headingTitleFontSize":21.333,"headingTitleFontSizeMobile":21.333,"headingTitleFontSizeTablet":21.333,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleColor":"#ffffff","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0009d8b8-9ff9-44b1-bd0f-e739d5091f9d"><p class="responsive-heading-desc-text">+123 - 456 - 7890</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":66.6666,"topPadding":10,"bottomPadding":10,"leftPadding":50,"rightPadding":50,"topPaddingTablet":10,"bottomPaddingTablet":10,"leftPaddingTablet":50,"rightPaddingTablet":52,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"f0a310fc-c5fd-4b5b-9226-045b117e8f40","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":65,"backgroundType":"color","backgroundColor":"#5b5b5b"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-f0a310fc-c5fd-4b5b-9226-045b117e8f40"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:shortcode -->
    [wpforms id="2878" title="false" description="false"]
    <!-- /wp:shortcode --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'One Page Business', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'One Page', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'One Page', 'responsive-block-editor-addons' ),
		esc_html__( 'Single Page', 'responsive-block-editor-addons' ),
		esc_html__( 'Landing Page', 'responsive-block-editor-addons' ),
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
		esc_html__( 'Consulting', 'responsive-block-editor-addons' ),
		esc_html__( 'Startup', 'responsive-block-editor-addons' ),
		esc_html__( 'Company', 'responsive-block-editor-addons' ),
		esc_html__( 'Agency', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
