<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_corporate_lawyer_layout',
	'collection' => array(
		'slug'      => 'corporate-lawyer',
		'label'     => __( 'Corporate Lawyer', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"5125c9f3-308f-4c7a-8e8a-c33f6c03e755","topPadding":230,"topPaddingMobile":150,"topPaddingTablet":200,"bottomPadding":230,"bottomPaddingMobile":150,"bottomPaddingTablet":200,"leftPaddingMobile":40,"rightPaddingMobile":40,"opacity":63,"backgroundImage":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/law-bg.jpg","backgroundPosition":"top center","backgroundAttachment":"fixed","backgroundImageColor":"#020202","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-5125c9f3-308f-4c7a-8e8a-c33f6c03e755 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"71036d9f-7c50-48c6-aa7f-a26545bdc5a7"} -->
    <div class="block-71036d9f-7c50-48c6-aa7f-a26545bdc5a7 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":65,"block_id":"f2ef416d-793c-4343-8429-81ca4053ca87","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-f2ef416d-793c-4343-8429-81ca4053ca87"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c2217a14-47f3-4724-9bbf-43ff0386127d","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":39,"headingTitleFontWeight":"700","headingTitleLineHeight":1.5,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-c2217a14-47f3-4724-9bbf-43ff0386127d"><h2 class="responsive-heading-title-text">CORPORATE LEGAL SERVICES</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left","buttonAlignmentMobile":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAlignleft responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"21852dd9-6e30-4bc3-ba5d-138d11c011df","label":"Learn More","link":"#","target":false,"vPadding":20,"hPadding":40,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":5,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#FFFFFF","background":"#8c2849","hColor":"","buttonFontSize":18,"buttonLineHeight":1,"hbackground":"#b83d64","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-21852dd9-6e30-4bc3-ba5d-138d11c011df responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">Learn More</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":35,"block_id":"636b3ada-f57d-4701-9944-d8b241f27796","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-636b3ada-f57d-4701-9944-d8b241f27796"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:paragraph -->
    <p></p>
    <!-- /wp:paragraph --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"21ca3eb9-672f-4316-b772-ab85f5f0c54c","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-21ca3eb9-672f-4316-b772-ab85f5f0c54c background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"041363d1-0dc9-403f-b058-7a39a274037c","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":80,"headSpacingTablet":80,"headSpacingMobile":80,"headingTitleFontSize":39,"headingTitleFontWeight":"700"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-041363d1-0dc9-403f-b058-7a39a274037c"><h2 class="responsive-heading-title-text">ABOUT US</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"a4d2044d-6ee1-4e54-8a8e-562f26b5a694"} -->
    <div class="block-a4d2044d-6ee1-4e54-8a8e-562f26b5a694 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"leftPaddingMobile":30,"rightPaddingMobile":30,"block_id":"568962ce-9f2f-4b44-a6af-d0034aac3e31","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-568962ce-9f2f-4b44-a6af-d0034aac3e31"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"cb716074-f8cb-43a5-9c6c-e739c6482aa9","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-cb716074-f8cb-43a5-9c6c-e739c6482aa9"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.<br><br>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"block_id":"cff873e1-cc0e-44db-9412-e4ee121f78ed","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-cff873e1-cc0e-44db-9412-e4ee121f78ed"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"3847960a-8403-4825-97b9-84cf1e8b4963","classMigrate":true,"imgiconPosition":"left","ressubHeadFontWeight":"400","resheadSpace":20,"source_type":"image","resseperatorStyle":"none","iconRightMargin":20,"iconImage":{"id":106,"title":"vision","filename":"vision.jpg","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision.jpg","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/vision/","alt":"","author":"17","description":"","caption":"","name":"vision","status":"inherit","uploadedTo":0,"date":"2020-12-24T07:25:50.000Z","modified":"2020-12-24T07:25:50.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 24, 2020","nonces":{"update":"63960f7151","delete":"850b475fa5","edit":"607876992e"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=106\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":4344,"filesizeHumanReadable":"4 KB","context":"","height":200,"width":200,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision-150x150.jpg","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision.jpg","height":200,"width":200,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":192.5,"imageWidthTablet":128,"imageWidthMobile":119,"stack":"mobile","resshowPrefix":false,"counterId":"3847960a-8403-4825-97b9-84cf1e8b4963","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-3847960a-8403-4825-97b9-84cf1e8b4963"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/vision.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Our Vision</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:spacer {"height":70} -->
    <div style="height:70px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"f61975dc-2806-43ae-b095-aaea9a1004c3","classMigrate":true,"imgiconPosition":"left","ressubHeadFontWeight":"400","resheadSpace":20,"source_type":"image","resseperatorStyle":"none","iconRightMargin":20,"iconImage":{"id":107,"title":"mission","filename":"mission.jpg","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission.jpg","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/mission/","alt":"","author":"17","description":"","caption":"","name":"mission","status":"inherit","uploadedTo":0,"date":"2020-12-24T07:25:54.000Z","modified":"2020-12-24T07:25:54.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 24, 2020","nonces":{"update":"9999b52980","delete":"9f4c6db2c5","edit":"32eb353323"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=107\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":5496,"filesizeHumanReadable":"5 KB","context":"","height":200,"width":200,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission-150x150.jpg","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission.jpg","height":200,"width":200,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":192.5,"imageWidthTablet":128,"imageWidthMobile":119,"stack":"mobile","resshowPrefix":false,"counterId":"f61975dc-2806-43ae-b095-aaea9a1004c3","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-f61975dc-2806-43ae-b095-aaea9a1004c3"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/mission.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Our Mission</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:spacer {"height":60} -->
    <div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"23fd7cd2-0e24-4a9f-9785-8063dd05f6ab","topPadding":90,"topPaddingMobile":50,"topPaddingTablet":50,"bottomPadding":90,"bottomPaddingMobile":50,"bottomPaddingTablet":50,"leftPadding":0,"leftPaddingMobile":30,"leftPaddingTablet":30,"rightPadding":0,"rightPaddingMobile":30,"rightPaddingTablet":30,"opacity":100,"backgroundColor":"#8c2849","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-23fd7cd2-0e24-4a9f-9785-8063dd05f6ab background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"dbef5ee7-96a1-43d3-b77f-3b9ef4b70a7a","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":80,"headSpacingTablet":80,"headSpacingMobile":80,"headingTitleFontSize":39,"headingTitleFontSizeMobile":40,"headingTitleFontWeight":"700","headingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-dbef5ee7-96a1-43d3-b77f-3b9ef4b70a7a"><h2 class="responsive-heading-title-text">EXPERT ATTORNEYS</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"20ac5aea-5a1a-4a97-a517-41433d943cc2"} -->
    <div class="block-20ac5aea-5a1a-4a97-a517-41433d943cc2 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"width":33.33,"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":15,"rightMargin":15,"topMargin":15,"bottomMargin":15,"topPaddingTablet":20,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":30,"bottomPaddingMobile":30,"leftPaddingMobile":0,"rightPaddingMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":30,"bottomMarginMobile":0,"block_id":"4fa8de8d-7646-4c94-8877-e30d0f2005e7","boxShadowColor":"#0f0f2b","boxShadowBlur":50,"hoverboxShadowColor":"#0f0f2b","hoverboxShadowBlur":50,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-4fa8de8d-7646-4c94-8877-e30d0f2005e7"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":134,"width":300,"height":300,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large is-resized"><img src="http://testccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer3.jpg" alt="" class="wp-image-134" width="300" height="300"/></figure>
    <!-- /wp:image -->
    <!-- wp:spacer {"height":5} -->
    <div style="height:5px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"8896f1f8-de1f-4545-a2b8-f94ad8b48648","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":15,"subHeadingTitleFontWeight":"300","subHeadingTitleLineHeight":2.1,"subHeadingTitleColor":"#353535"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-8896f1f8-de1f-4545-a2b8-f94ad8b48648"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"bc45afd0-ac3b-4133-a951-c7f9e98a4969","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontFamily":"Montserrat","headingTitleFontSize":17,"headingTitleColor":"#000000","subHeadingTitleFontFamily":"Montserrat","subHeadingTitleFontSize":14,"subHeadingTitleFontWeight":"700","subHeadingTitleColor":"#555555"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-bc45afd0-ac3b-4133-a951-c7f9e98a4969"><h2 class="responsive-heading-title-text">SMITH DOE</h2><p class="responsive-heading-desc-text">CEO/Founder</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":33.33,"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":15,"rightMargin":15,"topMargin":15,"bottomMargin":15,"topPaddingTablet":20,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":30,"bottomPaddingMobile":30,"leftPaddingMobile":0,"rightPaddingMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":30,"bottomMarginMobile":0,"block_id":"3000c58d-b50d-4ee5-acab-7aa3987f2a7d","boxShadowColor":"#0f0f2b","boxShadowBlur":50,"hoverboxShadowColor":"#0f0f2b","hoverboxShadowBlur":50,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-3000c58d-b50d-4ee5-acab-7aa3987f2a7d"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":137,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer2.jpg" alt="" class="wp-image-137"/></figure>
    <!-- /wp:image -->
    <!-- wp:spacer {"height":5} -->
    <div style="height:5px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"3cf709e1-5988-41eb-86fc-398ebad825af","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":15,"subHeadingTitleFontWeight":"300","subHeadingTitleLineHeight":2.1,"subHeadingTitleColor":"#353535"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-3cf709e1-5988-41eb-86fc-398ebad825af"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"16777dfd-02e0-428f-9ad3-8d1a7591f0fd","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontFamily":"Montserrat","headingTitleFontSize":17,"headingTitleColor":"#000000","subHeadingTitleFontFamily":"Montserrat","subHeadingTitleFontSize":14,"subHeadingTitleFontWeight":"700","subHeadingTitleColor":"#555555"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-16777dfd-02e0-428f-9ad3-8d1a7591f0fd"><h2 class="responsive-heading-title-text">JOHN DOE</h2><p class="responsive-heading-desc-text">Employment Lawyer</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":33.33,"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":15,"rightMargin":15,"topMargin":15,"bottomMargin":15,"topPaddingTablet":20,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":30,"bottomPaddingMobile":30,"leftPaddingMobile":0,"rightPaddingMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":30,"bottomMarginMobile":0,"block_id":"cb4ea175-0fe6-427e-aee1-8819b88c93cc","boxShadowColor":"#0f0f2b","boxShadowBlur":50,"hoverboxShadowColor":"#0f0f2b","hoverboxShadowBlur":50,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-cb4ea175-0fe6-427e-aee1-8819b88c93cc"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":139,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer1.jpg" alt="" class="wp-image-139"/></figure>
    <!-- /wp:image -->
    <!-- wp:spacer {"height":5} -->
    <div style="height:5px" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"df7a0857-2b70-43ba-b09b-66fedf6c2807","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subheadSpacing":20,"subheadSpacingTablet":20,"subheadSpacingMobile":20,"subHeadingTitleFontSize":15,"subHeadingTitleFontWeight":"300","subHeadingTitleLineHeight":2.1,"subHeadingTitleColor":"#353535"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-df7a0857-2b70-43ba-b09b-66fedf6c2807"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"3dae5f2d-a8c8-4632-9733-09e245a0a2e8","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontFamily":"Montserrat","headingTitleFontSize":17,"headingTitleColor":"#000000","subHeadingTitleFontFamily":"Montserrat","subHeadingTitleFontSize":14,"subHeadingTitleFontWeight":"700","subHeadingTitleColor":"#555555"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-3dae5f2d-a8c8-4632-9733-09e245a0a2e8"><h2 class="responsive-heading-title-text">RICHARD ROE</h2><p class="responsive-heading-desc-text">Family Lawyer</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"5fdceb25-43aa-4e35-ad72-3dd6e4e3df70","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"leftPadding":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingTablet":0,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-5fdceb25-43aa-4e35-ad72-3dd6e4e3df70 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"30af5ecf-8a35-46ad-b217-59cb4fecf622","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":80,"headSpacingTablet":80,"headSpacingMobile":80,"headingTitleFontSize":39,"headingTitleFontWeight":"700"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-30af5ecf-8a35-46ad-b217-59cb4fecf622"><h2 class="responsive-heading-title-text">OUR SERVICES</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"ea1921a1-62f1-425c-ba9c-1ea9fbb9c318"} -->
    <div class="block-ea1921a1-62f1-425c-ba9c-1ea9fbb9c318 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"topPadding":0,"bottomPadding":90,"leftPadding":10,"rightPadding":10,"block_id":"ec6f92e4-377b-46c8-9b43-0e4276b85437","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-ec6f92e4-377b-46c8-9b43-0e4276b85437"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"7c86d55b-1859-48b9-9ed6-0c8365450a62","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-7c86d55b-1859-48b9-9ed6-0c8365450a62"><h2 class="responsive-heading-title-text">BANK AND FINANCIAL</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":90,"leftPadding":10,"rightPadding":10,"block_id":"7e241c08-c06d-48f3-8050-e8d73cfe17c7","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-7e241c08-c06d-48f3-8050-e8d73cfe17c7"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"4a68e52e-8f04-4d3b-8349-e1ba45fab4ad","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-4a68e52e-8f04-4d3b-8349-e1ba45fab4ad"><h2 class="responsive-heading-title-text">EMPLOYMENT LAW</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":90,"leftPadding":10,"rightPadding":10,"block_id":"93c9ad73-33ad-4607-8069-dc6dca4a368c","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-93c9ad73-33ad-4607-8069-dc6dca4a368c"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"daafbd22-1b90-45cb-9ad4-5423e7b8b79a","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-daafbd22-1b90-45cb-9ad4-5423e7b8b79a"><h2 class="responsive-heading-title-text">CAR ACCIDENT</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":90,"leftPadding":10,"rightPadding":10,"block_id":"3484929e-0dd5-456a-850f-f90f826d3149","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-3484929e-0dd5-456a-850f-f90f826d3149"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"71777fc4-2e97-4cf4-85e0-9c3b25c4abdf","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-71777fc4-2e97-4cf4-85e0-9c3b25c4abdf"><h2 class="responsive-heading-title-text">PERSONAL INJURY</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns -->
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"51bc0e70-1e5e-4b7d-b4f4-c5a40a783bd2"} -->
    <div class="block-51bc0e70-1e5e-4b7d-b4f4-c5a40a783bd2 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"topPadding":0,"bottomPadding":0,"leftPadding":10,"rightPadding":10,"bottomPaddingMobile":90,"block_id":"ca611b9f-8cda-43e3-8269-cc74a806925a","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-ca611b9f-8cda-43e3-8269-cc74a806925a"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"f9c82587-c844-48a1-914d-ad77b88b1d16","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-f9c82587-c844-48a1-914d-ad77b88b1d16"><h2 class="responsive-heading-title-text">PROPERTY DISPUTE</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":10,"rightPadding":10,"bottomPaddingMobile":90,"block_id":"d81e9927-e9ae-46a9-b488-39da360df5ca","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-d81e9927-e9ae-46a9-b488-39da360df5ca"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"e83ec588-e7ae-4cf6-bb92-80f872301d62","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-e83ec588-e7ae-4cf6-bb92-80f872301d62"><h2 class="responsive-heading-title-text">HOME OWNERSHIP</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":10,"rightPadding":10,"bottomPaddingMobile":90,"block_id":"611e7743-d623-453c-9df9-67cae5349e44","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-611e7743-d623-453c-9df9-67cae5349e44"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"4898d49a-cfd0-48bd-82e0-828ca1ba61e3","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-4898d49a-cfd0-48bd-82e0-828ca1ba61e3"><h2 class="responsive-heading-title-text">INSURANCE CLAIM</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":10,"rightPadding":10,"block_id":"94ca7122-27d5-4fda-a0e6-5bc5351dee9c","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-94ca7122-27d5-4fda-a0e6-5bc5351dee9c"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"fa83c66e-1aef-4175-909f-4f8c40b2e5ee","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontWeight":"700","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-fa83c66e-1aef-4175-909f-4f8c40b2e5ee"><h2 class="responsive-heading-title-text">FAMILY LAW</h2><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"ffb255cd-22dc-43cb-b9f1-87da044e06a0","topPadding":90,"topPaddingMobile":35,"topPaddingTablet":60,"bottomPadding":90,"bottomPaddingMobile":35,"bottomPaddingTablet":60,"leftPadding":0,"leftPaddingMobile":20,"leftPaddingTablet":30,"rightPadding":0,"rightPaddingMobile":20,"rightPaddingTablet":30,"opacity":100,"backgroundColor":"#f7f7f7","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-ffb255cd-22dc-43cb-b9f1-87da044e06a0 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9905b2d2-9d57-47c4-9334-3dc1b868b59e","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":39,"headingTitleFontWeight":"700"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-9905b2d2-9d57-47c4-9334-3dc1b868b59e"><h2 class="responsive-heading-title-text">CLIENT TESTIMONIALS</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"09db9436-00b2-4c57-83ad-41fd888dec46"} -->
    <div class="block-09db9436-00b2-4c57-83ad-41fd888dec46 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"width":20,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"block_id":"dacddd40-6d2b-4267-b678-4853e73aa1e1","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-dacddd40-6d2b-4267-b678-4853e73aa1e1"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"91aeb39a-4c0f-4ec8-862a-b439bca9d164","classMigrate":true,"source_type":"image","resseperatorStyle":"none","iconImage":{"id":372,"title":"real-rechard (1)","filename":"real-rechard-1.jpg","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/real-rechard-1.jpg","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/real-rechard-1/","alt":"","author":"17","description":"","caption":"","name":"real-rechard-1","status":"inherit","uploadedTo":0,"date":"2020-12-31T09:53:55.000Z","modified":"2020-12-31T09:53:55.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 31, 2020","nonces":{"update":"0dd89f1181","delete":"30bda39b4c","edit":"a0fe5b5433"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=372\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":8763,"filesizeHumanReadable":"9 KB","context":"","height":250,"width":250,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/real-rechard-1-150x150.jpg","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/real-rechard-1.jpg","height":250,"width":250,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":136,"imageWidthTablet":141.6,"imageWidthMobile":208,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"91aeb39a-4c0f-4ec8-862a-b439bca9d164","boxBackgroundColor":"#f7f7f7","resImageBorderStyle":"solid","resImageBorderRadius":100,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-91aeb39a-4c0f-4ec8-862a-b439bca9d164"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/real-rechard-1.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":30,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"block_id":"cacd3969-fdd9-49ab-bd31-60f7f24369f1","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-cacd3969-fdd9-49ab-bd31-60f7f24369f1"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"3aded414-4211-47fc-8068-4dc59542bc41","classMigrate":true,"resheadingAlign":"left","ressubheadingColor":"#6b6b6b","icon":"quote-right","resIconSize":26,"ressubHeadFontSize":16,"ressubHeadFontWeight":"400","ressubHeadSpace":28,"resseperatorStyle":"none","iconTopMargin":0,"iconBottomMargin":28,"resshowPrefix":false,"resshowTitle":false,"counterId":"3aded414-4211-47fc-8068-4dc59542bc41","boxBackgroundColor":"#f7f7f7","icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-3aded414-4211-47fc-8068-4dc59542bc41"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M464 32H336c-26.5 0-48 21.5-48 48v128c0 26.5 21.5 48 48 48h80v64c0 35.3-28.7 64-64 64h-8c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24h8c88.4 0 160-71.6 160-160V80c0-26.5-21.5-48-48-48zm-288 0H48C21.5 32 0 53.5 0 80v128c0 26.5 21.5 48 48 48h80v64c0 35.3-28.7 64-64 64h-8c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24h8c88.4 0 160-71.6 160-160V80c0-26.5-21.5-48-48-48z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"ed866236-f987-4452-8b63-33b9f0bdb46d","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":30,"headingTitleFontSize":19,"headingTitleFontWeight":"700","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-ed866236-f987-4452-8b63-33b9f0bdb46d"><h2 class="responsive-heading-title-text">Richard Roe</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":20,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"block_id":"5ba465fb-2905-4ec1-befd-53c3e089836f","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-5ba465fb-2905-4ec1-befd-53c3e089836f"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"ccaf86b8-04df-4992-82de-b4db206b326a","classMigrate":true,"source_type":"image","resseperatorStyle":"none","iconImage":{"id":268,"title":"john-doe","filename":"john-doe.jpg","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/john-doe.jpg","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/john-doe/","alt":"","author":"17","description":"","caption":"","name":"john-doe","status":"inherit","uploadedTo":0,"date":"2020-12-25T04:54:36.000Z","modified":"2020-12-25T04:54:36.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 25, 2020","nonces":{"update":"8a628304db","delete":"baf88410e0","edit":"850142ce41"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=268\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":3774,"filesizeHumanReadable":"4 KB","context":"","height":136,"width":136,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/john-doe.jpg","height":136,"width":136,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":136,"imageWidthTablet":141.6,"imageWidthMobile":208,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"ccaf86b8-04df-4992-82de-b4db206b326a","boxBackgroundColor":"#f7f7f7","resImageBorderStyle":"solid","resImageBorderRadius":100,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-ccaf86b8-04df-4992-82de-b4db206b326a"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/john-doe.jpg" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"width":30,"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"block_id":"266bdb44-c6e2-48f4-91be-720c32b54b59","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-266bdb44-c6e2-48f4-91be-720c32b54b59"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"f36ca107-075b-49d3-a348-daabc1e51b7b","classMigrate":true,"resheadingAlign":"left","ressubheadingColor":"#6b6b6b","icon":"quote-right","resIconSize":26,"ressubHeadFontSize":16,"ressubHeadFontWeight":"400","ressubHeadSpace":28,"resseperatorStyle":"none","iconTopMargin":0,"iconBottomMargin":28,"resshowPrefix":false,"resshowTitle":false,"counterId":"f36ca107-075b-49d3-a348-daabc1e51b7b","boxBackgroundColor":"#f7f7f7","icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-f36ca107-075b-49d3-a348-daabc1e51b7b"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M464 32H336c-26.5 0-48 21.5-48 48v128c0 26.5 21.5 48 48 48h80v64c0 35.3-28.7 64-64 64h-8c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24h8c88.4 0 160-71.6 160-160V80c0-26.5-21.5-48-48-48zm-288 0H48C21.5 32 0 53.5 0 80v128c0 26.5 21.5 48 48 48h80v64c0 35.3-28.7 64-64 64h-8c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24h8c88.4 0 160-71.6 160-160V80c0-26.5-21.5-48-48-48z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"f11c511f-0af5-4bf3-97ac-cdc4326f2941","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":30,"headingTitleFontSize":19,"headingTitleFontWeight":"700","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-f11c511f-0af5-4bf3-97ac-cdc4326f2941"><h2 class="responsive-heading-title-text">John Jones</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    <!-- wp:responsive-block-editor-addons/section {"block_id":"66136779-9baf-4086-a5b7-f286713d70dc","topPadding":90,"topPaddingMobile":90,"topPaddingTablet":90,"bottomPadding":90,"bottomPaddingMobile":90,"bottomPaddingTablet":90,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-66136779-9baf-4086-a5b7-f286713d70dc background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"02a219f9-6deb-46f4-a8d9-2651d5f397c0"} -->
    <div class="block-02a219f9-6deb-46f4-a8d9-2651d5f397c0 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":20,"bottomPadding":20,"leftPadding":20,"rightPadding":20,"block_id":"d6e25326-a382-4cd7-ab65-b10e195b2583","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-d6e25326-a382-4cd7-ab65-b10e195b2583"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"5c860e14-9354-4bc4-895e-0cf90706c53d","classMigrate":true,"resheadingAlign":"left","ressubHeadFontSize":16,"ressubHeadFontWeight":"400","ressubHeadSpace":15,"source_type":"image","resseperatorStyle":"none","iconBottomMargin":15,"iconImage":{"id":35,"title":"lawyer","filename":"lawyer.png","url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer.png","link":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/lawyer/","alt":"","author":"17","description":"","caption":"","name":"lawyer","status":"inherit","uploadedTo":0,"date":"2020-12-24T05:48:06.000Z","modified":"2020-12-24T05:48:06.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-includes/images/media/default.png","dateFormatted":"December 24, 2020","nonces":{"update":"f226798875","delete":"743d2f72e7","edit":"69068bf337"},"editLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/post.php?post=35\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-admin/profile.php","filesizeInBytes":3079,"filesizeHumanReadable":"3 KB","context":"","height":62,"width":211,"orientation":"landscape","sizes":{"thumbnail":{"height":62,"width":150,"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer-150x62.png","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer.png","height":62,"width":211,"orientation":"landscape"}},"compat":{"item":"","meta":""},"mediaStates":"Logo"},"imageWidth":210,"imageWidthTablet":211,"imageWidthMobile":211,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"5c860e14-9354-4bc4-895e-0cf90706c53d","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-5c860e14-9354-4bc4-895e-0cf90706c53d"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gcorporate-lawyer/wp-content/uploads/sites/122/2020/12/lawyer.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"b859c3b4-8caa-4e62-91c2-afad3375bd89","showHeading":false,"showSeparator":false,"seperatorStyle":"none","subHeadingTitleLineHeight":1.4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-b859c3b4-8caa-4e62-91c2-afad3375bd89"><p class="responsive-heading-desc-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text, make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    <!-- wp:responsive-block-editor-addons/column {"topPadding":20,"bottomPadding":20,"leftPadding":50,"rightPadding":20,"leftPaddingMobile":20,"block_id":"1c24c204-5746-4dee-a0e2-796e4712490e","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-1c24c204-5746-4dee-a0e2-796e4712490e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"e0ca0197-4fcc-4336-8207-b2cf21b25242","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":12,"headSpacingTablet":12,"headSpacingMobile":12,"headingTitleFontSize":21.33,"headingTitleFontWeight":"700","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-e0ca0197-4fcc-4336-8207-b2cf21b25242"><h4 class="responsive-heading-title-text">Quick Links</h4></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    <!-- wp:responsive-block-editor-addons/icons-list {"gap":0,"inner_gap":0,"labelFontWeight":"400","labelFontSize":16,"labelFontLineHeight":1.6,"block_id":"8e934bb3-1c83-4b5a-863a-288deee11ddf"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-8e934bb3-1c83-4b5a-863a-288deee11ddf"><div class="responsive-block-editor-addons-icon-wrap-8e934bb3-1c83-4b5a-863a-288deee11ddf responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Home","icon":"","label_color":"","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"514371e6-5491-4bcb-866d-e154187a96a1"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-514371e6-5491-4bcb-866d-e154187a96a1"><a target="_self" rel="noopener noreferrer" aria-label="Home" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-514371e6-5491-4bcb-866d-e154187a96a1 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Home</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Services","icon":"","disableLink":false,"block_id":"ac2bfafe-5bff-4af4-b85a-6c865e805527"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-ac2bfafe-5bff-4af4-b85a-6c865e805527"><a target="_self" rel="noopener noreferrer" aria-label="Services" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-ac2bfafe-5bff-4af4-b85a-6c865e805527 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Services</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"About","icon":"","disableLink":false,"block_id":"8e7890f9-8dd8-42dc-b1e6-3d995426e0c3"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-8e7890f9-8dd8-42dc-b1e6-3d995426e0c3"><a target="_self" rel="noopener noreferrer" aria-label="About" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-8e7890f9-8dd8-42dc-b1e6-3d995426e0c3 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">About</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Blog","icon":"","disableLink":false,"block_id":"7d04c3e2-e53d-41e2-a0cd-07ace91c2cd6"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-7d04c3e2-e53d-41e2-a0cd-07ace91c2cd6"><a target="_self" rel="noopener noreferrer" aria-label="Blog" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-7d04c3e2-e53d-41e2-a0cd-07ace91c2cd6 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Blog</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Contact","icon":"","disableLink":false,"block_id":"7f0ce4a8-3972-48ff-ae24-17b9344d3d41"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-7f0ce4a8-3972-48ff-ae24-17b9344d3d41"><a target="_self" rel="noopener noreferrer" aria-label="Contact" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-7f0ce4a8-3972-48ff-ae24-17b9344d3d41 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Contact</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --> 
    <!-- wp:responsive-block-editor-addons/column {"topPadding":20,"bottomPadding":20,"leftPadding":50,"rightPadding":20,"leftPaddingTablet":20,"leftPaddingMobile":20,"block_id":"c4a6317e-4d85-4728-a639-5877a06040a3","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c4a6317e-4d85-4728-a639-5877a06040a3"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"3e554b71-cefc-4fda-8ea5-819db9c76ca1","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":12,"headSpacingTablet":12,"headSpacingMobile":12,"headingTitleFontSize":21.33,"headingTitleFontWeight":"700","headingTag":"h4","level":4,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-3e554b71-cefc-4fda-8ea5-819db9c76ca1"><h4 class="responsive-heading-title-text">Contact Us</h4></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --> 
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"3359405a-fe01-4605-8d91-3e08f1fedabe","classMigrate":true,"alignment":"left","icon":"map-marker-alt","imgiconPosition":"left","resIconSize":30,"resheadFontSize":18,"ressubHeadFontSize":14,"ressubHeadFontWeight":"400","resheadSpace":2,"resseperatorStyle":"none","resprefixSpace":0,"iconRightMargin":5,"stack":"mobile","resshowPrefix":false,"counterId":"3359405a-fe01-4605-8d91-3e08f1fedabe","sepSpace":0,"icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-3359405a-fe01-4605-8d91-3e08f1fedabe"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 384 512"><path d="M172.268 501.67C26.97 291.031 0 269.413 0 192 0 85.961 85.961 0 192 0s192 85.961 192 192c0 77.413-26.97 99.031-172.268 309.67-9.535 13.774-29.93 13.773-39.464 0zM192 272c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Address</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">123, Main Street, Anytown, ST 12345.</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"490c38dd-c4e1-4629-a2f0-dd9f929b94fc","classMigrate":true,"alignment":"left","icon":"envelope","imgiconPosition":"left","resIconSize":30,"resheadFontSize":18,"ressubHeadFontSize":14,"ressubHeadFontWeight":"400","resheadSpace":2,"resseperatorStyle":"none","resprefixSpace":0,"iconRightMargin":5,"stack":"mobile","resshowPrefix":false,"counterId":"490c38dd-c4e1-4629-a2f0-dd9f929b94fc","sepSpace":0,"icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-490c38dd-c4e1-4629-a2f0-dd9f929b94fc"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Send Mail</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">info@example.com</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block -->
    <!-- wp:responsive-block-editor-addons/info-block {"block_id":"ee905a08-e6a0-4435-8aff-56b2ad687fbf","classMigrate":true,"alignment":"left","icon":"phone","imgiconPosition":"left","resIconSize":30,"resheadFontSize":18,"ressubHeadFontSize":14,"ressubHeadFontWeight":"400","resheadSpace":2,"resseperatorStyle":"none","resprefixSpace":0,"iconRightMargin":5,"stack":"mobile","resshowPrefix":false,"counterId":"ee905a08-e6a0-4435-8aff-56b2ad687fbf","sepSpace":0,"icon_color":"#8c2849","icon_hcolor":"#8c2849","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-ee905a08-e6a0-4435-8aff-56b2ad687fbf"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-icon responsive-block-editor-addons-infobox-icon-left responsive-block-editor-addons-infobox-left responsive-block-editor-addons-infobox-stacked-mobile responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-image-valign-tablet-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-icon-wrap"><span class="responsive-block-editor-addons-ifb-icon"><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512"><path d="M493.4 24.6l-104-24c-11.3-2.6-22.9 3.3-27.5 13.9l-48 112c-4.2 9.8-1.4 21.3 6.9 28l60.6 49.6c-36 76.7-98.9 140.5-177.2 177.2l-49.6-60.6c-6.8-8.3-18.2-11.1-28-6.9l-112 48C3.9 366.5-2 378.1.6 389.4l24 104C27.1 504.2 36.7 512 48 512c256.1 0 464-207.5 464-464 0-11.2-7.7-20.9-18.6-23.4z"></path></svg></span></div></div><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Call Us</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">123-456-7890</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Corporate Lawyer', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
		esc_html__( 'Consulting', 'responsive-block-editor-addons' ),
		esc_html__( 'Law', 'responsive-block-editor-addons' ),
		esc_html__( 'Professional', 'responsive-block-editor-addons' ),
		esc_html__( 'Corporate Lawyer', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
