<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_construction_layout',
	'collection' => array(
		'slug'      => 'construction',
		'label'     => __( 'Construction', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"3d9f3514-b69a-42b1-96ed-19197d64b5c2","topPadding":150,"topPaddingMobile":0,"topPaddingTablet":0,"bottomPadding":170,"bottomPaddingMobile":0,"bottomPaddingTablet":0,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":230,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/construction_02.jpg","backgroundPosition":"center right","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-3d9f3514-b69a-42b1-96ed-19197d64b5c2 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"stack":"tablet","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"2add867e-b558-4b58-9512-28b987b74858"} -->
    <div class="block-2add867e-b558-4b58-9512-28b987b74858 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-tablet responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":52,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":30,"bottomPaddingTablet":30,"leftPaddingTablet":30,"rightPaddingTablet":30,"topPaddingMobile":20,"bottomPaddingMobile":20,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"bf31a344-6a59-4a5f-ba75-f14278c84f03","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-bf31a344-6a59-4a5f-ba75-f14278c84f03"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"67368a7a-5ad1-4aff-9cbc-76e47cf27871","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":70,"headingTitleFontSizeMobile":42,"headingTitleLineHeight":1.3,"headingTitleColor":"#FFFFFF","subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-67368a7a-5ad1-4aff-9cbc-76e47cf27871"><h2 class="responsive-heading-title-text">Innovating since 1965</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"0fd77a24-2a8a-416d-8db5-e355273de3a3","label":"Read More","link":"#","target":false,"vPadding":20,"hPadding":40,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":50,"borderStyle":"none","borderColor":"","borderHColor":"","color":"","background":"#ffdd00","hColor":"#FFFFFF","buttonFontSize":18,"buttonLineHeight":1,"hbackground":"#002240","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-0fd77a24-2a8a-416d-8db5-e355273de3a3 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">Read More</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":48,"block_id":"04f0336b-bd57-44bc-97fa-5098f97f7ab1","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-04f0336b-bd57-44bc-97fa-5098f97f7ab1"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"08563d9c-567d-4e91-9dec-fd567b7f69e6","topPadding":0,"topPaddingMobile":0,"topPaddingTablet":0,"bottomPadding":0,"bottomPaddingMobile":0,"bottomPaddingTablet":0,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/construction_04.jpg","backgroundPosition":"center left","backgroundSize":"auto","backgroundAttachment":"fixed","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-08563d9c-567d-4e91-9dec-fd567b7f69e6 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"b071ac01-7e64-4356-8893-f658809b67ac"} -->
    <div class="block-b071ac01-7e64-4356-8893-f658809b67ac responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":80,"bottomPadding":80,"rightPadding":0,"topPaddingTablet":30,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":20,"bottomPaddingMobile":20,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"c1daac31-57cf-4291-a43e-43bbf2bec837","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c1daac31-57cf-4291-a43e-43bbf2bec837"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":40,"sizeSlug":"large","linkDestination":"none"} -->
    <figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cons-about1-1.jpg" alt="" class="wp-image-40"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":60,"bottomPadding":60,"leftPadding":60,"rightPadding":60,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":40,"block_id":"7e9ad921-ac20-4696-a5c3-913d4d475e7e","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-7e9ad921-ac20-4696-a5c3-913d4d475e7e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0004e2eb-9fb5-4cf1-a9c6-bc0105727605","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":26,"headingTitleFontWeight":"700","subHeadingTitleLineHeight":1.6,"headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0004e2eb-9fb5-4cf1-a9c6-bc0105727605"><h2 class="responsive-heading-title-text">We Are a group of Passionate Architects</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"aca2ea71-c63a-4451-b9b1-b61a9e1dc314","label":"Read More","link":"#","target":false,"vPadding":20,"hPadding":40,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":50,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#FFFFFF","background":"#002240","hColor":"#333333","buttonFontSize":18,"buttonLineHeight":1,"hbackground":"#ffdd00","backgroundType":"color"} -->
    <div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-aca2ea71-c63a-4451-b9b1-b61a9e1dc314 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><div class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper"><a class="responsive-block-editor-addons-button__link_child not-inherited-from-theme" href="#">Read More</a></div></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"de613f03-377b-4383-9744-0c7c5597b75a","topPadding":80,"topPaddingMobile":80,"topPaddingTablet":80,"bottomPadding":80,"bottomPaddingMobile":80,"bottomPaddingTablet":80,"leftPadding":0,"leftPaddingMobile":20,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":20,"rightPaddingTablet":0,"opacity":100,"backgroundColor":"#f7f7f7","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-de613f03-377b-4383-9744-0c7c5597b75a background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"db3fa6fa-506e-4d73-a10e-b775cbeaa207","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":26,"headingTitleFontWeight":"700"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-db3fa6fa-506e-4d73-a10e-b775cbeaa207"><h2 class="responsive-heading-title-text">Our Services</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"e4174396-edb8-4044-99b2-2f4d6ca997d1"} -->
    <div class="block-e4174396-edb8-4044-99b2-2f4d6ca997d1 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"block_id":"28e8e401-113c-4ae4-b051-069d2305616a","hoverboxShadowColor":"#cacaca","hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-28e8e401-113c-4ae4-b051-069d2305616a"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"bf9f66aa-f965-4ed0-ba7d-12b8ee9eb376","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":51,"title":"con-icon4","filename":"con-icon4.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon4.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon4/","alt":"","author":"17","description":"","caption":"","name":"con-icon4","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:53.000Z","modified":"2020-11-10T05:30:53.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"b54c017c95","delete":"394deca699","edit":"ba2df08952"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=51\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":4923,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon4.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"bf9f66aa-f965-4ed0-ba7d-12b8ee9eb376","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-bf9f66aa-f965-4ed0-ba7d-12b8ee9eb376"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon4.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Heavy Foundation</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"block_id":"5065e0dc-4ef8-4408-9a24-892f5700b870","hoverboxShadowColor":"#cacaca","hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-5065e0dc-4ef8-4408-9a24-892f5700b870"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"c7f075e9-56de-47d5-b638-8c79320303dd","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":50,"title":"con-icon3","filename":"con-icon3.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon3.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon3/","alt":"","author":"17","description":"","caption":"","name":"con-icon3","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:51.000Z","modified":"2020-11-10T05:30:51.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"2539aacd2f","delete":"feefeb11d9","edit":"a2345907f4"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=50\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":5288,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon3.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"c7f075e9-56de-47d5-b638-8c79320303dd","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-c7f075e9-56de-47d5-b638-8c79320303dd"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon3.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Blue Print Model</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"block_id":"faf7a49b-7b65-423a-a93c-84e34ec0c9c3","hoverboxShadowColor":"#cacaca","hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-faf7a49b-7b65-423a-a93c-84e34ec0c9c3"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"5aa29e23-5169-4ec5-959e-975d0f25388f","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":49,"title":"con-icon2","filename":"con-icon2.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon2.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon2/","alt":"","author":"17","description":"","caption":"","name":"con-icon2","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:49.000Z","modified":"2020-11-10T05:30:49.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"070308f01f","delete":"26da640202","edit":"b05c1f95af"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=49\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":4664,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon2.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"5aa29e23-5169-4ec5-959e-975d0f25388f","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-5aa29e23-5169-4ec5-959e-975d0f25388f"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon2.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Sustainable Model</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":0,"block_id":"a215e6e3-95fe-4645-b35c-169e18c7cd6a","hoverboxShadowColor":"#cacaca","hoverboxShadowBlur":4,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-a215e6e3-95fe-4645-b35c-169e18c7cd6a"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"eee93ae4-eb4f-453f-b0ab-24a4000f780a","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":52,"title":"con-icon1","filename":"con-icon1.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon1.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon1/","alt":"","author":"17","description":"","caption":"","name":"con-icon1","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:54.000Z","modified":"2020-11-10T05:30:54.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"0425f48f36","delete":"c1117e4d53","edit":"38fb2b4fd2"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=52\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":5219,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon1.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"eee93ae4-eb4f-453f-b0ab-24a4000f780a","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-eee93ae4-eb4f-453f-b0ab-24a4000f780a"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon1.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Safety Assurance</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"4c251681-0c18-4650-a1e3-25ea545c9243","topPadding":80,"topPaddingMobile":80,"topPaddingTablet":80,"bottomPadding":80,"bottomPaddingMobile":80,"bottomPaddingTablet":80,"leftPadding":0,"rightPadding":0,"opacity":100,"backgroundColor":"#002240","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-4c251681-0c18-4650-a1e3-25ea545c9243 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"850c5f72-2ed8-40a7-8d97-2083241c32ab","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":42,"headingTitleColor":"#FFFFFF"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-850c5f72-2ed8-40a7-8d97-2083241c32ab"><h2 class="responsive-heading-title-text">Portfolio</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/gallery-masonry {"align":"","lightbox":true,"gridSize":"lrg"} -->
    <div class="wp-block-responsive-block-editor-addons-gallery-masonry"><div class="responsive-block-editor-addons-gallery has-no-alignment has-caption-style-dark has-gutter has-lightbox"><ul class="has-grid-lrg has-gutter-15 has-gutter-mobile-15"><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_08-1.jpg" alt="" data-id="395" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_08-1-2/" class="wp-image-395"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_10-1.jpg" alt="" data-id="396" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_10-1-2/" class="wp-image-396"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/construction_12-1.jpg" alt="" data-id="73" data-link="https://ccreadysites.cyberchimps.com/gconstruction/construction_12-1/" class="wp-image-73"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_20-1.jpg" alt="" data-id="401" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_20-1-2/" class="wp-image-401"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_17-1.jpg" alt="" data-id="398" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_17-1-2/" class="wp-image-398"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_19-1.jpg" alt="" data-id="400" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_19-1-2/" class="wp-image-400"/></figure></li></ul></div></div>
    <!-- /wp:responsive-block-editor-addons/gallery-masonry --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"4bac7624-44bf-47f5-9330-740b96cf462d","topPadding":80,"topPaddingMobile":80,"topPaddingTablet":80,"bottomPadding":80,"bottomPaddingMobile":80,"bottomPaddingTablet":80,"leftPadding":0,"leftPaddingMobile":30,"rightPadding":0,"rightPaddingMobile":30,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-4bac7624-44bf-47f5-9330-740b96cf462d background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"d33f88d8-3462-45be-a37d-5b8590f7c8a2","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":42} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-d33f88d8-3462-45be-a37d-5b8590f7c8a2"><h2 class="responsive-heading-title-text">Testimonials</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"a955fc54-f737-454a-8620-e5a07c6387f1"} -->
    <div class="block-a955fc54-f737-454a-8620-e5a07c6387f1 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":70,"bottomPadding":70,"leftPadding":35,"rightPadding":35,"rightMargin":16,"bottomPaddingMobile":70,"rightMarginMobile":0,"block_id":"1ab47f44-db64-44bc-9b43-80f84b937afd","blockBorderRadius":5,"boxShadowColor":"#e1dede","boxShadowBlur":10,"hoverboxShadowColor":"#c0c0c0","hoverboxShadowBlur":35,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"none"} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-1ab47f44-db64-44bc-9b43-80f84b937afd"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/testimonial {"block_id":"cf64a468-f15b-4817-86f5-96139ef25a38","testimonialBlock":[{"testimonialContent":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​","testimonialTitle":"CEO","testimonialName":"Jane Doe","testimonialImgId":83,"testimonialImgURL":{"id":83,"title":"yoga-marysmith","filename":"yoga-marysmith.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yoga-marysmith.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/yoga-marysmith/","alt":"","author":"17","description":"","caption":"","name":"yoga-marysmith","status":"inherit","uploadedTo":0,"date":"2020-11-10T06:19:24.000Z","modified":"2020-11-10T06:19:24.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"5a9fcb0223","delete":"e787e70681","edit":"b129b04d72"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=83\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":7684,"filesizeHumanReadable":"8 KB","context":"","height":80,"width":80,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yoga-marysmith.png","height":80,"width":80,"orientation":"landscape"}},"compat":{"item":"","meta":""}}}],"count":1,"gutter":"no","testimonialBackgroundColor":"#FFFFFF","testimonialTextColor":"#000000","testimonialNameColor":"#000000","testimonialTitleColor":"#aaaaaa","titleFontSize":14,"titleLineHeight":1.4,"titleFontWeight":"500","nameFontSize":16,"nameLineHeight":1.4,"nameFontWeight":"400","contentFontSize":14,"contentFontWeight":"500","padding":0,"paddingTablet":0,"paddingMobile":0,"contentSpacing":20,"imageSpacing":15,"imageShape":"circle","boxShadowColor":"","boxShadowPosition":"","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":1} -->
    <div class="wp-block-responsive-block-editor-addons-testimonial-wrapper responsive-block-editor-addons-block-testimonial block-cf64a468-f15b-4817-86f5-96139ef25a38 has-1-columns has-no-gutter"><div class="wp-block-responsive-block-editor-addons-testimonial left-aligned responsive-block-editor-addons-font-size-undefined testimonial-box responsive-block-editor-addons-block-testimonial image-shape-circle"><div class="responsive-block-editor-addons-testimonial-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​</div><div class="responsive-block-editor-addons-testimonial-info"><div class="responsive-block-editor-addons-testimonial-inner-block"><div class="responsive-block-editor-addons-testimonial-avatar-wrap"><div class="responsive-block-editor-addons-testimonial-image-wrap"><img class="responsive-block-editor-addons-testimonial-avatar" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yoga-marysmith.png" alt="avatar"/></div></div><div class="responsive-block-editor-addons-testimonial-details"><h2 class="responsive-block-editor-addons-testimonial-name">Jane Doe</h2><small class="responsive-block-editor-addons-testimonial-title">CEO</small></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/testimonial --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":70,"bottomPadding":70,"leftPadding":35,"rightPadding":35,"leftMargin":16,"topMargin":0,"bottomPaddingMobile":70,"leftMarginMobile":0,"topMarginMobile":25,"block_id":"7af8f852-4aa5-4158-bb9d-3a1f55d19930","blockBorderRadius":5,"boxShadowColor":"#e1dede","boxShadowBlur":10,"hoverboxShadowColor":"#c0c0c0","hoverboxShadowBlur":35,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-7af8f852-4aa5-4158-bb9d-3a1f55d19930"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/testimonial {"block_id":"e4d21cff-13bc-487c-a458-7d0480be4a66","testimonialBlock":[{"testimonialContent":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​","testimonialTitle":"Architecture","testimonialName":"John Doe","testimonialImgId":84,"testimonialImgURL":{"id":84,"title":"yogarichard-roe","filename":"yogarichard-roe.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yogarichard-roe.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/yogarichard-roe/","alt":"","author":"17","description":"","caption":"","name":"yogarichard-roe","status":"inherit","uploadedTo":0,"date":"2020-11-10T06:19:51.000Z","modified":"2020-11-10T06:19:51.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"5c1428712d","delete":"4ee6b30c95","edit":"9bb827ae50"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=84\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":7085,"filesizeHumanReadable":"7 KB","context":"","height":80,"width":80,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yogarichard-roe.png","height":80,"width":80,"orientation":"landscape"}},"compat":{"item":"","meta":""}}}],"count":1,"gutter":"no","testimonialBackgroundColor":"#FFFFFF","testimonialTextColor":"#000000","testimonialNameColor":"#000000","testimonialTitleColor":"#aaaaaa","titleFontSize":14,"titleLineHeight":1.4,"titleFontWeight":"500","nameFontSize":16,"nameLineHeight":1.4,"nameFontWeight":"400","contentFontSize":14,"contentFontWeight":"500","padding":0,"paddingTablet":0,"paddingMobile":0,"contentSpacing":20,"imageSpacing":15,"imageShape":"circle","boxShadowColor":"","boxShadowPosition":"","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":1} -->
    <div class="wp-block-responsive-block-editor-addons-testimonial-wrapper responsive-block-editor-addons-block-testimonial block-e4d21cff-13bc-487c-a458-7d0480be4a66 has-1-columns has-no-gutter"><div class="wp-block-responsive-block-editor-addons-testimonial left-aligned responsive-block-editor-addons-font-size-undefined testimonial-box responsive-block-editor-addons-block-testimonial image-shape-circle"><div class="responsive-block-editor-addons-testimonial-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​</div><div class="responsive-block-editor-addons-testimonial-info"><div class="responsive-block-editor-addons-testimonial-inner-block"><div class="responsive-block-editor-addons-testimonial-avatar-wrap"><div class="responsive-block-editor-addons-testimonial-image-wrap"><img class="responsive-block-editor-addons-testimonial-avatar" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yogarichard-roe.png" alt="avatar"/></div></div><div class="responsive-block-editor-addons-testimonial-details"><h2 class="responsive-block-editor-addons-testimonial-name">John Doe</h2><small class="responsive-block-editor-addons-testimonial-title">Architecture</small></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/testimonial --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"e99c5233-0b90-4680-a2ee-b5cc22913aa7","topPadding":80,"topPaddingMobile":40,"topPaddingTablet":40,"bottomPadding":80,"bottomPaddingMobile":40,"bottomPaddingTablet":40,"leftPadding":0,"leftPaddingMobile":0,"leftPaddingTablet":0,"rightPadding":0,"rightPaddingMobile":0,"rightPaddingTablet":0,"opacity":100,"backgroundColor":"#002240","backgroundType":"color","boxShadowColor":"#ffdd00","boxShadowVOffset":-1.5,"align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-e99c5233-0b90-4680-a2ee-b5cc22913aa7 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"51d70952-bd17-41d3-a4e1-b40692304ad0"} -->
    <div class="block-51d70952-bd17-41d3-a4e1-b40692304ad0 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"bottomMarginMobile":30,"block_id":"b0a45ee7-515e-4493-82a8-b58e001e2c11","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-b0a45ee7-515e-4493-82a8-b58e001e2c11"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"655c2be5-6d96-474f-8a42-db9cec9cb80d","classMigrate":true,"resheadingAlign":"left","ressubheadingColor":"#FFFFFF","ressubHeadFontSize":14,"ressubHeadFontWeight":"500","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":95,"title":"cont-logo-white","filename":"cont-logo-white.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/cont-logo-white/","alt":"","author":"17","description":"","caption":"","name":"cont-logo-white","status":"inherit","uploadedTo":0,"date":"2020-11-10T06:49:30.000Z","modified":"2020-11-10T06:49:30.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"da90a26a45","delete":"00ff8d0b56","edit":"c89ed11068"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=95\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":1929,"filesizeHumanReadable":"2 KB","context":"","height":26,"width":185,"orientation":"landscape","sizes":{"thumbnail":{"height":26,"width":150,"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white-150x26.png","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white.png","height":26,"width":185,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":185,"resshowPrefix":false,"resshowTitle":false,"counterId":"655c2be5-6d96-474f-8a42-db9cec9cb80d","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-655c2be5-6d96-474f-8a42-db9cec9cb80d"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"bottomMarginMobile":30,"block_id":"6f4b5d87-4cd2-469a-b456-1a1a3f9878f2","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-6f4b5d87-4cd2-469a-b456-1a1a3f9878f2"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"8f45bbf9-8048-4bf5-90c6-67225d3900ad","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":18,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-8f45bbf9-8048-4bf5-90c6-67225d3900ad"><h2 class="responsive-heading-title-text">Quick Links</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"gap":0,"inner_gap":0,"labelFontWeight":"500","labelFontSize":14,"labelFontLineHeight":1.6,"block_id":"6585c0a6-3360-4cc9-9614-fa18abc2d7c6"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-6585c0a6-3360-4cc9-9614-fa18abc2d7c6"><div class="responsive-block-editor-addons-icon-wrap-6585c0a6-3360-4cc9-9614-fa18abc2d7c6 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Home","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"9d4deda1-4f64-4371-8ff1-2255862566b1"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-9d4deda1-4f64-4371-8ff1-2255862566b1"><a target="_self" rel="noopener noreferrer" aria-label="Home" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-9d4deda1-4f64-4371-8ff1-2255862566b1 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Home</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"About","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"7ce08efd-33ac-4a75-b1b2-0b5d8e6e8791"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-7ce08efd-33ac-4a75-b1b2-0b5d8e6e8791"><a target="_self" rel="noopener noreferrer" aria-label="About" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-7ce08efd-33ac-4a75-b1b2-0b5d8e6e8791 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">About</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Blog","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"1089fddf-a6d3-4809-8bb4-d3fe8ded1345"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-1089fddf-a6d3-4809-8bb4-d3fe8ded1345"><a target="_self" rel="noopener noreferrer" aria-label="Blog" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-1089fddf-a6d3-4809-8bb4-d3fe8ded1345 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Blog</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Contact","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"b3a28acb-2c34-4642-bc1f-56d384272d62"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-b3a28acb-2c34-4642-bc1f-56d384272d62"><a target="_self" rel="noopener noreferrer" aria-label="Contact" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-b3a28acb-2c34-4642-bc1f-56d384272d62 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Contact</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":30,"rightPaddingTablet":10,"bottomMarginMobile":30,"block_id":"3de9a8ae-f626-4494-b74b-f19192457cc9","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-3de9a8ae-f626-4494-b74b-f19192457cc9"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"a1ecc9fd-214d-449a-8395-0750919e7e3b","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":18,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-a1ecc9fd-214d-449a-8395-0750919e7e3b"><h2 class="responsive-heading-title-text">Contact Us</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"gap":20,"inner_gap":0,"labelFontWeight":"500","labelFontSize":14,"labelFontLineHeight":1.6,"block_id":"d5a6afd3-c0d0-4d2a-9427-b6e42e4a972a"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-d5a6afd3-c0d0-4d2a-9427-b6e42e4a972a"><div class="responsive-block-editor-addons-icon-wrap-d5a6afd3-c0d0-4d2a-9427-b6e42e4a972a responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"123, Main street, Anytown ST 12345.","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"a088147e-74c3-4eee-aad9-e33ea1c17624"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-a088147e-74c3-4eee-aad9-e33ea1c17624"><div class="responsive-block-editor-addons-icon-a088147e-74c3-4eee-aad9-e33ea1c17624 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">123, Main street, Anytown ST 12345.</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"+123-456-7890","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"3d640a97-069c-4776-a6d9-cbcc3e4bf162"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-3d640a97-069c-4776-a6d9-cbcc3e4bf162"><div class="responsive-block-editor-addons-icon-3d640a97-069c-4776-a6d9-cbcc3e4bf162 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">+123-456-7890</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"block_id":"28b490d5-75a3-4f99-920e-118e47d012e0","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-28b490d5-75a3-4f99-920e-118e47d012e0"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c7ce8da5-6239-4cb4-bc03-94bc42f80ab0","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":18,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-c7ce8da5-6239-4cb4-bc03-94bc42f80ab0"><h2 class="responsive-heading-title-text">Get A Quote</h2></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:shortcode -->
    [wpforms id="383" title="false" description="false"]
    <!-- /wp:shortcode --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Construction', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Real Estate', 'responsive-block-editor-addons' ),
		esc_html__( 'Construction', 'responsive-block-editor-addons' ),
		esc_html__( 'Consulting', 'responsive-block-editor-addons' ),
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
