<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_restaurant_menu_layout',
	'collection' => array(
		'slug'      => 'restaurant-menu',
		'label'     => __( 'Restaurant Menu', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"9d3cbc39-6c27-48ff-bed5-005fa8955f07","topPadding":0,"topPaddingMobile":50,"bottomPadding":0,"bottomPaddingMobile":50,"leftPadding":0,"leftPaddingMobile":0,"rightPadding":0,"rightPaddingMobile":0,"opacity":100,"backgroundColor":"#fff0dc","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-9d3cbc39-6c27-48ff-bed5-005fa8955f07 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"verticalAlign":"center","block_id":"5a64d279-6acd-4c73-8856-136f1c35ce97"} -->
    <div class="block-5a64d279-6acd-4c73-8856-136f1c35ce97 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":25,"block_id":"0ee33847-0dfc-48b3-a40d-d860f1e23a92","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-0ee33847-0dfc-48b3-a40d-d860f1e23a92"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"36af610a-3f55-47b1-b7f9-f054966a5ed8","showSubHeading":false,"showSeparator":false,"headSpacing":0,"headSpacingTablet":0,"headSpacingMobile":0,"headingTitleFontSize":62,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":50,"headingTitleColor":"#000000","headingTag":"h1","level":1,"headingAlignment":"left","headingAlignmentTablet":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-36af610a-3f55-47b1-b7f9-f054966a5ed8"><h1 class="responsive-heading-title-text">MENUS</h1></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"width":75,"block_id":"4b136d3b-b25a-4a97-b45d-0eaa64ded425","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-4b136d3b-b25a-4a97-b45d-0eaa64ded425"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":499,"sizeSlug":"full","linkDestination":"none"} -->
    <figure class="wp-block-image size-full"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/plates11.png" alt="" class="wp-image-499"/></figure>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"025eec9e-5862-4db2-ad15-6b6ff9fbec65","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":60,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/rest-menu-bg.jpg","backgroundPosition":"center center","backgroundAttachment":"fixed","backgroundColor":"#ffffff","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-025eec9e-5862-4db2-ad15-6b6ff9fbec65 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0c4c2b7a-127e-4194-b016-3ce7995d255b","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":50,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":30,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0c4c2b7a-127e-4194-b016-3ce7995d255b"><h3 class="responsive-heading-title-text">Starter</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"e713b8fc-922a-467a-8bab-ebd1c3f090f8"} -->
    <div class="block-e713b8fc-922a-467a-8bab-ebd1c3f090f8 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"c4893b36-6891-4843-9057-183e640c6523","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-c4893b36-6891-4843-9057-183e640c6523"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"cc9f4172-6e46-4207-aa02-ad0d4e75a809","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-cc9f4172-6e46-4207-aa02-ad0d4e75a809"><h3 class="responsive-heading-title-text">Smoked Salmon</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"2c2be013-3dc3-48c5-8c98-cd7d270f6b9f","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-2c2be013-3dc3-48c5-8c98-cd7d270f6b9f"><p class="responsive-heading-desc-text">$10.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"2b30ea61-fd3e-4193-87d0-8bc5fb718b06","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-2b30ea61-fd3e-4193-87d0-8bc5fb718b06"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"37bede8b-f867-477a-a263-2ca77aa8b7d3","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-37bede8b-f867-477a-a263-2ca77aa8b7d3"><h3 class="responsive-heading-title-text">Chilli Prawns</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"4ffbb2a9-1b41-493c-9b7f-89fde76cdf85","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-4ffbb2a9-1b41-493c-9b7f-89fde76cdf85"><p class="responsive-heading-desc-text">$15.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"e1015383-d89b-4aab-920d-9c53eb562e99","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-e1015383-d89b-4aab-920d-9c53eb562e99"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"64692649-e69a-4cde-876e-63bd236998de","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-64692649-e69a-4cde-876e-63bd236998de"><h3 class="responsive-heading-title-text">BBQ Kabab</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"48f0085c-9321-4400-94dc-75a779c1f056","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-48f0085c-9321-4400-94dc-75a779c1f056"><p class="responsive-heading-desc-text">$20.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"d20df231-04b7-4e07-b7e7-58c94d5f0de2"} -->
    <div class="block-d20df231-04b7-4e07-b7e7-58c94d5f0de2 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"9205b3e9-3c31-4e00-89e1-35e32e6d279b","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-9205b3e9-3c31-4e00-89e1-35e32e6d279b"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0fc53902-e6bc-4dff-a344-1a23ede00128","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0fc53902-e6bc-4dff-a344-1a23ede00128"><h3 class="responsive-heading-title-text">Manchurian</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"2cc53bc5-a335-4fa5-8953-53e0feadbc52","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-2cc53bc5-a335-4fa5-8953-53e0feadbc52"><p class="responsive-heading-desc-text">$12.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"26e04880-65e1-4bdb-8819-b1391d01b7bc","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-26e04880-65e1-4bdb-8819-b1391d01b7bc"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"da1c6cd1-dcbe-43a1-a2c1-57c90258536f","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-da1c6cd1-dcbe-43a1-a2c1-57c90258536f"><h3 class="responsive-heading-title-text">Seekh Kabab</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c4518664-31c7-4c9c-9b37-c8ae7ceb5a0d","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-c4518664-31c7-4c9c-9b37-c8ae7ceb5a0d"><p class="responsive-heading-desc-text">$10.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"7f647f34-35ca-4ff7-9047-80881b6269da","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-7f647f34-35ca-4ff7-9047-80881b6269da"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"0f938ac5-a122-464f-a241-16167db06613","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-0f938ac5-a122-464f-a241-16167db06613"><h3 class="responsive-heading-title-text">Fish Kabab Toasted</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"4d487ba0-b3c3-49c6-ab2f-65c416af33ff","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-4d487ba0-b3c3-49c6-ab2f-65c416af33ff"><p class="responsive-heading-desc-text">$15.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"55c8406c-02e9-40a4-9368-c87ca4680183","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":80,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/rest-menu-bg.jpg","backgroundPosition":"center center","backgroundAttachment":"fixed","backgroundImageColor":"#fff0dc","backgroundColor":"#fff0dc","backgroundType":"image","imagePositionTab":"tablet","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-55c8406c-02e9-40a4-9368-c87ca4680183 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9ddfca77-00d3-4d0c-85d3-3c4421b06a58","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":50,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":30,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-9ddfca77-00d3-4d0c-85d3-3c4421b06a58"><h3 class="responsive-heading-title-text">Main</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"ecea413b-96e0-4fc5-82da-8f632feb9344"} -->
    <div class="block-ecea413b-96e0-4fc5-82da-8f632feb9344 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"7e883c09-73db-4804-8d8f-10e17553c468","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-7e883c09-73db-4804-8d8f-10e17553c468"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c7b51fe5-dede-488f-ab70-bfccacdf0b7f","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-c7b51fe5-dede-488f-ab70-bfccacdf0b7f"><h3 class="responsive-heading-title-text">Chicken Stew</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"12489a08-c3af-4ed3-b895-a77de4b9cbc8","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-12489a08-c3af-4ed3-b895-a77de4b9cbc8"><p class="responsive-heading-desc-text">$30.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"5cecff75-fe96-4465-9014-964c3047d488","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-5cecff75-fe96-4465-9014-964c3047d488"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"2a18517a-2dd7-4a1e-ad15-05de2866c823","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-2a18517a-2dd7-4a1e-ad15-05de2866c823"><h3 class="responsive-heading-title-text">Grand Aioli</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"ca7fd239-d1e6-4fb7-ba1f-b11b1b3d67e0","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-ca7fd239-d1e6-4fb7-ba1f-b11b1b3d67e0"><p class="responsive-heading-desc-text">$35.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"2f503813-86b8-438f-94d0-f38b9350cde3","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-2f503813-86b8-438f-94d0-f38b9350cde3"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c0fedcc7-042d-423e-948f-63ef49943cc2","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-c0fedcc7-042d-423e-948f-63ef49943cc2"><h3 class="responsive-heading-title-text">Special Fish Curry</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"643740c7-5b2d-4af4-955d-1cec192be14a","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-643740c7-5b2d-4af4-955d-1cec192be14a"><p class="responsive-heading-desc-text">$20.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"20d3a742-a7b1-4e5c-a05e-a306243bc8eb"} -->
    <div class="block-20d3a742-a7b1-4e5c-a05e-a306243bc8eb responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"e93936e6-7267-40c3-b14e-e1a2179730c5","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-e93936e6-7267-40c3-b14e-e1a2179730c5"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"2b6b600b-ea0a-4f99-b64d-64ec014ec6f7","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-2b6b600b-ea0a-4f99-b64d-64ec014ec6f7"><h3 class="responsive-heading-title-text">Herb-Crusted Cauliflower</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"cb5b83c2-ead5-46a0-b058-53705cd9ed33","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-cb5b83c2-ead5-46a0-b058-53705cd9ed33"><p class="responsive-heading-desc-text">$25.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"1f204ef2-601a-4d87-ba89-9fe71c734c17","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-1f204ef2-601a-4d87-ba89-9fe71c734c17"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"dbc19a5b-cf21-4820-9011-8c3734f79975","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-dbc19a5b-cf21-4820-9011-8c3734f79975"><h3 class="responsive-heading-title-text">Crabs Curry</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"74bd5995-198f-41c7-8b75-03d3e321d0e6","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-74bd5995-198f-41c7-8b75-03d3e321d0e6"><p class="responsive-heading-desc-text">$30.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"a1be262c-d8dc-440b-8d43-91816af60d89","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-a1be262c-d8dc-440b-8d43-91816af60d89"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"735efe65-fc1d-4ef3-85d7-c26b09704119","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-735efe65-fc1d-4ef3-85d7-c26b09704119"><h3 class="responsive-heading-title-text">Creamed Corn</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"00683757-e145-44d6-8f79-b9a0b01aa78e","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-00683757-e145-44d6-8f79-b9a0b01aa78e"><p class="responsive-heading-desc-text">$40.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"27154ac3-d970-42ad-801a-89449a747a29","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":80,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/dessert-10.png","backgroundPosition":"center center","backgroundAttachment":"fixed","backgroundImageColor":"#fff7fc","backgroundColor":"#ffffff","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-27154ac3-d970-42ad-801a-89449a747a29 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"115361cc-c56b-4dda-905b-2df253f239c2","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":50,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":30,"subheadSpacingMobile":0,"headingTitleFontSize":30,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-115361cc-c56b-4dda-905b-2df253f239c2"><h3 class="responsive-heading-title-text">Desserts</h3></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"2575ae0c-c451-4e67-8212-372b0abfd0c7"} -->
    <div class="block-2575ae0c-c451-4e67-8212-372b0abfd0c7 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"4e7d6cb4-dd49-4bb5-b0a4-f3d21c4d5e6c","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-4e7d6cb4-dd49-4bb5-b0a4-f3d21c4d5e6c"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"291477b7-13e7-4cf3-afdb-f039481f68ba","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-291477b7-13e7-4cf3-afdb-f039481f68ba"><h3 class="responsive-heading-title-text">Chocolate Macarons</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"e4151822-644e-48a9-8093-117d63c08354","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-e4151822-644e-48a9-8093-117d63c08354"><p class="responsive-heading-desc-text">$30.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"5cc8e6af-06b2-4deb-919f-5b778f55eef8","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-5cc8e6af-06b2-4deb-919f-5b778f55eef8"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"45304952-2475-4679-921a-abfef9346a8f","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-45304952-2475-4679-921a-abfef9346a8f"><h3 class="responsive-heading-title-text">Marshmallow Cookies</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"048b660f-4c8e-4080-a2de-bfe44907a140","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-048b660f-4c8e-4080-a2de-bfe44907a140"><p class="responsive-heading-desc-text">$35.50</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"3e2d4320-f20c-4934-9128-d766d7347f3e","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-3e2d4320-f20c-4934-9128-d766d7347f3e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"dc73f31e-10f3-4d79-b7ed-7cb6756ae481","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-dc73f31e-10f3-4d79-b7ed-7cb6756ae481"><h3 class="responsive-heading-title-text">Easy Apple Crumble</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9f5abba0-442f-49ab-9c6f-91a7205bcd9d","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-9f5abba0-442f-49ab-9c6f-91a7205bcd9d"><p class="responsive-heading-desc-text">$20.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns -->
    
    <!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"60467758-d18b-40dd-90ef-47bc27eb258a"} -->
    <div class="block-60467758-d18b-40dd-90ef-47bc27eb258a responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"df488578-9878-4217-9fe3-6136439fc5f7","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-df488578-9878-4217-9fe3-6136439fc5f7"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"8c26d489-f25d-4d2b-9e3b-b84d5967c4f8","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-8c26d489-f25d-4d2b-9e3b-b84d5967c4f8"><h3 class="responsive-heading-title-text">Lemon Blueberry Cake</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"6918485c-c37d-4a26-ab38-814a963559b8","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-6918485c-c37d-4a26-ab38-814a963559b8"><p class="responsive-heading-desc-text">$25.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"39b755a4-c07b-40c0-b825-47d5c450bcdf","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-39b755a4-c07b-40c0-b825-47d5c450bcdf"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"207ad869-41a4-4f26-bb56-24f1db50089d","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-207ad869-41a4-4f26-bb56-24f1db50089d"><h3 class="responsive-heading-title-text">Honey Pie</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"82d7bc8c-c3e8-46e8-a48c-1b9f3f5bf242","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-82d7bc8c-c3e8-46e8-a48c-1b9f3f5bf242"><p class="responsive-heading-desc-text">$30.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":30,"rightPadding":30,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"block_id":"41053a95-34cf-4b14-83ec-fad4e3e5915c","boxShadowColor":"#e4e4e4","boxShadowBlur":6,"hoverboxShadowColor":"#e4e4e4","hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-41053a95-34cf-4b14-83ec-fad4e3e5915c"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"53b01cfa-e1bc-4be4-a9d3-1f6e54caaf6f","showSubHeading":true,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":20,"headingTitleFontWeight":"700","headingTitleLineHeight":1.25,"headingTitleColor":"#000000","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#000000","headingTag":"h3","level":3,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-53b01cfa-e1bc-4be4-a9d3-1f6e54caaf6f"><h3 class="responsive-heading-title-text">Easy Eton Mess</h3><p class="responsive-heading-desc-text"><em>Lorem Ipsum&nbsp;is simply dummy text of the printing and typesetting industry.</em></p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"63002f34-7253-4434-97e2-a5194aee0ef4","showHeading":false,"showSeparator":false,"subheadSpacing":0,"subheadSpacingTablet":0,"subheadSpacingMobile":0,"subHeadingTitleFontSize":16,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-63002f34-7253-4434-97e2-a5194aee0ef4"><p class="responsive-heading-desc-text">$40.00</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"f966b72b-91a0-415d-92d4-0bb828506858","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":100,"backgroundColor":"#ffffff","backgroundType":"color","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-f966b72b-91a0-415d-92d4-0bb828506858 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontSize":"20px"}},"textColor":"responsive-container-background-color"} -->
    <p class="has-text-align-center has-responsive-container-background-color-color has-text-color" style="font-size:20px"><em>Our food is responsibly caught from sustainable sources</em>.</p>
    <!-- /wp:paragraph --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->
    
    <!-- wp:responsive-block-editor-addons/section {"block_id":"1e10dd20-fc89-4afd-902f-42ab95cdbb6d","topPadding":100,"topPaddingMobile":100,"topPaddingTablet":100,"bottomPadding":100,"bottomPaddingMobile":100,"bottomPaddingTablet":100,"opacity":80,"backgroundImage":"https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/restaurant4.jpg","backgroundPosition":"center center","backgroundImageColor":"#000000","backgroundType":"image","align":"full"} -->
    <div class="responsive-block-editor-addons-block-section-outer-wrap block-1e10dd20-fc89-4afd-902f-42ab95cdbb6d background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"block_id":"3ca682ab-6303-4c30-8ac6-2a63ada16bbb"} -->
    <div class="block-3ca682ab-6303-4c30-8ac6-2a63ada16bbb responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"bottomPaddingMobile":30,"leftPaddingMobile":20,"block_id":"62b6fda3-40d2-49b4-869c-18f1f2dd8679","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-62b6fda3-40d2-49b4-869c-18f1f2dd8679"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"align":"left","id":484,"sizeSlug":"full","linkDestination":"none"} -->
    <div class="wp-block-image"><figure class="alignleft size-full"><img src="https://ccreadysites.cyberchimps.com/restaurant-gutenberg/wp-content/uploads/sites/54/2020/01/restaurant-logo2.png" alt="" class="wp-image-484"/></figure></div>
    <!-- /wp:image --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"bottomPaddingMobile":30,"block_id":"d54d14a8-9723-4ca6-9670-6da3b961ca5b","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-d54d14a8-9723-4ca6-9670-6da3b961ca5b"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"516166aa-a847-4d96-844e-dee99c78cc13","showSubHeading":false,"showSeparator":false,"headSpacing":30,"headSpacingTablet":30,"headSpacingMobile":20,"headingTitleFontSize":29,"headingTitleFontWeight":"400","headingTitleColor":"#ffffff","headingTag":"h5","level":5,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-516166aa-a847-4d96-844e-dee99c78cc13"><h5 class="responsive-heading-title-text">Open Hours</h5></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"inner_gap":0,"labelFontWeight":"400","labelFontSize":16,"labelFontLineHeight":1.6,"block_id":"81bd053d-3e66-4e54-83c4-e9d68b1ce28a"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-81bd053d-3e66-4e54-83c4-e9d68b1ce28a"><div class="responsive-block-editor-addons-icon-wrap-81bd053d-3e66-4e54-83c4-e9d68b1ce28a responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Mon-Sat: 10:00 AM - 08.00 PM","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"#FFFFFF","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"4315e291-5581-43bf-aaf4-0a1a82df2e3a"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-4315e291-5581-43bf-aaf4-0a1a82df2e3a"><div class="responsive-block-editor-addons-icon-4315e291-5581-43bf-aaf4-0a1a82df2e3a responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Mon-Sat: 10:00 AM - 08.00 PM</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Sunday: 10:00 AM - 10.00 PM","icon":"","label_color":"#ffffff","icon_hover_color":"","label_hover_color":"#ffffff","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"09a0461b-f576-4768-a169-ffa5b52c6e3d"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-09a0461b-f576-4768-a169-ffa5b52c6e3d"><div class="responsive-block-editor-addons-icon-09a0461b-f576-4768-a169-ffa5b52c6e3d responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Sunday: 10:00 AM - 10.00 PM</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"bottomPaddingMobile":30,"block_id":"8914dda2-1982-450f-8731-381ed51e8dcf","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-8914dda2-1982-450f-8731-381ed51e8dcf"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"561b14a1-b0f0-4c02-b908-de2673a6a4ca","showSubHeading":true,"showSeparator":false,"headSpacing":30,"subheadSpacing":0,"headSpacingTablet":30,"subheadSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"headingTitleFontSize":29,"headingTitleFontWeight":"400","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingTag":"h5","level":5,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-561b14a1-b0f0-4c02-b908-de2673a6a4ca"><h5 class="responsive-heading-title-text">Location</h5><p class="responsive-heading-desc-text">123, Main Street, Anytown, ST 12345</p></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column -->
    
    <!-- wp:responsive-block-editor-addons/column {"bottomPadding":0,"leftPadding":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"bottomPaddingMobile":0,"block_id":"b33b4082-2f10-4bc4-b534-c8e91349e871","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
    <div class="responsive-block-editor-addons-advanced-column-child block-b33b4082-2f10-4bc4-b534-c8e91349e871"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"e25cd63d-da7c-482f-985f-7e34243f946a","showSubHeading":false,"showSeparator":false,"headSpacing":30,"headSpacingTablet":30,"headSpacingMobile":20,"headingTitleFontSize":29,"headingTitleFontWeight":"400","headingTitleColor":"#ffffff","headingTag":"h5","level":5,"headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
    <div class="responsive-block-editor-addons-block-advanced-heading block-e25cd63d-da7c-482f-985f-7e34243f946a"><h5 class="responsive-heading-title-text">Reservation</h5></div>
    <!-- /wp:responsive-block-editor-addons/advanced-heading -->
    
    <!-- wp:responsive-block-editor-addons/icons-list {"inner_gap":0,"labelFontWeight":"400","labelFontSize":16,"labelFontLineHeight":1.6,"block_id":"e997c781-d52b-413d-a038-769977864231"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-e997c781-d52b-413d-a038-769977864231"><div class="responsive-block-editor-addons-icon-wrap-e997c781-d52b-413d-a038-769977864231 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"+123 4567 890","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"#FFFFFF","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"aa4d904f-b8c9-4eb4-a26e-d13685e9693b"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-aa4d904f-b8c9-4eb4-a26e-d13685e9693b"><div class="responsive-block-editor-addons-icon-aa4d904f-b8c9-4eb4-a26e-d13685e9693b responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">+123 4567 890</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child -->
    
    <!-- wp:responsive-block-editor-addons/icons-list-child {"label":"hello@example.com","icon":"","label_color":"#ffffff","icon_hover_color":"","label_hover_color":"#ffffff","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"19ba865d-453a-4962-9135-b9cf60815e6f"} -->
    <div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-19ba865d-453a-4962-9135-b9cf60815e6f"><div class="responsive-block-editor-addons-icon-19ba865d-453a-4962-9135-b9cf60815e6f responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">hello@example.com</div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
    <!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
    <!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
    <!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
    <!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Menu | Restaurant', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Menu Restaurant', 'responsive-block-editor-addons' ),
		esc_html__( 'Restaurant', 'responsive-block-editor-addons' ),
		esc_html__( 'Cafe', 'responsive-block-editor-addons' ),
		esc_html__( 'Food', 'responsive-block-editor-addons' ),
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
		esc_html__( 'Services', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://picsum.photos/id/1043/356/246',
);
