<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	'type'       => 'layout',
	'key'        => 'rbea_construction_home_layout',
	'collection' => array(
		'slug'      => 'construction',
		'label'     => __( 'Construction', 'responsive-block-editor-addons' ),
		'thumbnail' => 'https://picsum.photos/id/1055/356/246',
	),
	'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"b9177def-9653-4826-b3c9-0a95a7c8b760","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/construction_02.jpg","backgroundPosition":"center right","backgroundType":"image","topPadding":150,"bottomPadding":170,"leftPadding":0,"rightPadding":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":230,"align":"full"} -->
	<div class="responsive-block-editor-addons-block-section-outer-wrap block-b9177def-9653-4826-b3c9-0a95a7c8b760 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"stack":"tablet","block_id":"9683292b-dce5-4e4c-aaca-0147b719545e","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0} -->
	<div class="block-9683292b-dce5-4e4c-aaca-0147b719545e responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-tablet responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"width":52,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":30,"bottomPaddingTablet":30,"leftPaddingTablet":30,"rightPaddingTablet":30,"topPaddingMobile":20,"bottomPaddingMobile":20,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"b0e7f0f4-dd21-4971-8e13-82dd712eff2a","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-b0e7f0f4-dd21-4971-8e13-82dd712eff2a"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"67415c7c-af22-42c9-adcd-76c0368ed033","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":70,"headingTitleFontSizeMobile":42,"headingTitleLineHeight":1.3,"headingTitleColor":"#FFFFFF","subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left"} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-67415c7c-af22-42c9-adcd-76c0368ed033"><h2 class="responsive-heading-title-text">Innovating since 1965</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left"} -->
	<div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"bcf149e3-ea80-4a7b-98b9-fae4e0ed517e","label":"Read More","link":"#","target":false,"vPadding":20,"hPadding":40,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":50,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#333333","background":"#ffdd00","hColor":"#FFFFFF","buttonFontSize":18,"buttonLineHeight":1,"hbackground":"#002240","backgroundType":"color"} -->
	<div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-bcf149e3-ea80-4a7b-98b9-fae4e0ed517e responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><a class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper" href="#"><div class="responsive-block-editor-addons-button__link_child not-inherited-from-theme">Read More</div></a></div></div>
	<!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
	<!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"width":48,"block_id":"6bb57db4-a9c2-436b-ba91-95645a7a69b3","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-6bb57db4-a9c2-436b-ba91-95645a7a69b3"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
	<!-- /wp:responsive-block-editor-addons/section -->
	
	<!-- wp:responsive-block-editor-addons/section {"block_id":"5d60b890-86fe-460e-8561-57f3afe8e985","opacity":0,"backgroundImage":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/construction_04.jpg","backgroundPosition":"center left","backgroundSize":"auto","backgroundAttachment":"fixed","backgroundType":"image","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"align":"full"} -->
	<div class="responsive-block-editor-addons-block-section-outer-wrap block-5d60b890-86fe-460e-8561-57f3afe8e985 background-type-image alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"verticalAlign":"center","block_id":"7e7a7670-955e-4d67-8324-5b18434b660a","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0} -->
	<div class="block-7e7a7670-955e-4d67-8324-5b18434b660a responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":80,"bottomPadding":80,"rightPadding":0,"topPaddingTablet":30,"bottomPaddingTablet":30,"leftPaddingTablet":10,"rightPaddingTablet":10,"topPaddingMobile":20,"bottomPaddingMobile":20,"leftPaddingMobile":20,"rightPaddingMobile":20,"block_id":"613e72fa-ff4d-40fd-9b77-2c6f3c5b6bfb","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-613e72fa-ff4d-40fd-9b77-2c6f3c5b6bfb"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:image {"id":40,"sizeSlug":"large","linkDestination":"none"} -->
	<figure class="wp-block-image size-large"><img src="http://testccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cons-about1-1.jpg" alt="" class="wp-image-40"/></figure>
	<!-- /wp:image --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":60,"bottomPadding":60,"leftPadding":60,"rightPadding":60,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":40,"block_id":"4cd46279-1982-4af1-834b-255834343960","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-4cd46279-1982-4af1-834b-255834343960"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"640df57b-2c7c-4782-b9f9-0f779bd5b022","showSeparator":false,"seperatorStyle":"none","headSpacing":20,"subheadSpacing":20,"headSpacingTablet":20,"subheadSpacingTablet":20,"headSpacingMobile":20,"subheadSpacingMobile":20,"headingTitleFontSize":26,"headingTitleFontWeight":"700","subHeadingTitleLineHeight":1.6,"headingAlignment":"left","headingAlignmentTablet":"left"} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-640df57b-2c7c-4782-b9f9-0f779bd5b022"><h2 class="responsive-heading-title-text">We Are a group of Passionate Architects</h2><p class="responsive-heading-desc-text">Lorem Ipsum has been the industry’s standard dummy text ever since the, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/buttons {"buttonAlignment":"left","buttonAlignmentTablet":"left"} -->
	<div class="wp-block-responsive-block-editor-addons-buttons left tabletAlignleft mobileAligncenter responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap responsive-block-editor-addons-buttons-stack-none"><div class="responsive-block-editor-addons-buttons__wrap responsive-block-editor-addons-buttons-layout-wrap"><!-- wp:responsive-block-editor-addons/buttons-child {"block_id":"d7ca4dd0-1a05-4893-a73c-c4e9c335b954","label":"Read More","link":"#","target":false,"vPadding":20,"hPadding":40,"vPaddingTablet":20,"hPaddingTablet":40,"vPaddingMobile":20,"hPaddingMobile":40,"vMargin":0,"vMarginTablet":0,"vMarginMobile":0,"hMargin":0,"hMarginTablet":0,"hMarginMobile":0,"borderRadius":50,"borderStyle":"none","borderColor":"","borderHColor":"","color":"#ffffff","background":"#002240","hColor":"#333333","buttonFontSize":18,"buttonLineHeight":1,"hbackground":"#ffdd00","backgroundType":"color"} -->
	<div class="wp-block-responsive-block-editor-addons-buttons-child responsive-block-editor-addons-undefined responsive-block-editor-addons-buttons-child block-d7ca4dd0-1a05-4893-a73c-c4e9c335b954 responsive-block-editor-addons-block-button responsive-block-editor-addons-buttons__outer-wrap"><div class="responsive-block-editor-addons-1 responsive-block-editor-addons-button__wrapper responsive-block-editor-addons-button__effect-undefined"><a class="responsive-block-editor-addons-buttons-repeater responsive-block-editor-addons-button__wrapper" href="#"><div class="responsive-block-editor-addons-button__link_child not-inherited-from-theme">Read More</div></a></div></div>
	<!-- /wp:responsive-block-editor-addons/buttons-child --></div></div>
	<!-- /wp:responsive-block-editor-addons/buttons --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
	<!-- /wp:responsive-block-editor-addons/section -->
	
	<!-- wp:responsive-block-editor-addons/section {"block_id":"0df6adcc-1dc3-4e79-ab2c-9109acbe6a29","opacity":100,"backgroundColor":"#f7f7f7","backgroundType":"color","topPadding":80,"bottomPadding":80,"leftPadding":0,"rightPadding":0,"topPaddingMobile":80,"bottomPaddingMobile":80,"leftPaddingMobile":20,"rightPaddingMobile":20,"topPaddingTablet":80,"bottomPaddingTablet":80,"leftPaddingTablet":0,"rightPaddingTablet":0,"align":"full"} -->
	<div class="responsive-block-editor-addons-block-section-outer-wrap block-0df6adcc-1dc3-4e79-ab2c-9109acbe6a29 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"9e68fdf3-e567-41c6-a321-5c2c23d7bc7f","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":26,"headingTitleFontWeight":"700"} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-9e68fdf3-e567-41c6-a321-5c2c23d7bc7f"><h2 class="responsive-heading-title-text">Our Services</h2></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"block_id":"8418ede8-7fac-49ba-bf5b-8a1008ec8b7b","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0} -->
	<div class="block-8418ede8-7fac-49ba-bf5b-8a1008ec8b7b responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"block_id":"a6202254-9682-4b17-a58e-d28fa88d991b","hoverboxShadowColor":"#cacaca","hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-a6202254-9682-4b17-a58e-d28fa88d991b"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"e76e0f1d-86ae-40f1-ad1b-7606eeddadb9","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":51,"title":"con-icon4","filename":"con-icon4.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon4.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon4/","alt":"","author":"17","description":"","caption":"","name":"con-icon4","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:53.000Z","modified":"2020-11-10T05:30:53.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"b54c017c95","delete":"394deca699","edit":"ba2df08952"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=51\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":4923,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon4.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"e76e0f1d-86ae-40f1-ad1b-7606eeddadb9","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-e76e0f1d-86ae-40f1-ad1b-7606eeddadb9"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon4.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Heavy Foundation</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"block_id":"65d29f51-0a8d-4d08-a514-873581bd71bd","hoverboxShadowColor":"#cacaca","hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-65d29f51-0a8d-4d08-a514-873581bd71bd"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"147bf5d7-53cc-4d97-b9af-1ebafa818cbe","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":50,"title":"con-icon3","filename":"con-icon3.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon3.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon3/","alt":"","author":"17","description":"","caption":"","name":"con-icon3","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:51.000Z","modified":"2020-11-10T05:30:51.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"2539aacd2f","delete":"feefeb11d9","edit":"a2345907f4"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=50\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":5288,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon3.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"147bf5d7-53cc-4d97-b9af-1ebafa818cbe","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-147bf5d7-53cc-4d97-b9af-1ebafa818cbe"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon3.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Blue Print Model</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"block_id":"ce145adb-be93-4539-8b18-f8399420e114","hoverboxShadowColor":"#cacaca","hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-ce145adb-be93-4539-8b18-f8399420e114"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"e837a42b-1009-441a-a99a-001d9c4f8a89","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":49,"title":"con-icon2","filename":"con-icon2.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon2.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon2/","alt":"","author":"17","description":"","caption":"","name":"con-icon2","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:49.000Z","modified":"2020-11-10T05:30:49.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"070308f01f","delete":"26da640202","edit":"b05c1f95af"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=49\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":4664,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon2.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"e837a42b-1009-441a-a99a-001d9c4f8a89","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-e837a42b-1009-441a-a99a-001d9c4f8a89"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon2.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Sustainable Model</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":30,"bottomPadding":30,"leftPadding":15,"rightPadding":15,"leftMargin":10,"rightMargin":10,"topMargin":10,"bottomMargin":10,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":0,"block_id":"4361f479-b8c6-41fc-a23e-7563f2e107d7","hoverboxShadowColor":"#cacaca","hoverboxShadowBlur":4,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"color","backgroundColor":"#FFFFFF"} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-4361f479-b8c6-41fc-a23e-7563f2e107d7"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"ee0649ee-779d-4b99-a0fe-7a37ddbad4ab","classMigrate":true,"resheadFontSize":18,"resheadFontWeight":"600","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":52,"title":"con-icon1","filename":"con-icon1.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon1.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/con-icon1/","alt":"","author":"17","description":"","caption":"","name":"con-icon1","status":"inherit","uploadedTo":0,"date":"2020-11-10T05:30:54.000Z","modified":"2020-11-10T05:30:54.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"0425f48f36","delete":"c1117e4d53","edit":"38fb2b4fd2"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=52\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":5219,"filesizeHumanReadable":"5 KB","context":"","height":84,"width":84,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon1.png","height":84,"width":84,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":84,"resshowPrefix":false,"resshowDesc":false,"counterId":"ee0649ee-779d-4b99-a0fe-7a37ddbad4ab","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-ee0649ee-779d-4b99-a0fe-7a37ddbad4ab"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/con-icon1.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"><h3 class="responsive-block-editor-addons-ifb-title">Safety Assurance</h3></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
	<!-- /wp:responsive-block-editor-addons/section -->
	
	<!-- wp:responsive-block-editor-addons/section {"block_id":"45978ffd-0c36-432b-8a79-a91f4c69cbf3","opacity":100,"backgroundColor":"#002240","backgroundType":"color","topPadding":80,"bottomPadding":80,"leftPadding":0,"rightPadding":0,"topPaddingMobile":80,"bottomPaddingMobile":80,"topPaddingTablet":80,"bottomPaddingTablet":80,"align":"full"} -->
	<div class="responsive-block-editor-addons-block-section-outer-wrap block-45978ffd-0c36-432b-8a79-a91f4c69cbf3 background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"38583095-25da-4895-bac4-9d273824fdda","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":42,"headingTitleColor":"#FFFFFF"} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-38583095-25da-4895-bac4-9d273824fdda"><h2 class="responsive-heading-title-text">Portfolio</h2></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/gallery-masonry {"align":"","lightbox":true,"gridSize":"lrg"} -->
	<div class="wp-block-responsive-block-editor-addons-gallery-masonry"><div class="responsive-block-editor-addons-gallery has-no-alignment has-caption-style-dark has-gutter has-lightbox"><ul class="has-grid-lrg has-gutter-15 has-gutter-mobile-15"><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_08-1.jpg" alt="" data-id="395" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_08-1-2/" class="wp-image-395"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_10-1.jpg" alt="" data-id="396" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_10-1-2/" class="wp-image-396"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/construction_12-1.jpg" alt="" data-id="73" data-link="https://ccreadysites.cyberchimps.com/gconstruction/construction_12-1/" class="wp-image-73"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_20-1.jpg" alt="" data-id="401" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_20-1-2/" class="wp-image-401"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_17-1.jpg" alt="" data-id="398" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_17-1-2/" class="wp-image-398"/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2021/06/construction_19-1.jpg" alt="" data-id="400" data-link="https://ccreadysites.cyberchimps.com/gconstruction/home/construction_19-1-2/" class="wp-image-400"/></figure></li></ul></div></div>
	<!-- /wp:responsive-block-editor-addons/gallery-masonry --></div></section></div>
	<!-- /wp:responsive-block-editor-addons/section -->
	
	<!-- wp:responsive-block-editor-addons/section {"block_id":"2e896b24-97ed-4c77-b3de-4e13aefd9923","topPadding":80,"bottomPadding":80,"leftPadding":0,"rightPadding":0,"topPaddingMobile":80,"bottomPaddingMobile":80,"leftPaddingMobile":30,"rightPaddingMobile":30,"topPaddingTablet":80,"bottomPaddingTablet":80,"align":"full"} -->
	<div class="responsive-block-editor-addons-block-section-outer-wrap block-2e896b24-97ed-4c77-b3de-4e13aefd9923 background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"bc616ca7-ee7c-4af1-b77d-a060e1a5ffa8","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":60,"headSpacingTablet":60,"headSpacingMobile":60,"headingTitleFontSize":42} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-bc616ca7-ee7c-4af1-b77d-a060e1a5ffa8"><h2 class="responsive-heading-title-text">Testimonials</h2></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/advance-columns {"block_id":"b1f89c7d-eb72-41c8-ae4f-5833148ebeb2","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0} -->
	<div class="block-b1f89c7d-eb72-41c8-ae4f-5833148ebeb2 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-2"><!-- wp:responsive-block-editor-addons/column {"topPadding":70,"bottomPadding":70,"leftPadding":35,"rightPadding":35,"rightMargin":16,"bottomPaddingMobile":70,"rightMarginMobile":0,"block_id":"5df881b5-4ef0-4a12-89cf-f25c624dcced","blockBorderRadius":5,"boxShadowColor":"#e1dede","boxShadowBlur":10,"hoverboxShadowColor":"#c0c0c0","hoverboxShadowBlur":35,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":100,"backgroundType":"none"} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-5df881b5-4ef0-4a12-89cf-f25c624dcced"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/testimonial {"block_id":"4fbf7606-2e6d-427c-89a0-954a2bc1579e","testimonialBlock":[{"testimonialContent":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​","testimonialTitle":"CEO","testimonialName":"Jane Doe","testimonialImgId":83,"testimonialImgURL":{"id":83,"title":"yoga-marysmith","filename":"yoga-marysmith.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yoga-marysmith.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/yoga-marysmith/","alt":"","author":"17","description":"","caption":"","name":"yoga-marysmith","status":"inherit","uploadedTo":0,"date":"2020-11-10T06:19:24.000Z","modified":"2020-11-10T06:19:24.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"5a9fcb0223","delete":"e787e70681","edit":"b129b04d72"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=83\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":7684,"filesizeHumanReadable":"8 KB","context":"","height":80,"width":80,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yoga-marysmith.png","height":80,"width":80,"orientation":"landscape"}},"compat":{"item":"","meta":""}}}],"count":1,"gutter":"no","testimonialBackgroundColor":"#FFFFFF","testimonialTextColor":"#000000","testimonialNameColor":"#000000","testimonialTitleColor":"#aaaaaa","titleFontSize":14,"titleLineHeight":1.4,"titleFontWeight":"500","nameFontSize":16,"nameLineHeight":1.4,"nameFontWeight":"400","contentFontSize":14,"contentFontWeight":"500","padding":0,"paddingTablet":0,"paddingMobile":0,"contentSpacing":20,"imageSpacing":15,"imageShape":"circle","boxShadowColor":"","boxShadowPosition":"","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":1} -->
	<div class="wp-block-responsive-block-editor-addons-testimonial-wrapper responsive-block-editor-addons-block-testimonial block-4fbf7606-2e6d-427c-89a0-954a2bc1579e has-1-columns has-no-gutter"><div class="wp-block-responsive-block-editor-addons-testimonial left-aligned responsive-block-editor-addons-font-size-undefined testimonial-box responsive-block-editor-addons-block-testimonial image-shape-circle"><div class="responsive-block-editor-addons-testimonial-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​</div><div class="responsive-block-editor-addons-testimonial-info"><div class="responsive-block-editor-addons-testimonial-inner-block"><div class="responsive-block-editor-addons-testimonial-avatar-wrap"><div class="responsive-block-editor-addons-testimonial-image-wrap"><img class="responsive-block-editor-addons-testimonial-avatar" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yoga-marysmith.png" alt="avatar"/></div></div><div class="responsive-block-editor-addons-testimonial-details"><h2 class="responsive-block-editor-addons-testimonial-name">Jane Doe</h2><small class="responsive-block-editor-addons-testimonial-title">CEO</small></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/testimonial --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":70,"bottomPadding":70,"leftPadding":35,"rightPadding":35,"leftMargin":16,"topMargin":0,"bottomPaddingMobile":70,"leftMarginMobile":0,"topMarginMobile":25,"block_id":"ac7d9d6e-27ad-4817-b509-855bbe526669","blockBorderRadius":5,"boxShadowColor":"#e1dede","boxShadowBlur":10,"hoverboxShadowColor":"#c0c0c0","hoverboxShadowBlur":35,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-ac7d9d6e-27ad-4817-b509-855bbe526669"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/testimonial {"block_id":"faaed939-029c-4523-aaa8-2b28b746749d","testimonialBlock":[{"testimonialContent":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​","testimonialTitle":"Architecture","testimonialName":"John Doe","testimonialImgId":84,"testimonialImgURL":{"id":84,"title":"yogarichard-roe","filename":"yogarichard-roe.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yogarichard-roe.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/yogarichard-roe/","alt":"","author":"17","description":"","caption":"","name":"yogarichard-roe","status":"inherit","uploadedTo":0,"date":"2020-11-10T06:19:51.000Z","modified":"2020-11-10T06:19:51.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"5c1428712d","delete":"4ee6b30c95","edit":"9bb827ae50"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=84\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":7085,"filesizeHumanReadable":"7 KB","context":"","height":80,"width":80,"orientation":"landscape","sizes":{"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yogarichard-roe.png","height":80,"width":80,"orientation":"landscape"}},"compat":{"item":"","meta":""}}}],"count":1,"gutter":"no","testimonialBackgroundColor":"#FFFFFF","testimonialTextColor":"#000000","testimonialNameColor":"#000000","testimonialTitleColor":"#aaaaaa","titleFontSize":14,"titleLineHeight":1.4,"titleFontWeight":"500","nameFontSize":16,"nameLineHeight":1.4,"nameFontWeight":"400","contentFontSize":14,"contentFontWeight":"500","padding":0,"paddingTablet":0,"paddingMobile":0,"contentSpacing":20,"imageSpacing":15,"imageShape":"circle","boxShadowColor":"","boxShadowPosition":"","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":"","opacity":1} -->
	<div class="wp-block-responsive-block-editor-addons-testimonial-wrapper responsive-block-editor-addons-block-testimonial block-faaed939-029c-4523-aaa8-2b28b746749d has-1-columns has-no-gutter"><div class="wp-block-responsive-block-editor-addons-testimonial left-aligned responsive-block-editor-addons-font-size-undefined testimonial-box responsive-block-editor-addons-block-testimonial image-shape-circle"><div class="responsive-block-editor-addons-testimonial-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.​</div><div class="responsive-block-editor-addons-testimonial-info"><div class="responsive-block-editor-addons-testimonial-inner-block"><div class="responsive-block-editor-addons-testimonial-avatar-wrap"><div class="responsive-block-editor-addons-testimonial-image-wrap"><img class="responsive-block-editor-addons-testimonial-avatar" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/yogarichard-roe.png" alt="avatar"/></div></div><div class="responsive-block-editor-addons-testimonial-details"><h2 class="responsive-block-editor-addons-testimonial-name">John Doe</h2><small class="responsive-block-editor-addons-testimonial-title">Architecture</small></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/testimonial --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
	<!-- /wp:responsive-block-editor-addons/section -->
	
	<!-- wp:responsive-block-editor-addons/section {"block_id":"ab86028f-bc1c-434a-b86a-3fcea4b975bd","opacity":100,"backgroundColor":"#002240","backgroundType":"color","boxShadowColor":"#ffdd00","boxShadowVOffset":-1.5,"topPadding":80,"bottomPadding":80,"leftPadding":0,"rightPadding":0,"topPaddingMobile":40,"bottomPaddingMobile":40,"leftPaddingMobile":0,"rightPaddingMobile":0,"topPaddingTablet":40,"bottomPaddingTablet":40,"leftPaddingTablet":0,"rightPaddingTablet":0,"align":"full"} -->
	<div class="responsive-block-editor-addons-block-section-outer-wrap block-ab86028f-bc1c-434a-b86a-3fcea4b975bd background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advance-columns {"columns":3,"block_id":"b60f1609-dc0a-4e16-9a2a-acebbf821341","topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0} -->
	<div class="block-b60f1609-dc0a-4e16-9a2a-acebbf821341 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-3"><!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"bottomMarginMobile":30,"block_id":"6899b6b3-83af-4633-b629-3c1c8525335e","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-6899b6b3-83af-4633-b629-3c1c8525335e"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"443dc391-297a-49fb-a8c7-9204b2ead4ca","classMigrate":true,"resheadingAlign":"left","ressubheadingColor":"#FFFFFF","ressubHeadFontSize":14,"ressubHeadFontWeight":"500","resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":20,"iconImage":{"id":95,"title":"cont-logo-white","filename":"cont-logo-white.png","url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white.png","link":"https://ccreadysites.cyberchimps.com/gconstruction/cont-logo-white/","alt":"","author":"17","description":"","caption":"","name":"cont-logo-white","status":"inherit","uploadedTo":0,"date":"2020-11-10T06:49:30.000Z","modified":"2020-11-10T06:49:30.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gconstruction/wp-includes/images/media/default.png","dateFormatted":"November 10, 2020","nonces":{"update":"da90a26a45","delete":"00ff8d0b56","edit":"c89ed11068"},"editLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/post.php?post=95\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gconstruction/wp-admin/profile.php","filesizeInBytes":1929,"filesizeHumanReadable":"2 KB","context":"","height":26,"width":185,"orientation":"landscape","sizes":{"thumbnail":{"height":26,"width":150,"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white-150x26.png","orientation":"landscape"},"full":{"url":"https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white.png","height":26,"width":185,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"imageWidth":185,"resshowPrefix":false,"resshowTitle":false,"counterId":"443dc391-297a-49fb-a8c7-9204b2ead4ca","opacity":0,"sepSpace":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-443dc391-297a-49fb-a8c7-9204b2ead4ca"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gconstruction/wp-content/uploads/sites/108/2020/11/cont-logo-white.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><p class="responsive-block-editor-addons-ifb-desc">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</p><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":10,"bottomMarginMobile":30,"block_id":"22af5cc0-45f9-4664-81ad-0e5203405966","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-22af5cc0-45f9-4664-81ad-0e5203405966"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"cbf31ec4-dd83-4c91-b103-133ee83cd645","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":18,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-cbf31ec4-dd83-4c91-b103-133ee83cd645"><h2 class="responsive-heading-title-text">Quick Links</h2></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/icons-list {"gap":0,"inner_gap":0,"labelFontWeight":"500","labelFontSize":14,"block_id":"50c3cca2-b486-4167-b231-b0a7a9fdbc27","labelFontLineHeight":1.6} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-50c3cca2-b486-4167-b231-b0a7a9fdbc27"><div class="responsive-block-editor-addons-icon-wrap-50c3cca2-b486-4167-b231-b0a7a9fdbc27 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Home","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"02cc479b-235c-46f6-8367-7a64bd5e2f0d"} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-02cc479b-235c-46f6-8367-7a64bd5e2f0d"><a target="_self" rel="noopener noreferrer" aria-label="Home" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-02cc479b-235c-46f6-8367-7a64bd5e2f0d responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Home</div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list-child -->
	
	<!-- wp:responsive-block-editor-addons/icons-list-child {"label":"About","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"187d8d88-038c-4038-a1ce-4b024ce5118f"} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-187d8d88-038c-4038-a1ce-4b024ce5118f"><a target="_self" rel="noopener noreferrer" aria-label="About" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-187d8d88-038c-4038-a1ce-4b024ce5118f responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">About</div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list-child -->
	
	<!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Blog","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"603d89ad-2510-47f9-8337-7f7aa0750fd8"} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-603d89ad-2510-47f9-8337-7f7aa0750fd8"><a target="_self" rel="noopener noreferrer" aria-label="Blog" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-603d89ad-2510-47f9-8337-7f7aa0750fd8 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Blog</div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list-child -->
	
	<!-- wp:responsive-block-editor-addons/icons-list-child {"label":"Contact","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","disableLink":false,"block_id":"037065b2-24c8-4c68-8d27-bca8be95a3a6"} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-037065b2-24c8-4c68-8d27-bca8be95a3a6"><a target="_self" rel="noopener noreferrer" aria-label="Contact" href="#" class="wp-responsive-block-editor-addons-icon-list responsive-block-editor-addons-icon-list-link"></a><div class="responsive-block-editor-addons-icon-037065b2-24c8-4c68-8d27-bca8be95a3a6 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">Contact</div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column -->
	
	<!-- wp:responsive-block-editor-addons/column {"topPadding":10,"bottomPadding":10,"leftPadding":10,"rightPadding":30,"rightPaddingTablet":10,"bottomMarginMobile":30,"block_id":"34bf834a-35c9-45f3-bce9-b20140d749af","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
	<div class="responsive-block-editor-addons-advanced-column-child block-34bf834a-35c9-45f3-bce9-b20140d749af"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"81afcb20-aaee-462d-a5cb-3c64adea0b29","showSubHeading":false,"showSeparator":false,"seperatorStyle":"none","headSpacing":20,"headSpacingTablet":20,"headSpacingMobile":20,"headingTitleFontSize":18,"headingTitleColor":"#FFFFFF","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
	<div class="responsive-block-editor-addons-block-advanced-heading block-81afcb20-aaee-462d-a5cb-3c64adea0b29"><h2 class="responsive-heading-title-text">Contact Us</h2></div>
	<!-- /wp:responsive-block-editor-addons/advanced-heading -->
	
	<!-- wp:responsive-block-editor-addons/icons-list {"gap":20,"inner_gap":0,"labelFontWeight":"500","labelFontSize":14,"block_id":"1df4bc4a-190c-467a-ae84-f0e6278f86e9","labelFontLineHeight":1.6} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list vertical responsive-block-editor-addons-icon-list__outer-wrap responsive-block-editor-addons-icon-list__layout-vertical responsive-block-editor-addons-1df4bc4a-190c-467a-ae84-f0e6278f86e9"><div class="responsive-block-editor-addons-icon-wrap-1df4bc4a-190c-467a-ae84-f0e6278f86e9 responsive-block-editor-addons-icon-list__wrap"><!-- wp:responsive-block-editor-addons/icons-list-child {"label":"123, Main street, Anytown ST 12345.","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"f906f8cb-8b80-4765-bfbf-d505214c91f6"} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-f906f8cb-8b80-4765-bfbf-d505214c91f6"><div class="responsive-block-editor-addons-icon-f906f8cb-8b80-4765-bfbf-d505214c91f6 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">123, Main street, Anytown ST 12345.</div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list-child -->
	
	<!-- wp:responsive-block-editor-addons/icons-list-child {"label":"+123-456-7890","icon":"","label_color":"#FFFFFF","icon_hover_color":"","label_hover_color":"","icon_bg_color":"","icon_bg_hover_color":"","icon_border_color":"","icon_border_hover_color":"","block_id":"b9722062-e5ca-475f-ad94-145ad380b017"} -->
	<div class="wp-block-responsive-block-editor-addons-icons-list-child responsive-block-editor-addons-icon-list-repeater responsive-block-editor-addons-icon-list__wrapper responsive-block-editor-addons-b9722062-e5ca-475f-ad94-145ad380b017"><div class="responsive-block-editor-addons-icon-b9722062-e5ca-475f-ad94-145ad380b017 responsive-block-editor-addons-icon-list__content-wrap"><span class="responsive-block-editor-addons-icon-list__source-wrap"></span><div class="responsive-block-editor-addons-icon-list__label-wrap"><div class="responsive-block-editor-addons-icon-list__label">+123-456-7890</div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list-child --></div></div>
	<!-- /wp:responsive-block-editor-addons/icons-list --></div></div></div>
	<!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
	<!-- /wp:responsive-block-editor-addons/advance-columns --></div></section></div>
	<!-- /wp:responsive-block-editor-addons/section -->',
	'name'       => esc_html__( 'Construction', 'responsive-block-editor-addons' ),
	'category'   => array(
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'keywords'   => array(
		esc_html__( 'Construction', 'responsive-block-editor-addons' ),
		esc_html__( 'Architect', 'responsive-block-editor-addons' ),
		esc_html__( 'Building Safety', 'responsive-block-editor-addons' ),
		esc_html__( 'Safety', 'responsive-block-editor-addons' ),
		esc_html__( 'Business', 'responsive-block-editor-addons' ),
	),
	'image'      => 'https://ccreadysites.cyberchimps.com/wp-content/uploads/2021/09/Construction.jpg',
);
