<?php
/**
 * RBEA Templates.
 *
 * @package Responsive Blocks
 */

return array(
	array(
		'type'       => 'section',
		'key'        => 'rbea-portfolio-corpb-section',
		'collection' => array(
			'slug'      => 'rbea-portfolio-section',
			'label'     => __( 'Portfolio', 'responsive-block-editor-addons' ),
			'thumbnail' => 'https://picsum.photos/id/1041/356/246',
		),
		'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"258e2589-8a62-4f1c-9139-58bae2ef174f","topPadding":110,"topPaddingMobile":110,"topPaddingTablet":110,"bottomPadding":110,"bottomPaddingMobile":110,"bottomPaddingTablet":110,"opacity":100,"align":"full"} -->
		<div class="responsive-block-editor-addons-block-section-outer-wrap block-258e2589-8a62-4f1c-9139-58bae2ef174f background-type-none alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"6fa40d77-b303-4879-8d8c-151c48380f34","showSubHeading":false,"showSeparator":false,"headSpacing":20,"subheadSpacing":0,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"headingTitleFontSize":20,"headingTitleFontSizeMobile":20,"headingTitleFontSizeTablet":20,"headingTitleColor":"#166dd5","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
		<div class="responsive-block-editor-addons-block-advanced-heading block-6fa40d77-b303-4879-8d8c-151c48380f34"><h2 class="responsive-heading-title-text">Portfolio</h2></div>
		<!-- /wp:responsive-block-editor-addons/advanced-heading -->
		
		<!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"d4ab9250-79c8-433e-b69d-d08ebcf51abd","showSubHeading":true,"showSeparator":false,"headSpacing":20,"subheadSpacing":100,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":100,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":100,"separatorSpacingMobile":0,"headingTitleFontFamily":"Inter","headingTitleFontSize":32,"headingTitleFontSizeMobile":32,"headingTitleFontSizeTablet":32,"headingTitleColor":"#071e57","subHeadingTitleFontFamily":"Inter","subHeadingTitleFontSize":18,"subHeadingTitleFontSizeMobile":18,"subHeadingTitleFontSizeTablet":18,"subHeadingTitleLineHeight":1.8,"subHeadingTitleColor":"#748494","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
		<div class="responsive-block-editor-addons-block-advanced-heading block-d4ab9250-79c8-433e-b69d-d08ebcf51abd"><h2 class="responsive-heading-title-text">Our work — digital marketing case studies</h2><p class="responsive-heading-desc-text">We work with forward-looking organizations who understand that joining the global startup economy is key to drive innovation and spur economic growth.</p></div>
		<!-- /wp:responsive-block-editor-addons/advanced-heading -->
		
		<!-- wp:responsive-block-editor-addons/gallery-masonry {"align":"","gutter":20,"gutterMobile":20,"lightbox":true,"gridSize":"lrg"} -->
		<div class="wp-block-responsive-block-editor-addons-gallery-masonry"><div class="responsive-block-editor-addons-gallery has-no-alignment has-caption-style-dark has-gutter has-lightbox"><ul class="has-grid-lrg has-gutter-20 has-gutter-mobile-20"><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gcorporate-business/wp-content/uploads/sites/115/2020/12/project3-1.jpg" alt="" data-id="" data-link="https://ccreadysites.cyberchimps.com/gcorporate-business/project3-1/" class=""/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gcorporate-business/wp-content/uploads/sites/115/2020/12/project2-1.jpg" alt="" data-id="" data-link="https://ccreadysites.cyberchimps.com/gcorporate-business/project2-1/" class=""/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gcorporate-business/wp-content/uploads/sites/115/2020/12/project6.jpg" alt="" data-id="" data-link="https://ccreadysites.cyberchimps.com/gcorporate-business/project6/" class=""/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gcorporate-business/wp-content/uploads/sites/115/2020/12/project5-1.jpg" alt="" data-id="" data-link="https://ccreadysites.cyberchimps.com/gcorporate-business/project5-1/" class=""/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gcorporate-business/wp-content/uploads/sites/115/2020/12/project4-1.jpg" alt="" data-id="" data-link="https://ccreadysites.cyberchimps.com/gcorporate-business/project4-1/" class=""/></figure></li><li class="responsive-block-editor-addons-gallery--item"><figure class="responsive-block-editor-addons-gallery--figure"><img src="https://ccreadysites.cyberchimps.com/gcorporate-business/wp-content/uploads/sites/115/2020/12/corpo-portfolio.jpg" alt="" data-id="" data-link="https://ccreadysites.cyberchimps.com/gcorporate-business/corpo-portfolio/" class=""/></figure></li></ul></div></div>
		<!-- /wp:responsive-block-editor-addons/gallery-masonry --></div></section></div>
		<!-- /wp:responsive-block-editor-addons/section -->',
		'name'       => esc_html__( 'Portfolio | Corporate Business', 'responsive-block-editor-addons' ),
		'category'   => array(
			esc_html__( 'Portfolio', 'responsive-block-editor-addons' ),
		),
		'keywords'   => array(
			esc_html__( 'Portfolio', 'responsive-block-editor-addons' ),
			esc_html__( 'Portfolio Corporate Business', 'responsive-block-editor-addons' ),
			esc_html__( 'Corporate Business', 'responsive-block-editor-addons' ),
			esc_html__( 'Business', 'responsive-block-editor-addons' ),
		),
		'image'      => 'https://ccreadysites.cyberchimps.com/wp-content/uploads/2021/08/Portfolio-Corporate-Business.jpg',
	),
	array(
		'type'       => 'section',
		'key'        => 'rbea-portfolio-photography-section',
		'collection' => array(
			'slug'      => 'rbea-portfolio-section',
			'label'     => __( 'Portfolio', 'responsive-block-editor-addons' ),
			'thumbnail' => 'https://picsum.photos/id/1041/356/246',
		),
		'content'    => '<!-- wp:responsive-block-editor-addons/section {"block_id":"6a56ea6f-2cb6-4fed-8593-5dac1f274b6c","topPadding":110,"topPaddingMobile":110,"topPaddingTablet":110,"bottomPadding":70,"bottomPaddingMobile":70,"bottomPaddingTablet":70,"opacity":100,"backgroundColor":"#000000","backgroundType":"color","align":"full"} -->
		<div class="responsive-block-editor-addons-block-section-outer-wrap block-6a56ea6f-2cb6-4fed-8593-5dac1f274b6c background-type-color alignfull"><section class="responsive-section-wrap responsive-block-editor-addons-block-section overlay-type-color linear"><div class="responsive-section-inner-wrap"><!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"c998f7ff-7f4f-41a2-ac4d-68be472c5e67","showSubHeading":false,"showSeparator":false,"headSpacing":20,"subheadSpacing":20,"separatorSpacing":0,"headSpacingTablet":20,"subheadSpacingTablet":20,"separatorSpacingTablet":0,"headSpacingMobile":20,"subheadSpacingMobile":20,"separatorSpacingMobile":0,"headingTitleFontSize":50,"headingTitleFontSizeMobile":50,"headingTitleFontSizeTablet":50,"headingTitleFontWeight":"700","headingTitleColor":"#ffffff","subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
		<div class="responsive-block-editor-addons-block-advanced-heading block-c998f7ff-7f4f-41a2-ac4d-68be472c5e67"><h2 class="responsive-heading-title-text">Portfolio</h2></div>
		<!-- /wp:responsive-block-editor-addons/advanced-heading -->
		
		<!-- wp:responsive-block-editor-addons/advance-columns {"columns":4,"topPadding":0,"bottomPadding":0,"leftPadding":0,"rightPadding":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"verticalAlign":"center","block_id":"4e5258cc-74bf-4d77-87c0-e08b04682533"} -->
		<div class="block-4e5258cc-74bf-4d77-87c0-e08b04682533 responsive-block-editor-addons-advanced-column-outer-wrap undefined"><div class="responsive-block-editor-addons-advanced-column alignundefined"><div class="responsive-columns-wrap responsive-block-editor-addons-block-columns responsive-columns__gap-default responsive-columns__stack-mobile responsive-columns__content-width-theme overlay-type-color linear"><div class="responsive-columns-inner-wrap responsive-columns-columns-4"><!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"leftMargin":0,"rightMargin":0,"topMargin":0,"bottomMargin":0,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginTablet":0,"bottomMarginTablet":0,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"leftMarginMobile":0,"rightMarginMobile":0,"topMarginMobile":0,"bottomMarginMobile":0,"block_id":"f67c9303-0aaa-408b-a6f6-b47d3602d968","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="responsive-block-editor-addons-advanced-column-child block-f67c9303-0aaa-408b-a6f6-b47d3602d968"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"c62be03a-5eb7-4a37-a328-12636a82fcee","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":120,"title":"portfolio","filename":"portfolio.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio-2/","alt":"","author":"17","description":"","caption":"","name":"portfolio-2","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:31:16.000Z","modified":"2020-12-23T07:31:16.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"65fbc4be3b","delete":"7932be1ca4","edit":"792e0bb532"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=120\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":193599,"filesizeHumanReadable":"189 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"c62be03a-5eb7-4a37-a328-12636a82fcee","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-c62be03a-5eb7-4a37-a328-12636a82fcee"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
		<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
		<!-- /wp:responsive-block-editor-addons/column -->
		
		<!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"ba8f4dfd-2862-4835-9d9f-b6a0c91b1930","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="responsive-block-editor-addons-advanced-column-child block-ba8f4dfd-2862-4835-9d9f-b6a0c91b1930"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"2cc0347b-de98-4449-b243-1fb6c8b2b230","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":125,"title":"portfolio1","filename":"portfolio1.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio1/","alt":"","author":"17","description":"","caption":"","name":"portfolio1","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:43:44.000Z","modified":"2020-12-23T07:43:44.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"eae7072855","delete":"6217b093fb","edit":"493176309f"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=125\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":207976,"filesizeHumanReadable":"203 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"2cc0347b-de98-4449-b243-1fb6c8b2b230","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-2cc0347b-de98-4449-b243-1fb6c8b2b230"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio1.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
		<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
		<!-- /wp:responsive-block-editor-addons/column -->
		
		<!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"29c26e77-02b6-4a08-bc56-e825194df6bd","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="responsive-block-editor-addons-advanced-column-child block-29c26e77-02b6-4a08-bc56-e825194df6bd"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"25601283-62d4-4ac0-b6e9-a120035ff98d","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":126,"title":"portfolio2","filename":"portfolio2.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio2/","alt":"","author":"17","description":"","caption":"","name":"portfolio2","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:44:38.000Z","modified":"2020-12-23T07:44:38.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"76958ea579","delete":"2411062033","edit":"0cb454ef20"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=126\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":152480,"filesizeHumanReadable":"149 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"25601283-62d4-4ac0-b6e9-a120035ff98d","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-25601283-62d4-4ac0-b6e9-a120035ff98d"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio2.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
		<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
		<!-- /wp:responsive-block-editor-addons/column -->
		
		<!-- wp:responsive-block-editor-addons/column {"width":25,"topPadding":50,"bottomPadding":50,"leftPadding":0,"rightPadding":50,"topPaddingTablet":20,"bottomPaddingTablet":20,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":10,"bottomPaddingMobile":10,"leftPaddingMobile":10,"rightPaddingMobile":10,"block_id":"a4e31699-07cf-415c-8059-fecf27f6cb15","hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="responsive-block-editor-addons-advanced-column-child block-a4e31699-07cf-415c-8059-fecf27f6cb15"><div class="responsive-column-wrap responsive-block-editor-addons-block-column"><div class="responsive-column-inner-wrap overlay-type-color linear"><!-- wp:responsive-block-editor-addons/info-block {"block_id":"5cc399a4-5edd-4439-b9ba-3b550d3bfef3","classMigrate":true,"resheadSpace":0,"ressubHeadSpace":0,"source_type":"image","resseperatorStyle":"none","resprefixSpace":0,"iconTopMargin":0,"iconBottomMargin":0,"iconImage":{"id":127,"title":"portfolio3","filename":"portfolio3.png","url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3.png","link":"https://ccreadysites.cyberchimps.com/gphotography-studio/portfolio3/","alt":"","author":"17","description":"","caption":"","name":"portfolio3","status":"inherit","uploadedTo":0,"date":"2020-12-23T07:45:23.000Z","modified":"2020-12-23T07:45:23.000Z","menuOrder":0,"mime":"image/png","type":"image","subtype":"png","icon":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-includes/images/media/default.png","dateFormatted":"December 23, 2020","nonces":{"update":"98208014ed","delete":"5e8ecd791e","edit":"c28215c22d"},"editLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/post.php?post=127\u0026action=edit","meta":false,"authorName":"Murtuza Shaikh","authorLink":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-admin/profile.php","filesizeInBytes":57917,"filesizeHumanReadable":"57 KB","context":"","height":440,"width":280,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3-150x150.png","orientation":"landscape"},"medium":{"height":300,"width":191,"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3-191x300.png","orientation":"portrait"},"full":{"url":"https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3.png","height":440,"width":280,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"imageWidth":230,"imageWidthTablet":142.75,"imageWidthMobile":280,"resshowPrefix":false,"resshowTitle":false,"resshowDesc":false,"counterId":"5cc399a4-5edd-4439-b9ba-3b550d3bfef3","opacity":0,"sepSpace":0,"resImageBorderStyle":"solid","resImageBorderRadius":8,"resImageBorderWidth":0,"hoverboxShadowColor":"","hoverboxShadowBlur":0,"hoverboxShadowSpread":0,"hoverboxShadowPosition":""} -->
		<div class="wp-block-responsive-block-editor-addons-info-block responsive-block-editor-addons-infobox__outer-wrap responsive-blocks-block-team responsive-block-editor-addons-block-info-block block-5cc399a4-5edd-4439-b9ba-3b550d3bfef3"><div class="responsive-block-editor-addons-infobox__content-wrap responsive-block-editor-addons-infobox responsive-block-editor-addons-infobox-has-image responsive-block-editor-addons-infobox-icon-above-title responsive-block-editor-addons-infobox-image-valign-top responsive-block-editor-addons-infobox-enable-border-radius "><div class="responsive-block-editor-addons-ifb-left-right-wrap"><div class="responsive-block-editor-addons-ifb-content"><div class="responsive-block-editor-addons-ifb-image-icon-content responsive-block-editor-addons-ifb-imgicon-wrap"><div class="responsive-block-editor-addons-ifb-image"><div class="responsive-block-editor-addons-ifb-image-content"><img class="" src="https://ccreadysites.cyberchimps.com/gphotography-studio/wp-content/uploads/sites/118/2020/12/portfolio3.png" alt=""/></div></div></div><div class="responsive-block-editor-addons-ifb-title-wrap"></div><div class="responsive-block-editor-addons-ifb-text-wrap"><div class="responsive-block-editor-addons-ifb-cta responsive-block-editor-addons-infobox-cta-link-style"></div></div></div></div></div></div>
		<!-- /wp:responsive-block-editor-addons/info-block --></div></div></div>
		<!-- /wp:responsive-block-editor-addons/column --></div></div></div></div>
		<!-- /wp:responsive-block-editor-addons/advance-columns -->
		
		<!-- wp:responsive-block-editor-addons/advanced-heading {"block_id":"529464af-a63e-4226-a41b-63bcb87167eb","showHeading":false,"showSeparator":false,"seperatorPosition":"belowDesc","separatorHeight":2,"separatorWidth":81,"separatorWidthType":"px","separatorColor":"#ffffff","subheadSpacing":0,"separatorSpacing":0,"subheadSpacingTablet":0,"separatorSpacingTablet":0,"subheadSpacingMobile":0,"separatorSpacingMobile":0,"subHeadingTitleFontSize":16,"subHeadingTitleFontSizeMobile":16,"subHeadingTitleFontSizeTablet":16,"subHeadingTitleLineHeight":1.6,"subHeadingTitleColor":"#ffffff","headingAlignment":"left","headingAlignmentTablet":"left","headingAlignmentMobile":"left"} -->
		<div class="responsive-block-editor-addons-block-advanced-heading block-529464af-a63e-4226-a41b-63bcb87167eb"><p class="responsive-heading-desc-text"><a href="#"><span class="has-inline-color has-button-hover-text-color-color"><span style="text-decoration: underline">Browse All</span></span></a></p></div>
		<!-- /wp:responsive-block-editor-addons/advanced-heading --></div></section></div>
		<!-- /wp:responsive-block-editor-addons/section -->',
		'name'       => esc_html__( 'Portfolio | Photography Studio', 'responsive-block-editor-addons' ),
		'category'   => array(
			esc_html__( 'Portfolio', 'responsive-block-editor-addons' ),
		),
		'keywords'   => array(
			esc_html__( 'Portfolio', 'responsive-block-editor-addons' ),
			esc_html__( 'Portfolio Photography Studio', 'responsive-block-editor-addons' ),
			esc_html__( 'Photography Studio', 'responsive-block-editor-addons' ),
		),
		'image'      => 'https://ccreadysites.cyberchimps.com/wp-content/uploads/2021/08/Portfolio-Photo-Studio-1.jpg',
	),
);
